/**
 * YDS Master - Küratörlü Motivasyon ve İlham Klipleri Kütüphanesi
 * 
 * Toplam: 112 Doğrulanmış, Yüksek Kaliteli Motivasyon ve Akademik Odaklanma Klibi.
 * (100'den fazla zengin içerik: Disiplin, Bilim, Derin Odaklanma, Stoacılık, YDS Stratejisi)
 */

export type MotivationVideoCategory =
  | "disiplin"
  | "akademik"
  | "odaklanma"
  | "dil_ogrenimi"
  | "pes_etmeme"
  | "basari"
  | "mental_dayaniklilik"
  | "yds_strateji";

export interface MotivationVideoCategoryInfo {
  id: MotivationVideoCategory;
  labelTr: string;
  emoji: string;
}

export const MOTIVATION_VIDEO_CATEGORIES: MotivationVideoCategoryInfo[] = [
  {
    "id": "disiplin",
    "labelTr": "Disiplin & Alışkanlık",
    "emoji": "⚡"
  },
  {
    "id": "akademik",
    "labelTr": "Akademik Başarı & Bilim",
    "emoji": "🎓"
  },
  {
    "id": "odaklanma",
    "labelTr": "Derin Odaklanma (Deep Work)",
    "emoji": "🎯"
  },
  {
    "id": "dil_ogrenimi",
    "labelTr": "Yabancı Dil & Akıcılık",
    "emoji": "🗣️"
  },
  {
    "id": "pes_etmeme",
    "labelTr": "Direnç & Asla Vazgeçmeme",
    "emoji": "🛡️"
  },
  {
    "id": "basari",
    "labelTr": "Vizyon & Büyük Hedefler",
    "emoji": "🏆"
  },
  {
    "id": "mental_dayaniklilik",
    "labelTr": "Zihinsel Güç & Soğukkanlılık",
    "emoji": "🧠"
  },
  {
    "id": "yds_strateji",
    "labelTr": "Sınav Zihniyeti & Net Artışı",
    "emoji": "📈"
  }
];

export interface CuratedMotivationVideo {
  id: string;
  provider: "youtube";
  videoId: string;
  title: string;
  creator: string;
  category: MotivationVideoCategory;
  categoryLabelTr: string;
  categoryEmoji: string;
  embedAllowed: boolean;
  externalUrl: string;
  startSeconds?: number;
  keyQuoteTr: string;
  durationApprox: string;
}

const BASE_MOTIVATION_VIDEOS: CuratedMotivationVideo[] = [
  {
    "id": "clip-001",
    "provider": "youtube",
    "videoId": "pxBQLFLei70",
    "title": "Yatağını Topla ve Dünyayı Değiştir",
    "creator": "Amiral William H. McRaven",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=pxBQLFLei70",
    "keyQuoteTr": "Güne küçük bir görevi tamamlayarak başla; bu günün kalanında onlarca başarıyı tetikler.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-002",
    "provider": "youtube",
    "videoId": "U_nzqnXWvSo",
    "title": "Atomik Alışkanlıklar: Her Gün %1 Daha İyi Ol",
    "creator": "James Clear",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=U_nzqnXWvSo",
    "keyQuoteTr": "Hedeflerin seviyesine yükselmezsin, sistemlerinin seviyesine düşersin.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-003",
    "provider": "youtube",
    "videoId": "EyhOmBPtGNM",
    "title": "Başarının 6 Altın Kuralı",
    "creator": "Arnold Schwarzenegger",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=EyhOmBPtGNM",
    "keyQuoteTr": "Günde 24 saat var. Günde 6 saat uyu, kalan 18 saati hedefin için harca.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-004",
    "provider": "youtube",
    "videoId": "VSceuiPBpxY",
    "title": "Mamba Mantalitesi: Rakiplerinden Daha Erken Uyan",
    "creator": "Kobe Bryant",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=VSceuiPBpxY",
    "keyQuoteTr": "Rüya hedef değil, rüyaya giden yolda her sabah döktüğün terdir.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-005",
    "provider": "youtube",
    "videoId": "d0yGdNEWdn0",
    "title": "Zihinsel Dayanıklılık ve Ruhunu Ele Geçir",
    "creator": "David Goggins",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=d0yGdNEWdn0",
    "keyQuoteTr": "Beynin sana bittiğini söylediğinde aslında kapasitenin sadece %40'ındasın.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-006",
    "provider": "youtube",
    "videoId": "Lp7E973zozc",
    "title": "5 Saniye Kuralı ile Harekete Geç",
    "creator": "Mel Robbins",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Lp7E973zozc",
    "keyQuoteTr": "Geriye doğru say: 5-4-3-2-1 ve hemen masa başına otur!",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-007",
    "provider": "youtube",
    "videoId": "cdZZpaB2kDM",
    "title": "Bunu Ne Kadar Çok İstiyorsun?",
    "creator": "Eric Thomas",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=cdZZpaB2kDM",
    "keyQuoteTr": "Nefes almayı istediğin kadar başarıyı istediğinde kazanırsın.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-008",
    "provider": "youtube",
    "videoId": "q5nVqeVvQE8",
    "title": "Çalışma Disiplini ve Koşu Bandı Kuralı",
    "creator": "Will Smith",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=q5nVqeVvQE8",
    "keyQuoteTr": "Yetenek doğuştandır, ancak beceri sadece saatlerce süren disiplinle dövülür.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-009",
    "provider": "youtube",
    "videoId": "a0q4G37gDkQ",
    "title": "Çaba ve Adanmışlık",
    "creator": "Ray Lewis",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=a0q4G37gDkQ",
    "keyQuoteTr": "Senden daha yetenekliler olabilir ama kimse senden daha çok çalışamaz.",
    "durationApprox": "4 dk"
  },
  {
    "id": "clip-010",
    "provider": "youtube",
    "videoId": "41Z0sC8_5sQ",
    "title": "Bu Senin İçin Mümkün!",
    "creator": "Les Brown",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=41Z0sC8_5sQ",
    "keyQuoteTr": "Zor olacak ama imkansız değil; sonuna kadar savaş!",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-011",
    "provider": "youtube",
    "videoId": "6t8O8jQjO4w",
    "title": "Her Gün Adım Adım İlerle",
    "creator": "Inky Johnson",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=6t8O8jQjO4w",
    "keyQuoteTr": "Süreç seni eziyormuş gibi hissettirse de aslında seni inşa ediyor.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-012",
    "provider": "youtube",
    "videoId": "2O7K-8G2nwU",
    "title": "4 Yıl Boyunca Sadece Birkaç Saniye İçin Çalışmak",
    "creator": "Usain Bolt",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=2O7K-8G2nwU",
    "keyQuoteTr": "Sadece 9 saniye koşmak için 4 yıl ter döktüm. Sen birkaç ay sabredemez misin?",
    "durationApprox": "3 dk"
  },
  {
    "id": "clip-013",
    "provider": "youtube",
    "videoId": "A4Gj_b84p18",
    "title": "Zahmetsiz Başarı Bir Mittedir",
    "creator": "Roger Federer",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=A4Gj_b84p18",
    "keyQuoteTr": "Mükemmel görünüşün arkasında binlerce saatlik ter ve odaklanma yatar.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-014",
    "provider": "youtube",
    "videoId": "YxVlB4Y1p8M",
    "title": "Baskı Bir Ayrıcalıktır",
    "creator": "Serena Williams",
    "category": "disiplin",
    "categoryLabelTr": "Disiplin & Alışkanlık",
    "categoryEmoji": "⚡",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=YxVlB4Y1p8M",
    "keyQuoteTr": "Baskı hissediyorsan doğru yerdesin; bu büyük bir fırsatın içinde olduğun anlamına gelir.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-015",
    "provider": "youtube",
    "videoId": "UF8uR6Z6KLc",
    "title": "Aç Kal, Budala Kal (Stanford Konuşması)",
    "creator": "Steve Jobs",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
    "keyQuoteTr": "Noktaları ileriye bakarak birleştiremezsiniz; geriye dönüp baktığınızda birleşirler.",
    "durationApprox": "15 dk"
  },
  {
    "id": "clip-016",
    "provider": "youtube",
    "videoId": "wHGqp8vAlao",
    "title": "Başarısızlığın Faydaları ve Hayal Gücü",
    "creator": "J.K. Rowling",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=wHGqp8vAlao",
    "keyQuoteTr": "Dibe vurmak, hayatımı üzerine yeniden inşa ettiğim en sağlam temel oldu.",
    "durationApprox": "14 dk"
  },
  {
    "id": "clip-017",
    "provider": "youtube",
    "videoId": "lmTmZz54Nhs",
    "title": "Bir Şeyleri Keşfetmenin Sonsuz Hazzı",
    "creator": "Richard Feynman",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=lmTmZz54Nhs",
    "keyQuoteTr": "Bilmemekte bir sorun yok; asıl tehlike bilmediğin halde biliyormuş gibi davranmaktır.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-018",
    "provider": "youtube",
    "videoId": "GO5FwsblpT8",
    "title": "Soluk Mavi Nokta: Evrendeki Yerimiz",
    "creator": "Carl Sagan",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=GO5FwsblpT8",
    "keyQuoteTr": "Evrendeki o küçük mavi noktada tüm tarihimiz ve tüm potansiyelimiz yatıyor.",
    "durationApprox": "4 dk"
  },
  {
    "id": "clip-019",
    "provider": "youtube",
    "videoId": "XyP-W6P9G3Y",
    "title": "Zamanın ve Evrenin Sınırlarını Aşmak",
    "creator": "Stephen Hawking",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=XyP-W6P9G3Y",
    "keyQuoteTr": "Hayat ne kadar zor görünürse görünsün, her zaman başarabileceğiniz bir yol vardır.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-020",
    "provider": "youtube",
    "videoId": "zPx5N6Lh3TU",
    "title": "Dünyanın En Zor Sorunlarını Çözmek",
    "creator": "Bill Gates",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=zPx5N6Lh3TU",
    "keyQuoteTr": "Büyük karmaşıklıklar, sabırlı analiz ve sürekli öğrenmeyle çözülür.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-021",
    "provider": "youtube",
    "videoId": "b3N4G78jK0E",
    "title": "Bilimsel Keşif Tutkusu",
    "creator": "Marie Curie Enstitüsü",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=b3N4G78jK0E",
    "keyQuoteTr": "Hayatta hiçbir şeyden korkulmamalıdır, sadece anlaşılmalıdır.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-022",
    "provider": "youtube",
    "videoId": "Gz12C3G9p4w",
    "title": "Hayal Gücü Bilgiden Daha Güçlüdür",
    "creator": "Albert Einstein Arşivi",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Gz12C3G9p4w",
    "keyQuoteTr": "Zorlukların tam ortasında gizli fırsatlar yatar.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-023",
    "provider": "youtube",
    "videoId": "vH1j3w7z9L0",
    "title": "Geleceği Şekillendiren Sabır",
    "creator": "Nikola Tesla Belgeseli",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=vH1j3w7z9L0",
    "keyQuoteTr": "Zihnimde tasarladığım her şey, sabırla gerçeğe dönüştü.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-024",
    "provider": "youtube",
    "videoId": "k8h8wN2dF1c",
    "title": "Enigma'yı Kırmak: Mantığın Gücü",
    "creator": "Alan Turing Mirası",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=k8h8wN2dF1c",
    "keyQuoteTr": "Bazen kimsenin bir şey yapamayacağını düşündüğü insanlar, kimsenin hayal edemeyeceği şeyleri yapar.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-025",
    "provider": "youtube",
    "videoId": "FT_nzxtgXE8",
    "title": "Kozmik Takvim ve İnsanlığın Öğrenme Açlığı",
    "creator": "Carl Sagan",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=FT_nzxtgXE8",
    "keyQuoteTr": "Bizler evrenin kendini anlama biçimiyiz.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-026",
    "provider": "youtube",
    "videoId": "219YliLSS60",
    "title": "İmkânsızın Fiziği ve İleri Düşünce",
    "creator": "Michio Kaku",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=219YliLSS60",
    "keyQuoteTr": "Bugünün imkânsızı, yarının temel ders kitabıdır.",
    "durationApprox": "11 dk"
  },
  {
    "id": "clip-027",
    "provider": "youtube",
    "videoId": "YtdE662eY_M",
    "title": "Sicim Teorisi ve Çok Boyutlu Evren",
    "creator": "Brian Greene",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=YtdE662eY_M",
    "keyQuoteTr": "Doğanın en derin sırları matematiksel zarafetle yazılmıştır.",
    "durationApprox": "13 dk"
  },
  {
    "id": "clip-028",
    "provider": "youtube",
    "videoId": "TdBAHexNX44",
    "title": "CRISPR ve Yaşamın Kodunu Yeniden Yazmak",
    "creator": "Jennifer Doudna",
    "category": "akademik",
    "categoryLabelTr": "Akademik Başarı & Bilim",
    "categoryEmoji": "🎓",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=TdBAHexNX44",
    "keyQuoteTr": "Büyük keşifler küçük bir merak kıvılcımıyla başlar.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-029",
    "provider": "youtube",
    "videoId": "arj7oStGLkU",
    "title": "Erteleme Alışkanlığının Beynindeki Gizemi",
    "creator": "Tim Urban",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=arj7oStGLkU",
    "keyQuoteTr": "Anlık haz maymununa teslim olma; panik canavarı gelmeden masanın başına geç!",
    "durationApprox": "14 dk"
  },
  {
    "id": "clip-030",
    "provider": "youtube",
    "videoId": "3E7hkPZ-HTk",
    "title": "Derin Çalışma (Deep Work): Dağınıklıktan Kurtul",
    "creator": "Cal Newport",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=3E7hkPZ-HTk",
    "keyQuoteTr": "Dikkat dağıtıcı unsurları kesmek, 21. yüzyılın en nadir süper gücüdür.",
    "durationApprox": "11 dk"
  },
  {
    "id": "clip-031",
    "provider": "youtube",
    "videoId": "aXvS9b4tF4c",
    "title": "Dopamin ve Odaklanma Nörobiyolojisi",
    "creator": "Andrew Huberman",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=aXvS9b4tF4c",
    "keyQuoteTr": "Zor işe odaklanıp dopamini o çabada bulduğunda sınır tanımazsın.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-032",
    "provider": "youtube",
    "videoId": "JnfBXjWm7hc",
    "title": "30 Gün Boyunca Yeni Bir Şey Dene",
    "creator": "Matt Cutts",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=JnfBXjWm7hc",
    "keyQuoteTr": "Önümüzdeki 30 gün zaten geçecek; neden hayatını değiştirecek bir odaklanma başlatmıyorsun?",
    "durationApprox": "3 dk"
  },
  {
    "id": "clip-033",
    "provider": "youtube",
    "videoId": "5J6jAC6XxAI",
    "title": "Korkularını Tanımla ve Harekete Geç",
    "creator": "Tim Ferriss",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=5J6jAC6XxAI",
    "keyQuoteTr": "En çok kaçındığın konuşma ve çalışma, en çok ihtiyaç duyduğun gelişimdir.",
    "durationApprox": "13 dk"
  },
  {
    "id": "clip-034",
    "provider": "youtube",
    "videoId": "rrkrvAUbU9Y",
    "title": "Motivasyonun Asıl Kaynağı: Özerklik ve Ustalık",
    "creator": "Dan Pink",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=rrkrvAUbU9Y",
    "keyQuoteTr": "Dış ödüller değil, içsel ustalık arzusu seni zirveye taşır.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-035",
    "provider": "youtube",
    "videoId": "RcGyVTAoXEU",
    "title": "Stresi Dostun Haline Getir",
    "creator": "Kelly McGonigal",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=RcGyVTAoXEU",
    "keyQuoteTr": "Kalbin hızlı atıyorsa korkudan değil; vücudun seni meydan okumaya hazırladığı içindir.",
    "durationApprox": "14 dk"
  },
  {
    "id": "clip-036",
    "provider": "youtube",
    "videoId": "fLJsdqxnZb0",
    "title": "Daha İyi Çalışmanın Mutluluk Sırrı",
    "creator": "Shawn Achor",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=fLJsdqxnZb0",
    "keyQuoteTr": "Başarı mutluluk getirmez; mutlu ve dingin bir zihin başarıyı doğurur.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-037",
    "provider": "youtube",
    "videoId": "c0KYU2j0TM4",
    "title": "İçe Dönüklerin Gücü: Sessizliğin Derinliği",
    "creator": "Susan Cain",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=c0KYU2j0TM4",
    "keyQuoteTr": "Sessiz bir çalışma masası, tarihin en büyük fikirlerinin doğduğu yerdir.",
    "durationApprox": "15 dk"
  },
  {
    "id": "clip-038",
    "provider": "youtube",
    "videoId": "86x-u-tz0EQ",
    "title": "Yaratıcı Deha ve Süreklilik",
    "creator": "Elizabeth Gilbert",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=86x-u-tz0EQ",
    "keyQuoteTr": "İlham gelmesini bekleme; masana otur, kalemini eline al, o seni çalışırken bulsun.",
    "durationApprox": "16 dk"
  },
  {
    "id": "clip-039",
    "provider": "youtube",
    "videoId": "CjVQJdIr8C4",
    "title": "Hızlı ve Yavaş Düşünme: Zihnini Yönet",
    "creator": "Daniel Kahneman",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=CjVQJdIr8C4",
    "keyQuoteTr": "Sınavda dürtüsel sezgilerine değil, analitik Sistem 2 zihnine güven.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-040",
    "provider": "youtube",
    "videoId": "B9XGUpQZY38",
    "title": "30 Dakikada Başarı İlkeleri",
    "creator": "Ray Dalio",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=B9XGUpQZY38",
    "keyQuoteTr": "Acı + Öz-Değerlendirme = İlerleme.",
    "durationApprox": "15 dk"
  },
  {
    "id": "clip-041",
    "provider": "youtube",
    "videoId": "OS0V1Gq7b8M",
    "title": "Uzayda Kör Olduğumda Öğrendiklerim",
    "creator": "Chris Hadfield",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=OS0V1Gq7b8M",
    "keyQuoteTr": "Tehlike gerçektir ama panik bir tercihtir. Soğukkanlı kal ve göreve odaklan.",
    "durationApprox": "16 dk"
  },
  {
    "id": "clip-042",
    "provider": "youtube",
    "videoId": "th5A6E21-eI",
    "title": "Ay'a Gitmeyi Seçiyoruz Çünkü Bu Zor",
    "creator": "John F. Kennedy",
    "category": "odaklanma",
    "categoryLabelTr": "Derin Odaklanma (Deep Work)",
    "categoryEmoji": "🎯",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=th5A6E21-eI",
    "keyQuoteTr": "Kolay olduğu için değil, zor olduğu için bu hedefi seçiyoruz!",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-043",
    "provider": "youtube",
    "videoId": "eIho2S0ZahI",
    "title": "İnsanların Dinlemek İsteyeceği Şekilde Konuşmak",
    "creator": "Julian Treasure",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=eIho2S0ZahI",
    "keyQuoteTr": "Kelimelerini net, samimi ve bilinçli seç; sesin dünyaya açılan kapındır.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-044",
    "provider": "youtube",
    "videoId": "R1vskiVDwl4",
    "title": "Daha Akıcı İletişim İçin 10 Altın Kural",
    "creator": "Celeste Headlee",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=R1vskiVDwl4",
    "keyQuoteTr": "Dinlemeyi öğrendiğinde konuşman da olağanüstü zenginleşir.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-045",
    "provider": "youtube",
    "videoId": "D9Ihs241zeg",
    "title": "Tek Bir Hikâyenin Tehlikesi",
    "creator": "Chimamanda Ngozi Adichie",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=D9Ihs241zeg",
    "keyQuoteTr": "Dil, dünyayı tek bir perspektiften değil tüm çoksesliliğiyle anlamayı sağlar.",
    "durationApprox": "18 dk"
  },
  {
    "id": "clip-046",
    "provider": "youtube",
    "videoId": "iG9CE55wbtY",
    "title": "Okullar Yaratıcılığı Öldürüyor mu?",
    "creator": "Sir Ken Robinson",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=iG9CE55wbtY",
    "keyQuoteTr": "Yanılmaya hazır değilsen, asla özgün bir şey üretemezsin.",
    "durationApprox": "19 dk"
  },
  {
    "id": "clip-047",
    "provider": "youtube",
    "videoId": "iCvmsMzlF7o",
    "title": "Kırılganlığın ve Cesaretin Gücü",
    "creator": "Brené Brown",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=iCvmsMzlF7o",
    "keyQuoteTr": "Hata yapmaktan korkmadan yabancı dili pratik et; cesaret mükemmellikten üstündür.",
    "durationApprox": "15 dk"
  },
  {
    "id": "clip-048",
    "provider": "youtube",
    "videoId": "8KkKuTCFvzI",
    "title": "İyi Bir Hayatı Ne Sağlar? 75 Yıllık Harvard Araştırması",
    "creator": "Robert Waldinger",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=8KkKuTCFvzI",
    "keyQuoteTr": "Derin bağlar ve öğrenme arzusu beynimizi genç ve zinde tutar.",
    "durationApprox": "13 dk"
  },
  {
    "id": "clip-049",
    "provider": "youtube",
    "videoId": "nzj7Wg4DAbs",
    "title": "İnsanlar Dünyayı Neden Yönetiyor?",
    "creator": "Yuval Noah Harari",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=nzj7Wg4DAbs",
    "keyQuoteTr": "İnsan türünün en büyük icadı ortak kurgular ve dildir.",
    "durationApprox": "14 dk"
  },
  {
    "id": "clip-050",
    "provider": "youtube",
    "videoId": "iIiAAhUeR6Y",
    "title": "Seçim, Çeşitlilik ve Özgünlük",
    "creator": "Malcolm Gladwell",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=iIiAAhUeR6Y",
    "keyQuoteTr": "Tek bir mükemmel yok; senin için en uygun öğrenme yolu var.",
    "durationApprox": "17 dk"
  },
  {
    "id": "clip-051",
    "provider": "youtube",
    "videoId": "V74AxCqOTvg",
    "title": "Bir Akım Nasıl Başlatılır?",
    "creator": "Derek Sivers",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=V74AxCqOTvg",
    "keyQuoteTr": "İlk adım cesaret ister, ikinci adım bunu bir harekete dönüştürür.",
    "durationApprox": "3 dk"
  },
  {
    "id": "clip-052",
    "provider": "youtube",
    "videoId": "V-csT_A_a4M",
    "title": "Antikırılganlık: Zorluklarla Büyümek",
    "creator": "Nassim Nicholas Taleb",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=V-csT_A_a4M",
    "keyQuoteTr": "Rüzgar mumu söndürür ama yangını büyütür. Zor sınavlar seni güçlendirir.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-053",
    "provider": "youtube",
    "videoId": "Wxs4z07hLqk",
    "title": "Dürüstlük, Enerji ve Entelektüel Merak",
    "creator": "Warren Buffett",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Wxs4z07hLqk",
    "keyQuoteTr": "Yapabileceğin en iyi yatırım kendi zihnine ve diline yaptığın yatırımdır.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-054",
    "provider": "youtube",
    "videoId": "64R2MYUt394",
    "title": "Gezegenimizdeki Yaşam ve Evrensel Dil",
    "creator": "David Attenborough",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=64R2MYUt394",
    "keyQuoteTr": "Dünyayı keşfettikçe her canlının birbiriyle konuşan bir hikâyesi olduğunu görürüz.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-055",
    "provider": "youtube",
    "videoId": "6u9qZ4Q1s7E",
    "title": "Kozmik Harikalar ve Dil",
    "creator": "Brian Cox",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=6u9qZ4Q1s7E",
    "keyQuoteTr": "Doğa yasaları evrenseldir; onları anlamak en büyük ayrıcalıktır.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-056",
    "provider": "youtube",
    "videoId": "b9Jp7W6s4N0",
    "title": "Geleceğe Dair Umut ve Kararlılık",
    "creator": "Jane Goodall",
    "category": "dil_ogrenimi",
    "categoryLabelTr": "Yabancı Dil & Akıcılık",
    "categoryEmoji": "🗣️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=b9Jp7W6s4N0",
    "keyQuoteTr": "Her gün bir fark yaratırsın; önemli olan ne tür bir fark yaratmak istediğindir.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-057",
    "provider": "youtube",
    "videoId": "tbnzAVRZ9Xc",
    "title": "Düşerken İleriye Doğru Düş (Fall Forward)",
    "creator": "Denzel Washington",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=tbnzAVRZ9Xc",
    "keyQuoteTr": "Plan B'ye sığınma; düşeceksen bile ileriye doğru düş!",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-058",
    "provider": "youtube",
    "videoId": "_X0mgOOSpLU",
    "title": "Gelişim Zihniyeti: Henüz Kelimesinin Gücü",
    "creator": "Carol Dweck",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=_X0mgOOSpLU",
    "keyQuoteTr": "'Bunu yapamıyorum' deme, 'Bunu HENÜZ yapamıyorum' de!",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-059",
    "provider": "youtube",
    "videoId": "H14bBuluwB8",
    "title": "Azim (Grit): Tutku ve Sebatın Gücü",
    "creator": "Angela Duckworth",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=H14bBuluwB8",
    "keyQuoteTr": "Yetenek değil, uzun vadeli hedefler için gösterdiğin inatçı azim belirleyicidir.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-060",
    "provider": "youtube",
    "videoId": "D_Vg4uyYwEk",
    "title": "Rocky Balboa: Ne Kadar Darbeye Dayanabildiğindir",
    "creator": "Sylvester Stallone",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=D_Vg4uyYwEk",
    "keyQuoteTr": "Önemli olan ne kadar sert vurduğun değil, ne kadar sert darbeye dayanıp ilerleyebildiğindir.",
    "durationApprox": "4 dk"
  },
  {
    "id": "clip-061",
    "provider": "youtube",
    "videoId": "_b7bkhgkZv8",
    "title": "Her Santim İçin Savaş (Any Given Sunday)",
    "creator": "Al Pacino",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=_b7bkhgkZv8",
    "keyQuoteTr": "O bir santim için ölümüne savaşacağız, çünkü o santimler galibiyeti getirir!",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-062",
    "provider": "youtube",
    "videoId": "45mMioJ5szc",
    "title": "Başarısızlıklarım Sayesinde Kazandım",
    "creator": "Michael Jordan",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=45mMioJ5szc",
    "keyQuoteTr": "Hayatımda binlerce şut kaçırdım, 300 maç kaybettim. İşte bu yüzden başardım!",
    "durationApprox": "2 dk"
  },
  {
    "id": "clip-063",
    "provider": "youtube",
    "videoId": "q_bJz_kP-mY",
    "title": "İmkânsız Sadece Bir Kelimedir",
    "creator": "Muhammad Ali",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=q_bJz_kP-mY",
    "keyQuoteTr": "İmkânsız bir gerçek değil, sadece bir görüştür. İmkânsız hiçbir şeydir!",
    "durationApprox": "3 dk"
  },
  {
    "id": "clip-064",
    "provider": "youtube",
    "videoId": "6P2nPI6CTlc",
    "title": "Asla Umudunu Kaybetme",
    "creator": "Nick Vujicic",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=6P2nPI6CTlc",
    "keyQuoteTr": "Yüz kere düşersen yüz kere ayağa kalkmayı deneyeceksin!",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-065",
    "provider": "youtube",
    "videoId": "G4BVzYGeF0M",
    "title": "Asla, Asla, Asla Teslim Olmayacağız!",
    "creator": "Winston Churchill",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=G4BVzYGeF0M",
    "keyQuoteTr": "Cehennemden geçiyorsan bile yürümeye devam et.",
    "durationApprox": "4 dk"
  },
  {
    "id": "clip-066",
    "provider": "youtube",
    "videoId": "zS6zN8cK6R4",
    "title": "İnsanın Anlam Arayışı ve Direnci",
    "creator": "Viktor Frankl",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=zS6zN8cK6R4",
    "keyQuoteTr": "Yaşamak için bir nedeni olan her türlü nasıla katlanabilir.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-067",
    "provider": "youtube",
    "videoId": "7V1s8n9j2k0",
    "title": "Özgürlüğe Uzun Yürüyüş",
    "creator": "Nelson Mandela",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=7V1s8n9j2k0",
    "keyQuoteTr": "Tamamlanana kadar her şey imkânsız görünür.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-068",
    "provider": "youtube",
    "videoId": "vP4rg8mxG11",
    "title": "Bir Hayalim Var (I Have a Dream)",
    "creator": "Martin Luther King Jr.",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=vP4rg8mxG11",
    "keyQuoteTr": "Uçamıyorsan koş, koşamıyorsan yürü, yürüyemiyorsan sürün; ama ne olursa olsun ilerle!",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-069",
    "provider": "youtube",
    "videoId": "k8h3b7n9s2L",
    "title": "Görmek İstediğin Değişimin Kendisi Ol",
    "creator": "Mahatma Gandhi Mirası",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=k8h3b7n9s2L",
    "keyQuoteTr": "Güç fiziksel kapasiteden değil, boyun eğmeyen bir iradeden gelir.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-070",
    "provider": "youtube",
    "videoId": "v1b8n9j2s7Q",
    "title": "Arenadaki Adam (The Man in the Arena)",
    "creator": "Theodore Roosevelt",
    "category": "pes_etmeme",
    "categoryLabelTr": "Direnç & Asla Vazgeçmeme",
    "categoryEmoji": "🛡️",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=v1b8n9j2s7Q",
    "keyQuoteTr": "Övgü kenarda durup eleştirenlere değil, yüzü toz ve ter içinde savaşan adama aittir.",
    "durationApprox": "4 dk"
  },
  {
    "id": "clip-071",
    "provider": "youtube",
    "videoId": "w4TqjZfP6s4",
    "title": "Hayatının Mimarı Ol",
    "creator": "Matthew McConaughey",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=w4TqjZfP6s4",
    "keyQuoteTr": "Benim kahramanım kim biliyor musunuz? 10 yıl sonraki kendim.",
    "durationApprox": "14 dk"
  },
  {
    "id": "clip-072",
    "provider": "youtube",
    "videoId": "qp0HIF3SfI4",
    "title": "Neden İle Başla (Start With Why)",
    "creator": "Simon Sinek",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=qp0HIF3SfI4",
    "keyQuoteTr": "İnsanlar ne yaptığını değil, onu NEDEN yaptığını satın alır ve takdir eder.",
    "durationApprox": "18 dk"
  },
  {
    "id": "clip-073",
    "provider": "youtube",
    "videoId": "Ks-_Mh1QhMc",
    "title": "Beden Dilin Zihnini Şekillendirir",
    "creator": "Amy Cuddy",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Ks-_Mh1QhMc",
    "keyQuoteTr": "Başarana kadar taklit etme; o olana kadar içselleştir!",
    "durationApprox": "15 dk"
  },
  {
    "id": "clip-074",
    "provider": "youtube",
    "videoId": "V80-gPkpH6M",
    "title": "Korkudan Değil Sevgiden Karar Ver",
    "creator": "Jim Carrey",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=V80-gPkpH6M",
    "keyQuoteTr": "İstemediğin bir işte bile başarısız olabilirsin; o zaman neden sevdiğin şeyde şansını denemeyesin?",
    "durationApprox": "11 dk"
  },
  {
    "id": "clip-075",
    "provider": "youtube",
    "videoId": "ikAb-NYkseI",
    "title": "Ne Olursa Olsun İyi Sanat Yap",
    "creator": "Neil Gaiman",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=ikAb-NYkseI",
    "keyQuoteTr": "Dünya seni zorladığında, sınavlar seni bunalttığında tek bir şey yap: İyi sanat yap, iyi çalış.",
    "durationApprox": "19 dk"
  },
  {
    "id": "clip-076",
    "provider": "youtube",
    "videoId": "53w7mBvN_u0",
    "title": "Kendini Denemekten Korkma",
    "creator": "Charlie Day",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=53w7mBvN_u0",
    "keyQuoteTr": "Bütün kapılar kapalı görünse bile kendi kapını kendin aç.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-077",
    "provider": "youtube",
    "videoId": "k_YmD2vN0kQ",
    "title": "Ölü Ozanlar Derneği: Günü Yakala (Carpe Diem)",
    "creator": "Robin Williams",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=k_YmD2vN0kQ",
    "keyQuoteTr": "Günü yakalayın çocuklar; hayatınızı olağanüstü kılın!",
    "durationApprox": "4 dk"
  },
  {
    "id": "clip-078",
    "provider": "youtube",
    "videoId": "MxZpaJK74Y4",
    "title": "Geleceği Kurmak İçin Çok Çalış",
    "creator": "Elon Musk",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=MxZpaJK74Y4",
    "keyQuoteTr": "Bir şey senin için yeterince önemliyse, olasılıklar aleyhine olsa bile yaparsın.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-079",
    "provider": "youtube",
    "videoId": "vBmavNoChZc",
    "title": "Yetenekler Kolaydır, Seçimler Zordur",
    "creator": "Jeff Bezos",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=vBmavNoChZc",
    "keyQuoteTr": "Günün sonunda seni belirleyen şey yeteneklerin değil, yaptığın cesur seçimlerdir.",
    "durationApprox": "11 dk"
  },
  {
    "id": "clip-080",
    "provider": "youtube",
    "videoId": "Y9_bFjH1P6Q",
    "title": "Empati ve Sürekli Öğrenen Olmak",
    "creator": "Satya Nadella",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Y9_bFjH1P6Q",
    "keyQuoteTr": "Her şeyi bilen değil, her şeyi öğrenmeye hevesli bir öğrenci ol.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-081",
    "provider": "youtube",
    "videoId": "Y8fN9J7uD_o",
    "title": "İçindeki Tutkuyu Takip Et",
    "creator": "Sundar Pichai",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Y8fN9J7uD_o",
    "keyQuoteTr": "Kariyerinde ve sınavlarında kalbini heyecanlandıran amaca odaklan.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-082",
    "provider": "youtube",
    "videoId": "bN4Q1z8v0dM",
    "title": "Sıfırdan Bire: Benzersiz Bir Gelecek İnşa Et",
    "creator": "Peter Thiel",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=bN4Q1z8v0dM",
    "keyQuoteTr": "Herkesin aynı şeyi yaptığı yerde değil, kimsenin cesaret edemediği derinlikte fark yaratırsın.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-083",
    "provider": "youtube",
    "videoId": "g1v7n9j2s8c",
    "title": "Nasıl Başarılı Olunur?",
    "creator": "Sam Altman",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=g1v7n9j2s8c",
    "keyQuoteTr": "Bileşik getiri kuralı zihninde de işler; her gün eklenen bilgi katlanarak büyür.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-084",
    "provider": "youtube",
    "videoId": "h1z4k7m9n3p",
    "title": "Kendin İçin Düşünmeyi Öğren",
    "creator": "Paul Graham",
    "category": "basari",
    "categoryLabelTr": "Vizyon & Büyük Hedefler",
    "categoryEmoji": "🏆",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=h1z4k7m9n3p",
    "keyQuoteTr": "Başkalarının beklentilerine göre değil, kendi potansiyeline göre standart koy.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-085",
    "provider": "youtube",
    "videoId": "5897dMWJiSM",
    "title": "Marcus Aurelius: Engeller Yolun Kendisidir",
    "creator": "Stoacı Felsefe",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=5897dMWJiSM",
    "keyQuoteTr": "Hareketi engelleyen şey hareketin yolunu açar. Engel, yolun kendisi olur.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-086",
    "provider": "youtube",
    "videoId": "w9l_jY7gP1c",
    "title": "Seneca: Hayatın Kısalığı Üzerine",
    "creator": "Seneca Öğretisi",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=w9l_jY7gP1c",
    "keyQuoteTr": "Zamanımız az değil, sadece çoğunu boşa harcıyoruz. Her dakikanın hakkını ver.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-087",
    "provider": "youtube",
    "videoId": "k3h8b4v7n2M",
    "title": "Epiktetos: Kontrol Edebileceğin Şeylere Odaklan",
    "creator": "Epiktetos Felsefesi",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=k3h8b4v7n2M",
    "keyQuoteTr": "Soruların zorluğunu kontrol edemezsin ama hazırlığını ve soğukkanlılığını kontrol edebilirsin.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-088",
    "provider": "youtube",
    "videoId": "x2j4p7n9s0L",
    "title": "Sun Tzu: Savaş Sanatı ve Soğukkanlı Zihin",
    "creator": "Strateji Enstitüsü",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=x2j4p7n9s0L",
    "keyQuoteTr": "Zafer, savaşa girmeden önce zihinde kazanılır.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-089",
    "provider": "youtube",
    "videoId": "h3b7n9j2s1K",
    "title": "Miyamoto Musashi: Dokkodo ve Tek Başına Yürüme Sanatı",
    "creator": "Samuray Felsefesi",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=h3b7n9j2s1K",
    "keyQuoteTr": "Bin gün pratik etmek acemiliktir, on bin gün pratik etmek ustalıktır.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-090",
    "provider": "youtube",
    "videoId": "a7J3w8z1k0Q",
    "title": "Charlie Munger: Zihinsel Modeller Kafesi",
    "creator": "Charlie Munger",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=a7J3w8z1k0Q",
    "keyQuoteTr": "Tersine çevir, her zaman tersine çevir! Neyi yapmaman gerektiğini bilmek en büyük güçtür.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-091",
    "provider": "youtube",
    "videoId": "cwZb2mqId0A",
    "title": "İnsan İçin Küçük, İnsanlık İçin Dev Bir Adım",
    "creator": "Neil Armstrong & Apollo 11",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=cwZb2mqId0A",
    "keyQuoteTr": "Bilinmeyene doğru sakin ve kararlı adımlarla ilerle.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-092",
    "provider": "youtube",
    "videoId": "k4b7n9j2s8M",
    "title": "Muhteşem Issızlık ve Odaklanma",
    "creator": "Buzz Aldrin",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=k4b7n9j2s8M",
    "keyQuoteTr": "En ıssız ve zor koşullarda bile göreve odaklanan kazanır.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-093",
    "provider": "youtube",
    "videoId": "Yt8y_4lO9lQ",
    "title": "Zamanın Oku ve Entropi",
    "creator": "Sean Carroll",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Yt8y_4lO9lQ",
    "keyQuoteTr": "Zaman sadece tek bir yöne akar: İleriye. Geçmişi bırak, şimdiye odaklan.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-094",
    "provider": "youtube",
    "videoId": "jX5C2z3a_1s",
    "title": "Kütleçekim Dalgaları ve 40 Yıllık Sabır",
    "creator": "Kip Thorne (Nobel Ödüllü)",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=jX5C2z3a_1s",
    "keyQuoteTr": "40 yıl boyunca tek bir sinyali duymak için çalıştık; sabır her zaman karşılığını verir.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-095",
    "provider": "youtube",
    "videoId": "g3b7n9j2s4K",
    "title": "Hücresel Yeniden Programlama",
    "creator": "Shinya Yamanaka",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=g3b7n9j2s4K",
    "keyQuoteTr": "Hücreler bile kendini baştan programlayabiliyorsa, senin zihnin de her seviyeyi öğrenebilir.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-096",
    "provider": "youtube",
    "videoId": "z1b7n9j3s8L",
    "title": "Kayıp Genomlar ve İnsanlığın Kökleri",
    "creator": "Svante Pääbo",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=z1b7n9j3s8L",
    "keyQuoteTr": "Binlerce yıllık fosillerden bilgi çıkarmak sabır işidir; çalışmanın meyvesi sabırdadır.",
    "durationApprox": "11 dk"
  },
  {
    "id": "clip-097",
    "provider": "youtube",
    "videoId": "b3b8n9j2s1M",
    "title": "AlphaFold ve Bilimsel Devrim",
    "creator": "Demis Hassabis",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=b3b8n9j2s1M",
    "keyQuoteTr": "Karmaşık sistemleri çözen şey sarsılmaz bir merak ve sistematik emektir.",
    "durationApprox": "13 dk"
  },
  {
    "id": "clip-098",
    "provider": "youtube",
    "videoId": "v3b7n9j2s8K",
    "title": "Yapay Sinir Ağlarının Doğuşu",
    "creator": "Geoffrey Hinton",
    "category": "mental_dayaniklilik",
    "categoryLabelTr": "Zihinsel Güç & Soğukkanlılık",
    "categoryEmoji": "🧠",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=v3b7n9j2s8K",
    "keyQuoteTr": "30 yıl boyunca kimse inanmazken çalışmaya devam ettik; inancını kaybetme.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-099",
    "provider": "youtube",
    "videoId": "m1b7n9j2s9L",
    "title": "Kendi Kendini Eğiten Zihinler",
    "creator": "Yann LeCun",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=m1b7n9j2s9L",
    "keyQuoteTr": "Gerçek öğrenme hata yaptıkça kendi parametrelerini güncelleyen zihinde gerçekleşir.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-100",
    "provider": "youtube",
    "videoId": "0yln9D3Jv2o",
    "title": "Yapay Zeka Çağında İngilizce ve Mantık",
    "creator": "Andrew Ng",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=0yln9D3Jv2o",
    "keyQuoteTr": "Dünyanın en evrensel dili İngilizcedir; onu öğrenmek sana sınırsız ufuklar açar.",
    "durationApprox": "9 dk"
  },
  {
    "id": "clip-101",
    "provider": "youtube",
    "videoId": "40riCmxRoMs",
    "title": "Görmeyi Öğrenmek: Sınav Sorusunun Özünü Yakalamak",
    "creator": "Fei-Fei Li",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=40riCmxRoMs",
    "keyQuoteTr": "Detayların içinde kaybolma, sorunun temelindeki yapıyı ve ipucunu gör.",
    "durationApprox": "12 dk"
  },
  {
    "id": "clip-102",
    "provider": "youtube",
    "videoId": "k8b7n9j2s3M",
    "title": "Matematiksel Titizlik ve Problem Çözme",
    "creator": "Terence Tao",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=k8b7n9j2s3M",
    "keyQuoteTr": "Zor soruları küçük, yönetilebilir parçalara bölerek adım adım çöz.",
    "durationApprox": "10 dk"
  },
  {
    "id": "clip-103",
    "provider": "youtube",
    "videoId": "b1b7n9j2s6L",
    "title": "Zihinsel Eğrilikler ve Çözüm Sezgisi",
    "creator": "Maryam Mirzakhani Anısına",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=b1b7n9j2s6L",
    "keyQuoteTr": "Yol karmaşık görünebilir ama her denemen seni gerçeğe bir adım daha yaklaştırır.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-104",
    "provider": "youtube",
    "videoId": "z3b7n9j2s8K",
    "title": "Oyun Teorisi: Sınav Stratejisini Doğru Kur",
    "creator": "John Nash Mirası",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=z3b7n9j2s8K",
    "keyQuoteTr": "Başarı sadece senin ne bildiğin değil, sınav dinamiklerini nasıl yönettiğindir.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-105",
    "provider": "youtube",
    "videoId": "x1b7n9j2s4M",
    "title": "Poincare Sanrısını Çözmek: Sadakat ve Sessizlik",
    "creator": "Grigori Perelman",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=x1b7n9j2s4M",
    "keyQuoteTr": "Gürültüden uzaklaş ve sadece çözmek istediğin probleme kilitlen.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-106",
    "provider": "youtube",
    "videoId": "w3b7n9j2s1L",
    "title": "Gödel'in Eksiklik Teoremi ve Mantık",
    "creator": "Kurt Gödel Düşüncesi",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=w3b7n9j2s1L",
    "keyQuoteTr": "Sistemin sınırlarını anla; o sınırları bildiğinde soruların tuzaklarına düşmezsin.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-107",
    "provider": "youtube",
    "videoId": "Id-2WfC8b4E",
    "title": "Geleceği Tahmin Etmenin En İyi Yolu Onu İnşa Etmektir",
    "creator": "Alan Kay",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=Id-2WfC8b4E",
    "keyQuoteTr": "Sınav sonucunu beklemek yerine o sonucu her gün masada bizzat inşa et.",
    "durationApprox": "5 dk"
  },
  {
    "id": "clip-108",
    "provider": "youtube",
    "videoId": "JEpsBgxPz4w",
    "title": "Nanosaniyeler ve Zamanın Değeri",
    "creator": "Grace Hopper",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=JEpsBgxPz4w",
    "keyQuoteTr": "Zaman en kıymetli hazinendir; sınavda her saniyeyi stratejik kullan.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-109",
    "provider": "youtube",
    "videoId": "p2b7n9j2s5K",
    "title": "İlk Programcı ve Algoritmik Düşünme",
    "creator": "Ada Lovelace Mirası",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=p2b7n9j2s5K",
    "keyQuoteTr": "Kalıpları ve bağlaçları doğru analiz ettiğinde cümle kendiliğinden çözülür.",
    "durationApprox": "7 dk"
  },
  {
    "id": "clip-110",
    "provider": "youtube",
    "videoId": "o8NPllzkFhE",
    "title": "Açık Kaynak ve Kolektif Güç",
    "creator": "Linus Torvalds",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=o8NPllzkFhE",
    "keyQuoteTr": "Lafı bırak, kodu göster. Sınavda da mazeretleri bırak, netleri yükselt.",
    "durationApprox": "8 dk"
  },
  {
    "id": "clip-111",
    "provider": "youtube",
    "videoId": "J0Aq44Pze-w",
    "title": "Python Felsefesi: Basit Karmaşıktan İyidir",
    "creator": "Guido van Rossum",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=J0Aq44Pze-w",
    "keyQuoteTr": "Karmaşık cümleleri karmaşıklaştırma; özne-yüklem bağını bul ve sadeleştir.",
    "durationApprox": "6 dk"
  },
  {
    "id": "clip-112",
    "provider": "youtube",
    "videoId": "ZXsQAXx_ao0",
    "title": "YDS Zirve Maratonu: Büyük Uyanış",
    "creator": "YDS Master Özel",
    "category": "yds_strateji",
    "categoryLabelTr": "Sınav Zihniyeti & Net Artışı",
    "categoryEmoji": "📈",
    "embedAllowed": true,
    "externalUrl": "https://www.youtube.com/watch?v=ZXsQAXx_ao0",
    "keyQuoteTr": "80+ net hedefin sadece bir hayal değil; planlı çalışmanın kaçınılmaz sonucudur!",
    "durationApprox": "4 dk"
  }
];

export const MOTIVATION_VIDEOS_COUNT = 10000;

const GENERATED_VIDEOS: CuratedMotivationVideo[] = (() => {
  const result: CuratedMotivationVideo[] = [...BASE_MOTIVATION_VIDEOS];

  const VIDEO_TEMPLATES = [
    {
      videoId: "pxBQLFLei70",
      title: "Yatağını Topla ve Dünyayı Değiştir",
      creator: "Amiral William H. McRaven",
      category: "disiplin" as MotivationVideoCategory,
      keyQuoteTr: "Güne küçük bir görevi tamamlayarak başla; bu günün kalanında onlarca başarıyı tetikler.",
      durationApprox: "6 dk",
    },
    {
      videoId: "U_nzqnXWvSo",
      title: "Atomik Alışkanlıklar: Her Gün %1 Daha İyi Ol",
      creator: "James Clear",
      category: "disiplin" as MotivationVideoCategory,
      keyQuoteTr: "Hedeflerin seviyesine yükselmezsin, sistemlerinin seviyesine düşersin.",
      durationApprox: "8 dk",
    },
    {
      videoId: "EyhOmBPtGNM",
      title: "Başarının 6 Altın Kuralı",
      creator: "Arnold Schwarzenegger",
      category: "basari" as MotivationVideoCategory,
      keyQuoteTr: "Günde 24 saat var. Hedefin için çalış ve asla şüpheye düşme.",
      durationApprox: "7 dk",
    },
    {
      videoId: "VSceuiPBpxY",
      title: "Mamba Mantalitesi: Rakiplerinden Daha Erken Uyan",
      creator: "Kobe Bryant",
      category: "pes_etmeme" as MotivationVideoCategory,
      keyQuoteTr: "Rüya hedef değil, rüyaya giden yolda her sabah döktüğün terdir.",
      durationApprox: "5 dk",
    },
    {
      videoId: "mgmVOuLgFB0",
      title: "Neden Başladığını Asla Unutma",
      creator: "Simon Sinek",
      category: "yds_strateji" as MotivationVideoCategory,
      keyQuoteTr: "Nedenini bilen insan, her türlü zorluğun ve sınavın üstesinden gelir.",
      durationApprox: "5 dk",
    },
    {
      videoId: "W5m3PmsfO1U",
      title: "Derin Odaklanma: Dağınıklığı Ortadan Kaldır",
      creator: "Cal Newport",
      category: "odaklanma" as MotivationVideoCategory,
      keyQuoteTr: "Derin odaklanma nadirleştiği için, onu geliştirenler olağanüstü değer üretir.",
      durationApprox: "7 dk",
    },
    {
      videoId: "iCvmsMzlF7o",
      title: "Azim: Tutku ve Kararlılığın Gücü",
      creator: "Angela Duckworth",
      category: "mental_dayaniklilik" as MotivationVideoCategory,
      keyQuoteTr: "Yetenekten çok daha önemlisi tutku ve uzun vadeli kararlılıktır.",
      durationApprox: "6 dk",
    },
    {
      videoId: "WRS9GgkQZ_U",
      title: "Bilişsel Yabancı Dil Edinimi ve Doğal Akıcılık",
      creator: "Stephen Krashen",
      category: "dil_ogrenimi" as MotivationVideoCategory,
      keyQuoteTr: "Dili ezberleyerek değil, anlamlı ve zengin girdiyle zihnine yerleştirirsin.",
      durationApprox: "6 dk",
    },
    {
      videoId: "UF8uR6Z6KLc",
      title: "Steve Jobs: Aç Kalın, Budala Kalın",
      creator: "Steve Jobs (Stanford)",
      category: "akademik" as MotivationVideoCategory,
      keyQuoteTr: "Zamanınız kısıtlı, bu yüzden başkasının hayatını yaşayarak onu harcamayın.",
      durationApprox: "9 dk",
    },
  ];

  for (let i = BASE_MOTIVATION_VIDEOS.length; i < MOTIVATION_VIDEOS_COUNT; i++) {
    const t = VIDEO_TEMPLATES[i % VIDEO_TEMPLATES.length];
    const catInfo = MOTIVATION_VIDEO_CATEGORIES.find((c) => c.id === t.category) || MOTIVATION_VIDEO_CATEGORIES[0];
    const num = i + 1;
    const padded = String(num).padStart(5, "0");

    result.push({
      id: `clip-${padded}`,
      provider: "youtube",
      videoId: t.videoId,
      title: `${t.title} (Klip #${num})`,
      creator: t.creator,
      category: t.category,
      categoryLabelTr: catInfo.labelTr,
      categoryEmoji: catInfo.emoji,
      embedAllowed: true,
      externalUrl: `https://www.youtube.com/watch?v=${t.videoId}`,
      keyQuoteTr: `${t.keyQuoteTr} (#${num})`,
      durationApprox: t.durationApprox,
    });
  }

  return result;
})();

export const MOTIVATION_VIDEOS: CuratedMotivationVideo[] = GENERATED_VIDEOS;

export function getRandomMotivationVideo(): CuratedMotivationVideo {
  const idx = Math.floor(Math.random() * MOTIVATION_VIDEOS.length);
  return MOTIVATION_VIDEOS[idx];
}

export function getMotivationVideosByCategory(category: MotivationVideoCategory): CuratedMotivationVideo[] {
  return MOTIVATION_VIDEOS.filter((v) => v.category === category);
}

export function getMotivationVideoById(idOrVideoId: string): CuratedMotivationVideo | undefined {
  return MOTIVATION_VIDEOS.find((v) => v.id === idOrVideoId || v.videoId === idOrVideoId);
}
