// 2013-2026 YDS sınavlarında sık çıkan kelimeler — Türkçe anlamlarıyla.
// Frekans etiketi: "çok" = çok sık, "sık" = sık, "orta" = ara sıra.
export interface ArchiveWord {
  w: string;
  tr: string;
  f: "çok" | "sık" | "orta";
  type: string;
}

export const ARCHIVE_WORDS: ArchiveWord[] = [
  { w: "abandon", tr: "terk etmek, bırakmak", f: "çok", type: "fiil" },
  { w: "abundant", tr: "bol, çok fazla", f: "çok", type: "sıfat" },
  { w: "acquire", tr: "edinmek, elde etmek", f: "çok", type: "fiil" },
  { w: "advocate", tr: "savunmak; savunucu", f: "sık", type: "fiil/isim" },
  { w: "alleviate", tr: "hafifletmek, dindirmek", f: "sık", type: "fiil" },
  { w: "ambiguous", tr: "belirsiz, çift anlamlı", f: "çok", type: "sıfat" },
  { w: "anticipate", tr: "önceden sezmek, beklemek", f: "sık", type: "fiil" },
  { w: "apparent", tr: "açık, belli", f: "çok", type: "sıfat" },
  { w: "arbitrary", tr: "keyfî, gelişigüzel", f: "sık", type: "sıfat" },
  { w: "assess", tr: "değerlendirmek", f: "çok", type: "fiil" },
  { w: "attribute", tr: "atfetmek, yormak", f: "sık", type: "fiil" },
  { w: "coincide", tr: "çakışmak, denk gelmek", f: "sık", type: "fiil" },
  { w: "compel", tr: "zorlamak, mecbur etmek", f: "çok", type: "fiil" },
  { w: "comprehensive", tr: "kapsamlı", f: "çok", type: "sıfat" },
  { w: "conceal", tr: "gizlemek", f: "sık", type: "fiil" },
  { w: "consecutive", tr: "ardışık, peş peşe", f: "orta", type: "sıfat" },
  { w: "constitute", tr: "oluşturmak, teşkil etmek", f: "çok", type: "fiil" },
  { w: "contradict", tr: "çelişmek, ters düşmek", f: "sık", type: "fiil" },
  { w: "controversial", tr: "tartışmalı", f: "sık", type: "sıfat" },
  { w: "convey", tr: "iletmek, aktarmak", f: "çok", type: "fiil" },
  { w: "crucial", tr: "çok önemli, can alıcı", f: "çok", type: "sıfat" },
  { w: "deteriorate", tr: "kötüleşmek, bozulmak", f: "çok", type: "fiil" },
  { w: "diminish", tr: "azalmak, küçülmek", f: "çok", type: "fiil" },
  { w: "disclose", tr: "açıklamak, ifşa etmek", f: "sık", type: "fiil" },
  { w: "distinguish", tr: "ayırt etmek", f: "çok", type: "fiil" },
  { w: "eliminate", tr: "elemek, ortadan kaldırmak", f: "çok", type: "fiil" },
  { w: "emerge", tr: "ortaya çıkmak", f: "çok", type: "fiil" },
  { w: "enhance", tr: "geliştirmek, artırmak", f: "çok", type: "fiil" },
  { w: "exaggerate", tr: "abartmak", f: "sık", type: "fiil" },
  { w: "feasible", tr: "uygulanabilir", f: "çok", type: "sıfat" },
  { w: "fluctuate", tr: "dalgalanmak", f: "sık", type: "fiil" },
  { w: "fundamental", tr: "temel, esas", f: "çok", type: "sıfat" },
  { w: "genuine", tr: "gerçek, samimi", f: "sık", type: "sıfat" },
  { w: "implement", tr: "uygulamak, hayata geçirmek", f: "çok", type: "fiil" },
  { w: "inevitable", tr: "kaçınılmaz", f: "çok", type: "sıfat" },
  { w: "inherent", tr: "doğasında var olan", f: "sık", type: "sıfat" },
  { w: "inhibit", tr: "engellemek, frenlemek", f: "sık", type: "fiil" },
  { w: "justify", tr: "haklı göstermek", f: "sık", type: "fiil" },
  { w: "maintain", tr: "sürdürmek; ileri sürmek", f: "çok", type: "fiil" },
  { w: "neglect", tr: "ihmal etmek", f: "çok", type: "fiil" },
  { w: "notion", tr: "kavram, düşünce", f: "sık", type: "isim" },
  { w: "obsolete", tr: "kullanımdan kalkmış", f: "sık", type: "sıfat" },
  { w: "perceive", tr: "algılamak", f: "çok", type: "fiil" },
  { w: "persist", tr: "sebat etmek; sürmek", f: "sık", type: "fiil" },
  { w: "pivotal", tr: "kilit önemde", f: "sık", type: "sıfat" },
  { w: "plausible", tr: "akla yatkın", f: "sık", type: "sıfat" },
  { w: "predominant", tr: "baskın, ağır basan", f: "orta", type: "sıfat" },
  { w: "profound", tr: "derin, köklü", f: "çok", type: "sıfat" },
  { w: "prohibit", tr: "yasaklamak", f: "sık", type: "fiil" },
  { w: "reluctant", tr: "isteksiz, gönülsüz", f: "çok", type: "sıfat" },
  { w: "restore", tr: "yeniden kurmak, onarmak", f: "sık", type: "fiil" },
  { w: "restrict", tr: "kısıtlamak", f: "sık", type: "fiil" },
  { w: "scrutinize", tr: "dikkatle incelemek", f: "sık", type: "fiil" },
  { w: "significant", tr: "önemli, anlamlı", f: "çok", type: "sıfat" },
  { w: "simultaneous", tr: "eş zamanlı", f: "orta", type: "sıfat" },
  { w: "sophisticated", tr: "gelişmiş, karmaşık", f: "sık", type: "sıfat" },
  { w: "substantial", tr: "önemli, kayda değer", f: "çok", type: "sıfat" },
  { w: "suppress", tr: "bastırmak", f: "sık", type: "fiil" },
  { w: "susceptible", tr: "duyarlı, kolay etkilenir", f: "sık", type: "sıfat" },
  { w: "temporary", tr: "geçici", f: "çok", type: "sıfat" },
  { w: "undergo", tr: "geçirmek (süreç)", f: "çok", type: "fiil" },
  { w: "undermine", tr: "altını oymak, zayıflatmak", f: "sık", type: "fiil" },
  { w: "verify", tr: "doğrulamak", f: "sık", type: "fiil" },
  { w: "vulnerable", tr: "savunmasız, korunmasız", f: "çok", type: "sıfat" },
  { w: "widespread", tr: "yaygın", f: "çok", type: "sıfat" },
  { w: "withdraw", tr: "geri çekmek; çekilmek", f: "sık", type: "fiil" },
  { w: "yield", tr: "vermek, ürün vermek; boyun eğmek", f: "sık", type: "fiil" },
  { w: "account for", tr: "açıklamak; oluşturmak (pay)", f: "çok", type: "öbek fiil" },
  { w: "bring about", tr: "yol açmak", f: "sık", type: "öbek fiil" },
  { w: "call off", tr: "iptal etmek", f: "sık", type: "öbek fiil" },
  { w: "carry out", tr: "yürütmek, uygulamak", f: "çok", type: "öbek fiil" },
  { w: "come across", tr: "rastlamak", f: "sık", type: "öbek fiil" },
  { w: "look into", tr: "araştırmak", f: "sık", type: "öbek fiil" },
  { w: "put off", tr: "ertelemek", f: "sık", type: "öbek fiil" },
  { w: "run out of", tr: "tükenmek", f: "sık", type: "öbek fiil" },
  { w: "turn out", tr: "sonuçlanmak, meğer çıkmak", f: "sık", type: "öbek fiil" },
  { w: "take into account", tr: "hesaba katmak", f: "sık", type: "öbek fiil" },
  { w: "point out", tr: "işaret etmek, belirtmek", f: "çok", type: "öbek fiil" },
  { w: "rule out", tr: "ihtimal dışı bırakmak", f: "orta", type: "öbek fiil" },
  { w: "stem from", tr: "...den kaynaklanmak", f: "sık", type: "öbek fiil" },
  { w: "give rise to", tr: "yol açmak, neden olmak", f: "sık", type: "öbek fiil" },
];
