// YDS soru bankası — ÇEKİRDEK (kelime, gramer, cümle, çeviri, restatement, akış, diyalog)
export type QType =
  | "vocab"
  | "grammar"
  | "cloze"
  | "sentence"
  | "en-tr"
  | "tr-en"
  | "restate"
  | "irrel"
  | "dialogue"
  | "reading";

export interface BankQ {
  id?: string;
  t: QType;
  s: string; // stem / soru
  o: string[]; // 5 seçenek
  a: number; // doğru indeks
  ex?: string; // açıklama
  p?: string; // pasaj metni (cloze / reading)
  pt?: string; // pasaj başlığı
  level?: string;
  difficulty?: "easy" | "medium" | "hard";
  sourceType?: "original-yds-style";
  isOfficial?: boolean;
}

export const CORE: BankQ[] = [
  // ================= KELİME (46) =================
  { t: "vocab", s: "The new drug has proven highly ---- in treating the disease, with very few side effects.", o: ["effective", "defective", "ineffective", "objective", "selective"], a: 0, ex: "effective = etkili; 'few side effects' olumlu bağlam." },
  { t: "vocab", s: "Many species are ---- to extinction because of widespread habitat loss.", o: ["vulnerable", "immune", "superior", "devoted", "accustomed"], a: 0, ex: "be vulnerable to = ...e karşı savunmasız." },
  { t: "vocab", s: "The committee decided to ---- the meeting until next week due to unforeseen circumstances.", o: ["postpone", "advance", "cancel", "convene", "attend"], a: 0, ex: "postpone = ertelemek." },
  { t: "vocab", s: "His theory was initially dismissed, but later evidence ---- its validity.", o: ["confirmed", "denied", "refused", "objected", "challenged"], a: 0, ex: "confirmed = doğruladı; 'but later' zıtlığı." },
  { t: "vocab", s: "The government introduced new measures to ---- the spread of the virus.", o: ["curb", "promote", "accelerate", "encourage", "expand"], a: 0, ex: "curb = frenlemek." },
  { t: "vocab", s: "The two reports reached ---- conclusions, which confused the committee.", o: ["contradictory", "identical", "obvious", "preliminary", "unanimous"], a: 0, ex: "contradictory = çelişkili; 'confused' ipucu." },
  { t: "vocab", s: "She has a ---- knowledge of ancient history, gained through years of research.", o: ["profound", "superficial", "negligible", "trivial", "limited"], a: 0, ex: "profound = derin." },
  { t: "vocab", s: "The company's profits have been ---- over the past year, rising by 30 percent.", o: ["soaring", "declining", "stagnant", "plummeting", "fluctuating"], a: 0, ex: "soaring = hızla yükselen." },
  { t: "vocab", s: "Regular exercise can help ---- the symptoms of mild depression.", o: ["alleviate", "aggravate", "provoke", "intensify", "induce"], a: 0, ex: "alleviate = hafifletmek." },
  { t: "vocab", s: "The instructions were so ---- that even the interns could follow them easily.", o: ["explicit", "ambiguous", "vague", "obscure", "implicit"], a: 0, ex: "explicit = açık, net; 'easily' ipucu." },
  { t: "vocab", s: "The constant criticism began to ---- his self-confidence over time.", o: ["undermine", "reinforce", "strengthen", "boost", "enhance"], a: 0, ex: "undermine = altını oymak, zayıflatmak." },
  { t: "vocab", s: "The witness's account was not ----, so the jury doubted her story.", o: ["credible", "incredible", "remarkable", "notorious", "plausible"], a: 0, ex: "credible = inandırıcı; 'doubted' ipucu." },
  { t: "vocab", s: "The company plans to ---- more resources to research and development next year.", o: ["allocate", "withdraw", "deprive", "neglect", "accumulate"], a: 0, ex: "allocate = tahsis etmek." },
  { t: "vocab", s: "Despite the heavy workload, she managed to ---- and complete the project on time.", o: ["persist", "surrender", "hesitate", "retreat", "collapse"], a: 0, ex: "persist = sebat etmek." },
  { t: "vocab", s: "Over the years, dust began to ---- on the unused furniture in the attic.", o: ["accumulate", "dissolve", "evaporate", "diminish", "vanish"], a: 0, ex: "accumulate = birikmek." },
  { t: "vocab", s: "The lab must ---- the results before publishing them in the journal.", o: ["verify", "falsify", "fabricate", "overlook", "conceal"], a: 0, ex: "verify = doğrulamak." },
  { t: "vocab", s: "The government tried to ---- the protests by banning public gatherings.", o: ["suppress", "encourage", "provoke", "stimulate", "promote"], a: 0, ex: "suppress = bastırmak." },
  { t: "vocab", s: "The storm is ---- and residents have been advised to stay indoors.", o: ["imminent", "remote", "distant", "unlikely", "ancient"], a: 0, ex: "imminent = eli kulağında, yakın." },
  { t: "vocab", s: "Participation in the survey was entirely ----; nobody was forced to take part.", o: ["voluntary", "compulsory", "mandatory", "obligatory", "required"], a: 0, ex: "voluntary = gönüllü; 'nobody was forced' ipucu." },
  { t: "vocab", s: "The new law has caused considerable ---- among small business owners.", o: ["controversy", "harmony", "consensus", "agreement", "approval"], a: 0, ex: "controversy = tartışma, ihtilaf." },
  { t: "vocab", s: "The documentary presents ---- evidence that the ancient city was once a major port.", o: ["compelling", "trivial", "dubious", "feeble", "doubtful"], a: 0, ex: "compelling = ikna edici, güçlü." },
  { t: "vocab", s: "The architect was known for his ---- attention to even the smallest details.", o: ["meticulous", "careless", "negligent", "reckless", "sloppy"], a: 0, ex: "meticulous = titiz." },
  { t: "vocab", s: "Many experts remain ---- about the long-term benefits of the new technology.", o: ["skeptical", "enthusiastic", "optimistic", "convinced", "certain"], a: 0, ex: "skeptical = şüpheci." },
  { t: "vocab", s: "The essay was well-structured and ----, making it easy to follow.", o: ["coherent", "chaotic", "disjointed", "confusing", "rambling"], a: 0, ex: "coherent = tutarlı, bütünlüklü." },
  { t: "vocab", s: "The campaign aims to ---- malaria from the region within a decade.", o: ["eradicate", "spread", "transmit", "propagate", "multiply"], a: 0, ex: "eradicate = kökünü kazımak." },
  { t: "vocab", s: "The two events may seem unrelated, but they ---- in several surprising ways.", o: ["coincide", "contradict", "diverge", "conflict", "separate"], a: 0, ex: "coincide = çakışmak, örtüşmek." },
  { t: "vocab", s: "Oil prices tend to ---- wildly during periods of political instability.", o: ["fluctuate", "stabilize", "freeze", "settle", "fix"], a: 0, ex: "fluctuate = dalgalanmak." },
  { t: "vocab", s: "Risk is ---- in any kind of investment; it cannot be completely avoided.", o: ["inherent", "absent", "external", "optional", "avoidable"], a: 0, ex: "inherent = doğasında var olan." },
  { t: "vocab", s: "Her research played a ---- role in the development of the new vaccine.", o: ["pivotal", "minor", "trivial", "negligible", "peripheral"], a: 0, ex: "pivotal = kilit, merkezî." },
  { t: "vocab", s: "There is ---- support for the reform across all political parties.", o: ["widespread", "scarce", "limited", "narrow", "isolated"], a: 0, ex: "widespread = yaygın." },
  { t: "vocab", s: "His explanation seemed ---- at first, but closer inspection revealed gaps.", o: ["plausible", "absurd", "ridiculous", "impossible", "ludicrous"], a: 0, ex: "plausible = akla yatkın; 'but' zıtlığı." },
  { t: "vocab", s: "The bright yellow sign was deliberately ---- to attract drivers' attention.", o: ["conspicuous", "invisible", "subtle", "hidden", "unnoticeable"], a: 0, ex: "conspicuous = göze çarpan." },
  { t: "vocab", s: "The old bridge will ---- major repairs before it can be reopened.", o: ["undergo", "avoid", "resist", "reject", "decline"], a: 0, ex: "undergo = (süreçten) geçmek." },
  { t: "vocab", s: "The valley is famous for its ---- supply of fresh spring water.", o: ["abundant", "scarce", "meagre", "deficient", "sparse"], a: 0, ex: "abundant = bol." },
  { t: "vocab", s: "The reporter refused to ---- his sources to protect their identities.", o: ["disclose", "conceal", "hide", "suppress", "withhold"], a: 0, ex: "disclose = açıklamak, ifşa etmek." },
  { t: "vocab", s: "The athlete's decision to retire was ----; he had been hinting at it for months.", o: ["inevitable", "unexpected", "abrupt", "sudden", "spontaneous"], a: 0, ex: "inevitable = kaçınılmaz; 'hinting for months' ipucu." },
  { t: "vocab", s: "The committee will ---- every clause of the agreement before signing it.", o: ["scrutinize", "ignore", "overlook", "skim", "neglect"], a: 0, ex: "scrutinize = dikkatle incelemek." },
  { t: "vocab", s: "Old paper maps have become largely ---- in the age of GPS navigation.", o: ["obsolete", "essential", "vital", "crucial", "indispensable"], a: 0, ex: "obsolete = kullanımdan kalkmış." },
  { t: "vocab", s: "A balanced diet is ---- for the healthy development of children.", o: ["indispensable", "optional", "expendable", "superfluous", "unnecessary"], a: 0, ex: "indispensable = vazgeçilmez." },
  { t: "vocab", s: "He was ---- to accept the offer because it required relocating abroad.", o: ["reluctant", "eager", "keen", "willing", "enthusiastic"], a: 0, ex: "reluctant = isteksiz." },
  { t: "vocab", s: "The word 'robot' is ---- from a Czech word meaning 'forced labour'.", o: ["derived", "separated", "removed", "excluded", "isolated"], a: 0, ex: "derive from = ...den türemek." },
  { t: "vocab", s: "The campaign aims to ---- public awareness of the dangers of smoking.", o: ["enhance", "diminish", "suppress", "reduce", "undermine"], a: 0, ex: "enhance = artırmak, geliştirmek." },
  { t: "vocab", s: "It is a common ---- that humans only use ten percent of their brains.", o: ["notion", "fact", "reality", "certainty", "proof"], a: 0, ex: "notion = yaygın (çoğu kez yanlış) kanı." },
  { t: "vocab", s: "Small children ---- danger quite differently from adults.", o: ["perceive", "ignore", "dismiss", "overlook", "neglect"], a: 0, ex: "perceive = algılamak." },
  { t: "vocab", s: "The painting successfully ---- a deep sense of loneliness.", o: ["conveys", "hides", "conceals", "masks", "disguises"], a: 0, ex: "convey = iletmek, aktarmak." },
  { t: "vocab", s: "Women now ---- more than half of the country's medical graduates.", o: ["constitute", "exclude", "dismiss", "eliminate", "reject"], a: 0, ex: "constitute = oluşturmak." },

  // ================= GRAMER (38) =================
  { t: "grammar", s: "By the time we arrived at the station, the train ----.", o: ["had already left", "already left", "will have left", "has left", "leaves"], a: 0, ex: "by the time + V2 → Past Perfect." },
  { t: "grammar", s: "The report, which ---- last month, will be discussed at today's meeting.", o: ["was completed", "completed", "has completed", "completes", "is completing"], a: 0, ex: "edilgen: was completed." },
  { t: "grammar", s: "If I ---- about the meeting, I would have attended it.", o: ["had known", "knew", "have known", "would know", "know"], a: 0, ex: "Type 3: If + had V3." },
  { t: "grammar", s: "Not only ---- the exam, but he also got the highest score in the class.", o: ["did he pass", "he passed", "he did pass", "passed he", "did he passed"], a: 0, ex: "Not only + devrik: did he pass." },
  { t: "grammar", s: "The novel, ---- author won a Nobel Prize, has been translated into forty languages.", o: ["whose", "which", "whom", "who", "that"], a: 0, ex: "sahiplik: whose author." },
  { t: "grammar", s: "They suggested that the factory ---- temporarily closed for maintenance.", o: ["be", "is", "was", "would be", "has been"], a: 0, ex: "suggest that + yalın fiil (subjunctive)." },
  { t: "grammar", s: "The more you practice, ---- you will become.", o: ["the more confident", "more confident", "the confident", "confident", "the most confident"], a: 0, ex: "the + comparative, the + comparative." },
  { t: "grammar", s: "Hardly ---- the concert ---- it started to rain.", o: ["had ... begun when", "did ... begin when", "had ... begun than", "has ... begun when", "... began when"], a: 0, ex: "Hardly + had + özne + V3 + when." },
  { t: "grammar", s: "The data ---- in the experiment will be presented at the conference.", o: ["obtained", "obtain", "obtaining", "to obtain", "obtains"], a: 0, ex: "pasif kısaltma: (which was) obtained." },
  { t: "grammar", s: "She had her car ---- by a professional mechanic last week.", o: ["repaired", "repair", "repairing", "to repair", "repairs"], a: 0, ex: "have + nesne + V3: had her car repaired." },
  { t: "grammar", s: "I'm looking forward to ---- from you soon.", o: ["hearing", "hear", "heard", "be heard", "have heard"], a: 0, ex: "look forward to + Ving." },
  { t: "grammar", s: "The children stopped ---- when the teacher entered the room.", o: ["talking", "to talk", "talk", "talked", "having talked"], a: 0, ex: "stop + Ving = eylemi bırakmak." },
  { t: "grammar", s: "It is essential that every candidate ---- the form before the deadline.", o: ["submit", "submits", "submitted", "would submit", "is submitting"], a: 0, ex: "It is essential that + yalın fiil." },
  { t: "grammar", s: "The book was written in 1920, ---- makes it almost a century old.", o: ["which", "what", "who", "whom", "that it"], a: 0, ex: "which tüm cümleyi temsil eder (virgüllü)." },
  { t: "grammar", s: "---- the rain, the match continued as planned.", o: ["Despite", "Although", "Even though", "Whereas", "Because"], a: 0, ex: "Despite + isim; diğerleri cümle ister." },
  { t: "grammar", s: "The manager insisted that the deadline ---- extended by two weeks.", o: ["be", "is", "was", "has been", "would be"], a: 0, ex: "insist that + yalın fiil." },
  { t: "grammar", s: "By next year, she ---- at this company for ten years.", o: ["will have been working", "will work", "has worked", "works", "worked"], a: 0, ex: "by next year → Future Perfect (Continuous)." },
  { t: "grammar", s: "The museum ---- by millions of tourists since it opened in 2010.", o: ["has been visited", "is visited", "was visited", "will be visited", "visited"], a: 0, ex: "since + Present Perfect Passive." },
  { t: "grammar", s: "If he were more careful, he ---- so many mistakes.", o: ["wouldn't make", "won't make", "hadn't made", "wouldn't have made", "doesn't make"], a: 0, ex: "Type 2: If + V2/were → would + V1." },
  { t: "grammar", s: "The teacher asked the students why they ---- their homework.", o: ["hadn't done", "didn't do", "won't do", "don't do", "haven't done"], a: 0, ex: "dolaylı soru + geçmişin geçmişi → had done." },
  { t: "grammar", s: "No sooner ---- the door than the phone rang.", o: ["had he closed", "he closed", "did he close", "he had closed", "has he closed"], a: 0, ex: "No sooner + had + özne + V3 + than." },
  { t: "grammar", s: "The meeting was postponed ---- the CEO's sudden illness.", o: ["owing to", "in spite", "despite of", "although", "even"], a: 0, ex: "owing to = yüzünden (isim ile)." },
  { t: "grammar", s: "Neither of the two proposals ---- acceptable to the board.", o: ["was", "were", "are", "have been", "being"], a: 0, ex: "neither + tekil fiil." },
  { t: "grammar", s: "A number of students ---- complained about the exam schedule.", o: ["have", "has", "was", "is", "had been"], a: 0, ex: "a number of + çoğul fiil." },
  { t: "grammar", s: "You ---- the door unlocked; anyone could have walked in.", o: ["shouldn't have left", "shouldn't leave", "mustn't leave", "didn't need to leave", "can't have left"], a: 0, ex: "shouldn't have + V3 = geçmişte yapılmaması gerekirdi." },
  { t: "grammar", s: "The lights are all off, so everyone ---- home hours ago.", o: ["must have gone", "should have gone", "might have gone", "couldn't have gone", "would go"], a: 0, ex: "güçlü kanıt → must have + V3." },
  { t: "grammar", s: "He speaks three languages, and so ---- his sister.", o: ["does", "is", "has", "speaks", "do"], a: 0, ex: "so + yardımcı + özne: so does his sister." },
  { t: "grammar", s: "The documentary, ---- in 2019, won several international awards.", o: ["produced", "producing", "produce", "to produce", "produces"], a: 0, ex: "pasif kısaltma: (which was) produced." },
  { t: "grammar", s: "It was in this small village ---- the famous poet spent his childhood.", o: ["that", "which", "where", "when", "whom"], a: 0, ex: "cleft sentence: It was ... that ..." },
  { t: "grammar", s: "---- the rain had stopped, the roads were still flooded.", o: ["Even though", "Despite", "In spite of", "Due to", "Owing to"], a: 0, ex: "Even though + cümle; despite + isim." },
  { t: "grammar", s: "The company ---- its profits would double, but the crisis changed everything.", o: ["had expected", "expected", "has expected", "expects", "was expecting"], a: 0, ex: "geçmişten önceki beklenti → Past Perfect." },
  { t: "grammar", s: "Rarely ---- such a talented young musician on this stage.", o: ["have we seen", "we have seen", "we saw", "did we saw", "we see"], a: 0, ex: "Rarely + devrik: have we seen." },
  { t: "grammar", s: "The new policy, ---- several experts have criticised, will take effect next month.", o: ["which", "that", "who", "whose", "where"], a: 0, ex: "edatlardan sonra which (virgüllü)." },
  { t: "grammar", s: "By the end of this century, sea levels ---- significantly.", o: ["will have risen", "rise", "have risen", "are rising", "rose"], a: 0, ex: "by the end of + Future Perfect." },
  { t: "grammar", s: "The children were made ---- their rooms before going out.", o: ["to clean", "clean", "cleaning", "cleaned", "cleans"], a: 0, ex: "make (passive) → be made TO do." },
  { t: "grammar", s: "Had I known about the traffic, I ---- earlier.", o: ["would have left", "would leave", "will leave", "had left", "leave"], a: 0, ex: "Had I known = If I had known (Type 3)." },
  { t: "grammar", s: "The report is ---- that it needs a complete rewrite.", o: ["so badly written", "such badly written", "so bad written", "too badly written", "very badly written"], a: 0, ex: "so + zarf + V3: so badly written that..." },
  { t: "grammar", s: "The athlete was disqualified ---- he had used a banned substance.", o: ["on the grounds that", "despite that", "in spite of that", "due to that", "because of"], a: 0, ex: "on the grounds that = gerekçesiyle (cümle alır)." },

  // ================= CÜMLE TAMAMLAMA (16) =================
  { t: "sentence", s: "Although the experiment failed, ----.", o: ["the researchers learned a great deal from it", "it was a complete success", "the results were published immediately", "no one was involved in it", "the hypothesis was confirmed"], a: 0, ex: "although + olumsuz → temkinli olumlu sonuç." },
  { t: "sentence", s: "---- as long as the economy remains stable.", o: ["The housing market is expected to keep growing", "Housing prices fell sharply", "The market crashed last year", "Investors lost confidence", "A recession began"], a: 0, ex: "as long as = olduğu sürece." },
  { t: "sentence", s: "The city has introduced a new recycling program ----.", o: ["to reduce the amount of waste going to landfills", "because waste had already disappeared", "although landfills were empty", "since recycling was banned", "unless waste increased"], a: 0, ex: "amaç: to reduce..." },
  { t: "sentence", s: "Scientists believe that ----, the polar ice caps will continue to melt.", o: ["unless urgent action is taken", "even though action was taken", "despite the measures", "as if nothing happened", "in case action has been taken"], a: 0, ex: "unless = ...medikçe." },
  { t: "sentence", s: "The film was so boring ----.", o: ["that half the audience left before the interval", "that everyone stayed until the end", "so the cinema was completely full", "because it won several awards", "although it was very exciting"], a: 0, ex: "so boring that ... ayrıldı." },
  { t: "sentence", s: "----, the company still managed to turn a profit.", o: ["Despite facing fierce competition", "Because the market collapsed", "Since sales doubled", "As demand increased", "While costs were falling"], a: 0, ex: "despite + zıtlık → yine de kâr." },
  { t: "sentence", s: "The more data the system collects, ----.", o: ["the more accurate its predictions become", "its predictions become less accurate", "the less it learns about users", "so it stops making predictions", "although it becomes slower"], a: 0, ex: "the more ..., the more ..." },
  { t: "sentence", s: "You should back up your files regularly ----.", o: ["in case your computer crashes", "so that your computer crashed", "unless your computer crashed", "because your computer had crashed", "although your computer crashes"], a: 0, ex: "in case = ... olursa diye." },
  { t: "sentence", s: "----, it attracted thousands of visitors on the first day.", o: ["Even though the exhibition opened without much publicity", "Unless the exhibition opened early", "Since the exhibition was cancelled", "Despite the exhibition being closed", "As if the exhibition had no visitors"], a: 0, ex: "even though + zıtlık." },
  { t: "sentence", s: "The team worked overtime ----.", o: ["so that they could meet the deadline", "in case they missed the deadline", "unless they met the deadline", "as if the deadline was met", "although they met the deadline"], a: 0, ex: "so that = amacıyla." },
  { t: "sentence", s: "----, the two countries signed a historic peace agreement.", o: ["After years of bitter conflict", "Before the war even began", "As if there had never been peace", "Although the war ended", "Despite signing nothing"], a: 0, ex: "after + zıtlık çözümü." },
  { t: "sentence", s: "The library remains open until midnight ----.", o: ["so that students can study for their exams", "in case students studied during the day", "unless students study at night", "because students never study", "although students study at home"], a: 0, ex: "so that = amacıyla." },
  { t: "sentence", s: "----, the singer still decided to perform.", o: ["Even though she had completely lost her voice", "Because she was in perfect health", "Since the concert was cancelled", "As the audience had left", "In case the show was sold out"], a: 0, ex: "even though + zorluğa rağmen." },
  { t: "sentence", s: "The researchers will publish their findings ----.", o: ["once the peer review process is complete", "unless the study was finished", "although the review is complete", "as if the data was verified", "because the results were rejected"], a: 0, ex: "once = ...diği zaman." },
  { t: "sentence", s: "----, the old factory now serves as an art gallery.", o: ["Having been abandoned for decades", "Being built last year", "To be demolished soon", "Having employed thousands", "To be renovated by the city"], a: 0, ex: "Having been abandoned = terk edilmiş olduğu için." },
  { t: "sentence", s: "The teacher explained the topic twice ----.", o: ["so that everyone could understand it clearly", "in case everyone understood it", "unless someone understood it", "because nobody asked questions", "as if it was perfectly clear"], a: 0, ex: "so that = amacıyla." },

  // ================= ÇEVİRİ EN → TR (12) =================
  { t: "en-tr", s: "The research indicates that children who read regularly tend to develop stronger analytical skills.", o: ["Araştırma, düzenli okuyan çocukların daha güçlü analitik beceriler geliştirme eğiliminde olduğunu gösteriyor.", "Düzenli okuyan çocuklar analitik becerilerini tamamen kaybeder.", "Araştırma yalnızca yetişkinlerin okuma alışkanlıklarını inceliyor.", "Çocukların analitik becerileri okumayla hiç ilgili değildir.", "Araştırma, okumanın çocuklara zarar verdiğini kanıtladı."], a: 0, ex: "indicates → gösteriyor; tend to → eğiliminde." },
  { t: "en-tr", s: "Despite the heavy rain, the outdoor concert attracted a record number of spectators.", o: ["Şiddetli yağmura rağmen açık hava konseri rekor sayıda izleyici çekti.", "Yağmur yüzünden konser tamamen iptal edildi.", "Konser kapalı alanda yapıldığı için çok kalabalıktı.", "Şiddetli yağmur izleyicilerin çoğunu kaçırdı.", "Açık hava konserine hiç kimse gelmedi."], a: 0, ex: "Despite → rağmen." },
  { t: "en-tr", s: "The findings of the study may help researchers develop new treatments for the disease.", o: ["Çalışmanın bulguları, araştırmacıların hastalık için yeni tedaviler geliştirmesine yardımcı olabilir.", "Çalışma, hastalığın tedavisini kesin olarak bulmuştur.", "Araştırmacılar yeni tedaviler geliştirmeyi reddetti.", "Bulgular, hastalığın asla tedavi edilemeyeceğini gösteriyor.", "Hastalık için hiçbir tedavi gerekmiyor."], a: 0, ex: "may help → yardımcı olabilir." },
  { t: "en-tr", s: "Unless drastic measures are taken, air pollution in major cities will keep worsening.", o: ["Kökten önlemler alınmadıkça büyük şehirlerdeki hava kirliliği kötüleşmeye devam edecek.", "Kökten önlemler alındığı için hava kirliliği arttı.", "Hava kirliliği büyük şehirlerde hiçbir zaman sorun olmadı.", "Alınan önlemler sayesinde hava kirliliği tamamen bitti.", "Hava kirliliği yalnızca kırsal bölgeleri etkiliyor."], a: 0, ex: "unless → alınmadıkça." },
  { t: "en-tr", s: "The discovery of antibiotics is widely regarded as one of the greatest medical breakthroughs.", o: ["Antibiyotiklerin keşfi, geniş çapta en büyük tıbbi buluşlardan biri olarak kabul edilir.", "Antibiyotiklerin keşfi tıp tarihinde hiç önem taşımaz.", "Antibiyotikler yalnızca veterinerlikte kullanılır.", "Tıbbi buluşlar antibiyotiklerin keşfini engelledi.", "Antibiyotikler hiçbir hastalığı tedavi edemez."], a: 0, ex: "is widely regarded as → kabul edilir." },
  { t: "en-tr", s: "Had the company invested in renewable energy earlier, it would not be facing such high costs today.", o: ["Şirket yenilenebilir enerjiye daha önce yatırım yapmış olsaydı, bugün bu kadar yüksek maliyetlerle karşılaşmazdı.", "Şirket yenilenebilir enerjiye yatırım yaptığı için bugün çok yüksek maliyetlerle karşılaşıyor.", "Yenilenebilir enerji, şirketin maliyetlerini her zaman artırır.", "Şirket bugün yüksek maliyetlerle karşılaşmayı tercih etti.", "Yenilenebilir enerji yatırımları hiçbir zaman kârlı değildir."], a: 0, ex: "Had ... invested → yatırım yapmış olsaydı (Type 3)." },
  { t: "en-tr", s: "The professor's lecture was so complex that most students had difficulty following it.", o: ["Profesörün dersi o kadar karmaşıktı ki çoğu öğrenci takip etmekte zorlandı.", "Profesörün dersi o kadar basitti ki herkes anında anladı.", "Öğrenciler dersi hiç zorlanmadan takip etti.", "Profesör dersi son dakikada iptal etti.", "Derse yalnızca birkaç öğrenci katıldı."], a: 0, ex: "so complex that ... had difficulty." },
  { t: "en-tr", s: "It is estimated that over a million species are currently at risk of extinction.", o: ["Şu anda bir milyondan fazla türün yok olma riski altında olduğu tahmin ediliyor.", "Bir milyon tür çoktan yok oldu.", "Yok olma riski artık bilim insanlarını ilgilendirmiyor.", "Bugün yalnızca birkaç tür risk altında.", "Türler artık yok olma riski taşımıyor."], a: 0, ex: "It is estimated → tahmin ediliyor." },
  { t: "en-tr", s: "Although the new policy was designed to reduce traffic, congestion has continued to rise.", o: ["Yeni politika trafiği azaltmak için tasarlanmış olsa da sıkışıklık artmaya devam etti.", "Yeni politika sayesinde trafik tamamen azaldı.", "Trafik sıkışıklığı hiçbir zaman sorun olmadı.", "Politika trafiği artırmak için tasarlandı.", "Sıkışıklık azaldığı için politika kaldırıldı."], a: 0, ex: "although + zıtlık." },
  { t: "en-tr", s: "The ancient city, which was destroyed by an earthquake, was declared a heritage site in 1994.", o: ["Bir depremle yerle bir olan antik kent, 1994'te miras alanı ilan edildi.", "Antik kent 1994'te kuruldu.", "Deprem 1994'te antik kenti inşa etti.", "Miras alanı deprem nedeniyle kaldırıldı.", "Antik kent hiçbir zaman deprem yaşamadı."], a: 0, ex: "which was destroyed → yerle bir olan." },
  { t: "en-tr", s: "No sooner had the final whistle blown than the fans flooded onto the pitch.", o: ["Final düdüğü çalar çalmaz taraftarlar sahaya akın etti.", "Final düdüğünden çok önce taraftarlar sahaya girdi.", "Taraftarlar düdük çalmadan sahayı terk etti.", "Final düdüğü hiç çalınmadı.", "Taraftarlar sahaya girmeyi reddetti."], a: 0, ex: "No sooner ... than = çalar çalmaz." },
  { t: "en-tr", s: "Only by reducing carbon emissions can we hope to slow down global warming.", o: ["Küresel ısınmayı yavaşlatmayı ancak karbon emisyonlarını azaltarak umabiliriz.", "Karbon emisyonları küresel ısınmayla ilgisizdir.", "Küresel ısınma zaten tamamen durmuştur.", "Emisyonları artırarak küresel ısınmayı durdurabiliriz.", "Küresel ısınma yalnızca bir efsanedir."], a: 0, ex: "Only by + devrik: ancak ... azaltarak." },

  // ================= ÇEVİRİ TR → EN (12) =================
  { t: "tr-en", s: "Teknoloji geliştikçe, uzaktan çalışma birçok sektörde yaygınlaşmaktadır.", o: ["As technology develops, remote working is becoming widespread in many sectors.", "Technology developed because remote working became widespread.", "Remote working prevented technology from developing.", "Technology will never affect remote working.", "Remote working is spreading only in the technology sector."], a: 0, ex: "geliştikçe → as ... develops." },
  { t: "tr-en", s: "Hükümet eğitime daha fazla yatırım yapmadığı sürece bu sorun çözülmeyecektir.", o: ["This problem will not be solved unless the government invests more in education.", "The problem was solved because the government invested in education.", "The government solved the problem without investing in education.", "Education is unrelated to this problem.", "The problem has already been solved by the government."], a: 0, ex: "...madığı sürece → unless." },
  { t: "tr-en", s: "İklim değişikliği konusunda acil önlemler alınması gerekiyor.", o: ["Urgent measures need to be taken regarding climate change.", "Climate change needs to be completely ignored.", "Urgent measures were never needed for climate change.", "Climate change is unrelated to any measures.", "Measures should be postponed indefinitely."], a: 0, ex: "alınması gerekiyor → need to be taken (edilgen)." },
  { t: "tr-en", s: "Rapor, şirketin geçen yılki performansını ayrıntılı olarak analiz ediyor.", o: ["The report analyses the company's performance last year in detail.", "The report ignores the company's performance entirely.", "The company analysed the report's performance last year.", "The report was never written.", "The company's performance is unrelated to the report."], a: 0, ex: "analiz ediyor → analyses; in detail → ayrıntılı." },
  { t: "tr-en", s: "Yeni keşfedilen gezegen, Dünya'dan yaklaşık iki kat daha büyüktür.", o: ["The newly discovered planet is about twice as large as Earth.", "The newly discovered planet is half the size of Earth.", "Earth is twice as large as the newly discovered planet.", "The planet was never discovered.", "The planet and Earth are exactly the same size."], a: 0, ex: "iki kat daha büyük → twice as large as." },
  { t: "tr-en", s: "Kütüphaneye gittiğimde, arkadaşım oradan çoktan ayrılmıştı.", o: ["When I went to the library, my friend had already left there.", "When I go to the library, my friend will leave there.", "My friend left the library before I went there for the first time.", "The library had already closed when my friend arrived.", "My friend never went to the library."], a: 0, ex: "çoktan ayrılmıştı → had already left." },
  { t: "tr-en", s: "Bu kadar çok hata yapmasaydı, sınavı geçmiş olurdu.", o: ["If he had not made so many mistakes, he would have passed the exam.", "If he makes many mistakes, he will pass the exam.", "He passed the exam despite making many mistakes.", "He made no mistakes, so he failed the exam.", "The exam was never held."], a: 0, ex: "Type 3: yapmasaydı → had not made." },
  { t: "tr-en", s: "Toplantı yarın sabah saat dokuzda yapılacak.", o: ["The meeting will be held at nine o'clock tomorrow morning.", "The meeting was held at nine o'clock yesterday.", "The meeting is never held in the morning.", "The meeting held itself at nine o'clock.", "The meeting will be held at night tomorrow."], a: 0, ex: "yapılacak → will be held (edilgen)." },
  { t: "tr-en", s: "Birçok insan, yapay zekânın iş dünyasını köklü biçimde değiştireceğine inanıyor.", o: ["Many people believe that artificial intelligence will fundamentally change the business world.", "Artificial intelligence has never affected the business world.", "Few people think artificial intelligence will change anything.", "The business world will prevent artificial intelligence from changing.", "Artificial intelligence only affects entertainment."], a: 0, ex: "inanıyor → believe that." },
  { t: "tr-en", s: "Proje, kaynak yetersizliği nedeniyle geçen ay iptal edildi.", o: ["The project was cancelled last month due to a lack of resources.", "The project was launched last month with plenty of resources.", "The project cancelled itself because of success.", "The project will never be cancelled.", "Resources were abundant, so the project ended."], a: 0, ex: "iptal edildi → was cancelled; due to → nedeniyle." },
  { t: "tr-en", s: "Bu tarihi binayı restore etmek için büyük çaba harcandı.", o: ["Great effort was made to restore this historic building.", "Great effort was made to demolish this historic building.", "No effort was made to restore the building.", "The historic building restored itself.", "Restoring the building required no effort."], a: 0, ex: "harcandı → was made (edilgen)." },
  { t: "tr-en", s: "Bilim insanları, deneyin sonuçlarını henüz açıklamadı.", o: ["The scientists have not announced the results of the experiment yet.", "The scientists announced the results of the experiment long ago.", "The experiment announced the scientists' results.", "The results of the experiment were announced by nobody.", "The scientists will never announce the results."], a: 0, ex: "henüz ... -medi → have not ... yet." },

  // ================= RESTATEMENT (12) =================
  { t: "restate", s: "It is estimated that over a million species are currently at risk of extinction.", o: ["More than a million species are believed to be in danger of disappearing right now.", "A million species have already become extinct.", "Extinction is no longer a concern for scientists.", "Only a few species are at risk today.", "Species are no longer at risk of disappearing."], a: 0, ex: "at risk → in danger; currently → right now." },
  { t: "restate", s: "The professor's lecture was so complex that most students had difficulty following it.", o: ["Most students found it hard to keep up with the lecture because it was very complicated.", "The lecture was simple and easy for everyone to follow.", "The students understood the lecture immediately.", "The professor cancelled the lecture at the last minute.", "The lecture was attended by only a few students."], a: 0, ex: "so complex → very complicated." },
  { t: "restate", s: "Despite years of research, no cure for the disease has been found yet.", o: ["A cure for the disease has not been discovered so far, even though research has continued for years.", "The disease was cured after many years of research.", "Research stopped because a cure was found.", "The disease is very easy to treat.", "A cure was found immediately after the research began."], a: 0, ex: "Despite → even though; no cure yet → not discovered so far." },
  { t: "restate", s: "It is widely believed that the ancient city was abandoned due to a severe drought.", o: ["Many people think the ancient city was left because of a serious lack of water.", "The ancient city was definitely destroyed by an earthquake.", "The ancient city was never inhabited again after the drought.", "A severe drought is widely believed to have destroyed the ancient city completely.", "The ancient city was built during a severe drought."], a: 0, ex: "abandoned → left; severe drought → serious lack of water." },
  { t: "restate", s: "The company is unlikely to launch the product before the end of the year.", o: ["The product will probably not be launched by the company before the end of the year.", "The company will certainly launch the product before the end of the year.", "The product was launched at the beginning of the year.", "The company has already launched the product.", "The company will never launch the product."], a: 0, ex: "is unlikely to → will probably not." },
  { t: "restate", s: "Hardly anyone attended the conference because of the heavy snowstorm.", o: ["Very few people went to the conference owing to the severe snowstorm.", "Everyone attended the conference despite the snowstorm.", "The conference was cancelled due to the snowstorm.", "Many people attended the conference because of the snowstorm.", "The snowstorm had no effect on attendance."], a: 0, ex: "hardly anyone → very few people." },
  { t: "restate", s: "The new regulation will come into force as of next January.", o: ["The new regulation will become effective starting next January.", "The new regulation was abolished last January.", "The new regulation has already come into force.", "The new regulation will never be effective.", "The new regulation expired last January."], a: 0, ex: "come into force → become effective." },
  { t: "restate", s: "The two countries have agreed to cooperate on environmental issues.", o: ["An agreement has been reached between the two countries to work together on environmental matters.", "The two countries have refused to cooperate on environmental issues.", "Environmental issues will be ignored by both countries.", "The two countries will compete on environmental issues.", "Cooperation between the two countries has ended."], a: 0, ex: "have agreed to cooperate → agreement reached to work together." },
  { t: "restate", s: "The museum attracts more visitors than any other attraction in the city.", o: ["The museum is the most popular attraction in the city.", "The museum is the least visited attraction in the city.", "No one ever visits the museum.", "The museum attracts only local visitors.", "The museum is closed to visitors."], a: 0, ex: "more than any other → the most popular." },
  { t: "restate", s: "It took the team three years to complete the project.", o: ["The team finished the project after working on it for three years.", "The team abandoned the project after three years.", "The project was completed in three days.", "The team completed three projects in one year.", "The project is still unfinished."], a: 0, ex: "It took ... to → finished after working." },
  { t: "restate", s: "The results of the survey are by no means conclusive.", o: ["The survey results are far from being final or certain.", "The survey results are completely certain and final.", "The survey was never conducted.", "The survey results prove everything beyond doubt.", "The survey has conclusively settled the matter."], a: 0, ex: "by no means conclusive → far from certain." },
  { t: "restate", s: "The committee is expected to announce its decision next week.", o: ["It is thought that the committee will announce its decision next week.", "The committee announced its decision last week.", "The committee will never announce its decision.", "The committee refused to make a decision.", "The decision was announced by someone else last week."], a: 0, ex: "is expected to → it is thought that." },

  // ================= AKIŞI BOZAN (12) =================
  { t: "irrel", s: "(I) Renewable energy sources are becoming more affordable every year. (II) Solar panel prices have dropped dramatically over the past decade. (III) Wind farms now produce electricity at competitive rates. (IV) Many people enjoy hiking in the mountains during summer.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV konu dışı (yürüyüş)." },
  { t: "irrel", s: "(I) The Mediterranean diet is widely known for its health benefits. (II) It emphasizes fruits, vegetables, whole grains, and olive oil. (III) Studies have linked it to lower rates of heart disease. (IV) The Mediterranean Sea borders three continents.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV coğrafi bilgi, akışı bozar." },
  { t: "irrel", s: "(I) Regular physical activity strengthens the heart. (II) It also helps control body weight. (III) Exercise releases endorphins that improve mood. (IV) My gym membership costs more than I expected.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV kişisel ve konu dışı." },
  { t: "irrel", s: "(I) The printing press revolutionised the spread of knowledge. (II) Before its invention, books were copied by hand. (III) It was invented by Johannes Gutenberg in the 15th century. (IV) Gutenberg also enjoyed painting landscapes in his free time.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV konu dışı detay." },
  { t: "irrel", s: "(I) Bees are essential pollinators for many crops. (II) Without them, global food production would decline sharply. (III) A single hive can contain tens of thousands of bees. (IV) The decline in bee populations is therefore a serious threat.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 2, ex: "III kopuk istatistik, akışı bozar." },
  { t: "irrel", s: "(I) Learning a second language improves cognitive flexibility. (II) It can also delay the onset of dementia. (III) Bilingual people often switch between languages effortlessly. (IV) My cousin speaks three languages fluently.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV kişisel örnek, konu dışı." },
  { t: "irrel", s: "(I) Plastic pollution is one of the greatest environmental challenges. (II) Millions of tonnes of plastic enter the oceans every year. (III) Marine animals often mistake plastic for food. (IV) Plastic was first synthesised in the early twentieth century.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 0, ex: "IV tarihsel bilgi akışı bozar." },
  { t: "irrel", s: "(I) Sleep plays a vital role in memory consolidation. (II) During deep sleep, the brain strengthens important connections. (III) Sleep deprivation impairs concentration and mood. (IV) Coffee is one of the most traded commodities in the world.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV konu dışı (kahve ticareti)." },
  { t: "irrel", s: "(I) Urban farming is gaining popularity in major cities. (II) Rooftop gardens provide fresh produce to local communities. (III) Vertical farms use far less water than traditional agriculture. (IV) The Eiffel Tower was completed in 1889.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV konu dışı." },
  { t: "irrel", s: "(I) The internet has transformed how people access information. (II) It has also created new forms of social interaction. (III) However, it has raised serious concerns about privacy. (IV) The wheel was invented thousands of years ago.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV konu dışı." },
  { t: "irrel", s: "(I) Reading fiction improves empathy in both children and adults. (II) It allows readers to experience the world from other perspectives. (III) Libraries offer free access to a wide range of books. (IV) Empathy is a skill that can be developed through practice.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 2, ex: "III kütüphane bilgisi akışı bozar." },
  { t: "irrel", s: "(I) Recycling reduces the amount of waste sent to landfills. (II) It also conserves natural resources such as timber and water. (III) Many cities have introduced curbside recycling programmes. (IV) The Pyramids of Giza attract millions of tourists annually.", o: ["I", "II", "III", "IV", "Hiçbiri"], a: 3, ex: "IV konu dışı." },

  // ================= DİYALOG (12) =================
  { t: "dialogue", s: "A: How was your job interview yesterday?\nB: ----. I think they were impressed.", o: ["It went really well", "I'm going to the gym", "It's raining outside", "I have two brothers", "The bus was late"], a: 0, ex: "Soruya mantıklı cevap." },
  { t: "dialogue", s: "A: Would you mind closing the window?\nB: ----. It's a bit chilly in here anyway.", o: ["Not at all", "Yes, I would", "I'm from Ankara", "It's a window", "It's three o'clock"], a: 0, ex: "Would you mind? → Not at all." },
  { t: "dialogue", s: "A: I'm thinking of taking an online course in data science.\nB: ----. I've heard they're very practical.\nA: Exactly, and they fit my schedule much better.", o: ["That sounds like a great idea", "Data science is too difficult for you", "You should have taken it years ago", "I don't think online courses work", "Why would you do that"], a: 0, ex: "Olumlu ve destekleyici ton." },
  { t: "dialogue", s: "A: Do you know where the nearest pharmacy is?\nB: ----. Turn left at the next corner.", o: ["Yes, it's just around the corner", "No, I'm not feeling well", "I bought some medicine yesterday", "The pharmacy is closed on Sundays", "I don't like pharmacies"], a: 0, ex: "Yön tarifi ile devam ediyor." },
  { t: "dialogue", s: "A: I'm afraid I can't come to your party on Saturday.\nB: ----. We'll miss you!", o: ["What a pity", "Congratulations", "How wonderful", "Of course you can't", "That's a great idea"], a: 0, ex: "Üzüntü ifadesi: What a pity." },
  { t: "dialogue", s: "A: Excuse me, could you tell me the time?\nB: ----. My watch has stopped.", o: ["I'm sorry, I don't have a watch", "It's half past nine", "Time flies", "I'm always late", "It's time to go"], a: 0, ex: "Devamı 'saatim durdu' → saati yok." },
  { t: "dialogue", s: "A: I passed my driving test!\nB: ----! You must be thrilled.", o: ["Congratulations", "That's unfortunate", "What a shame", "Better luck next time", "How disappointing"], a: 0, ex: "Başarı → tebrik." },
  { t: "dialogue", s: "A: Would you like some more tea?\nB: ----, thanks. It was delicious.", o: ["Yes, please", "No, never", "I hate tea", "Tea is unhealthy", "I'm full of coffee"], a: 0, ex: "'It was delicious' → evet lütfen." },
  { t: "dialogue", s: "A: I can't find my keys anywhere!\nB: ----? You had them in your hand a minute ago.", o: ["Have you checked your pockets", "Did you buy new keys", "Why are keys so heavy", "Are keys expensive", "Do you like keys"], a: 0, ex: "Mantıklı öneri sorusu." },
  { t: "dialogue", s: "A: The meeting has been postponed to Friday.\nB: ----. I had already prepared everything.", o: ["Oh no, really", "That's great news", "I'm glad to hear that", "Perfect timing", "How exciting"], a: 0, ex: "Hayal kırıklığı: hazırlanmıştı." },
  { t: "dialogue", s: "A: What do you think of the new restaurant downtown?\nB: ----. The food was cold and the service was slow.", o: ["I wasn't impressed at all", "It was absolutely fantastic", "I'd highly recommend it", "It's my favourite place", "We should go there tonight"], a: 0, ex: "Olumsuz yorum." },
  { t: "dialogue", s: "A: Are you free this weekend?\nB: ----. What did you have in mind?", o: ["Yes, I don't have any plans", "No, I'm leaving tomorrow", "I'm always busy", "This weekend was great", "I already went home"], a: 0, ex: "'Ne düşünüyordun?' → müsait." },
];
