export interface CurriculumTopic {
  slug: string;
  title: string;
  emoji: string;
  category: "tenses" | "clauses" | "structures" | "advanced";
  level: string;
  summary: string;
}

export const GRAMMAR_CURRICULUM: readonly CurriculumTopic[] = [
  // ===== 12 TENSE — her biri AYRI konu =====
  {
    slug: "simple-present",
    title: "Simple Present Tense",
    emoji: "☀️",
    category: "tenses",
    level: "A1 → YDS",
    summary: "Genel doğrular, bilimsel gerçekler, alışkanlıklar ve zaman çizelgeleri (time-tables).",
  },
  {
    slug: "present-continuous",
    title: "Present Continuous Tense",
    emoji: "🏃",
    category: "tenses",
    level: "A1 → YDS",
    summary: "Şu anda devam eden eylemler, geçici durumlar ve güncel trendler (increasingly, currently).",
  },
  {
    slug: "present-perfect",
    title: "Present Perfect Tense",
    emoji: "🌉",
    category: "tenses",
    level: "A2 → YDS",
    summary: "Geçmiş ile şimdiki zaman arasındaki köprü: since, for, so far, recently, in recent years.",
  },
  {
    slug: "present-perfect-continuous",
    title: "Present Perfect Continuous",
    emoji: "🌊",
    category: "tenses",
    level: "B1 → YDS",
    summary: "Geçmişten şimdiye kesintisiz süren ve hâlâ devam eden veya belirtisi süren süreçler.",
  },
  {
    slug: "simple-past",
    title: "Simple Past Tense",
    emoji: "📜",
    category: "tenses",
    level: "A1 → YDS",
    summary: "Geçmişte belirli bir zamanda tamamlanmış eylemler (in 1990, yesterday, ancient times).",
  },
  {
    slug: "past-continuous",
    title: "Past Continuous Tense",
    emoji: "🎞️",
    category: "tenses",
    level: "A2 → YDS",
    summary: "Geçmişte belli bir anda veya süreçte devam eden eylemler ve kesilme durumları (while, when).",
  },
  {
    slug: "past-perfect",
    title: "Past Perfect Tense",
    emoji: "⏮️",
    category: "tenses",
    level: "B1 → YDS",
    summary: "Geçmişin geçmişi: İki geçmiş olaydan önce olanı (had V3). By the time, before, after uyumu.",
  },
  {
    slug: "past-perfect-continuous",
    title: "Past Perfect Continuous",
    emoji: "⏳",
    category: "tenses",
    level: "B2 → YDS",
    summary: "Geçmişteki bir referans noktasına kadar belli bir süre kesintisiz sürmüş süreçler.",
  },
  {
    slug: "simple-future",
    title: "Simple Future (will)",
    emoji: "🔮",
    category: "tenses",
    level: "A1 → YDS",
    summary: "Anlık kararlar, tahminler, vaatler ve şart cümlelerinin temel sonuç yapıları.",
  },
  {
    slug: "be-going-to",
    title: "Be Going To & Planlar",
    emoji: "🗓️",
    category: "tenses",
    level: "A1 → YDS",
    summary: "Önceden planlanmış niyetler ve mevcut kanıtlara dayanan kesin gelecek tahminleri.",
  },
  {
    slug: "future-continuous",
    title: "Future Continuous",
    emoji: "🛫",
    category: "tenses",
    level: "B1 → YDS",
    summary: "Gelecekte belirli bir zaman diliminde devam ediyor olacak eylemler (this time next year).",
  },
  {
    slug: "future-perfect",
    title: "Future Perfect",
    emoji: "🏁",
    category: "tenses",
    level: "B2 → YDS",
    summary: "Gelecekteki belirli bir ana kadar tamamlanmış olacak eylemler (by 2030, by the end of this century).",
  },

  // ===== DİĞER TÜM YDS KONULARI =====
  {
    slug: "passive-voice",
    title: "Passive Voice (Edilgen Çatı)",
    emoji: "🔄",
    category: "structures",
    level: "A2 → YDS",
    summary: "Eylemi yapan değil etkilenen ön plandadır (be + V3). Akademik YDS metinlerinin %40'ı passive'dir.",
  },
  {
    slug: "modals",
    title: "Modals (can, must, should...)",
    emoji: "🎛️",
    category: "structures",
    level: "A2 → YDS",
    summary: "Yetenek, zorunluluk, olasılık, tavsiye ve çıkarım kipleri.",
  },
  {
    slug: "modals-perfect",
    title: "Perfect Modals (must have V3...)",
    emoji: "🕰️",
    category: "structures",
    level: "B2 → YDS",
    summary: "Geçmişe yönelik kesin çıkarımlar, pişmanlıklar ve imkânsızlıklar (could have, should have).",
  },
  {
    slug: "conditionals",
    title: "If Clauses (Type 0-1-2-3 + Mixed)",
    emoji: "🔀",
    category: "structures",
    level: "B1 → YDS",
    summary: "Gerçek ve varsayımsal şartlar, zaman kaymaları ve devrik (inverted) if yapıları.",
  },
  {
    slug: "wish-clauses",
    title: "Wish / If Only",
    emoji: "🌠",
    category: "structures",
    level: "B1 → YDS",
    summary: "Şu an veya geçmiş için gerçekleşmemiş dilekler, hayıflanmalar ve zaman bir derece geri alma kuralı.",
  },
  {
    slug: "reported-speech",
    title: "Reported Speech (Dolaylı Anlatım)",
    emoji: "🗣️",
    category: "structures",
    level: "B1 → YDS",
    summary: "Başkalarının sözlerini aktarma, zaman geri kayması (backshift) ve zaman zarfı dönüşümleri.",
  },
  {
    slug: "relative-clauses",
    title: "Relative Clauses (who, which...)",
    emoji: "🔗",
    category: "clauses",
    level: "B1 → YDS",
    summary: "İsimleri niteleyen sıfat cümlecikleri, preposition + which yapıları ve kısaltmalar.",
  },
  {
    slug: "noun-clauses",
    title: "Noun Clauses (that, whether...)",
    emoji: "📦",
    category: "clauses",
    level: "B2 → YDS",
    summary: "Cümlenin öznesi veya nesnesi olan isim cümlecikleri (that vs whether, wh- questions).",
  },
  {
    slug: "adverbial-clauses",
    title: "Adverbial Clauses (when, although...)",
    emoji: "🧭",
    category: "clauses",
    level: "B1 → YDS",
    summary: "Zaman, sebep, zıtlık, amaç ve sonuç bildiren zarf cümlecikleri.",
  },
  {
    slug: "gerund-infinitive",
    title: "Gerund & Infinitive (V-ing / to V)",
    emoji: "⚖️",
    category: "structures",
    level: "A2 → YDS",
    summary: "Fiilden sonra isimleşme kuralları, anlam değiştiren fiiller (remember, stop, forget).",
  },
  {
    slug: "conjunctions",
    title: "Bağlaçlar & Geçiş İfadeleri",
    emoji: "🌁",
    category: "clauses",
    level: "B2 → YDS",
    summary: "Zıtlık (although/however), sebep (because/therefore), ekleme (moreover) ve ikili bağlaçlar (not only.. but also).",
  },
  {
    slug: "prepositions",
    title: "Prepositions & Phrasal Collocations",
    emoji: "📍",
    category: "structures",
    level: "B1 → YDS",
    summary: "Edatlar ve kalıplaşmış isim/fiil edat eşleşmeleri (responsible FOR, contribute TO).",
  },
  {
    slug: "comparatives",
    title: "Comparatives & Superlatives",
    emoji: "📊",
    category: "structures",
    level: "A2 → YDS",
    summary: "Karşılaştırma, üstünlük, the more... the more ve paralel artış kalıpları.",
  },
  {
    slug: "articles-quantifiers",
    title: "Articles & Quantifiers (a/an/the, much/many)",
    emoji: "🔢",
    category: "structures",
    level: "A2 → YDS",
    summary: "Belirteçler, sayılabilen/sayılamayan isimler, a few vs few, each, every, none.",
  },
  {
    slug: "participles-inversion",
    title: "Participles & Inversion (İleri Yapılar)",
    emoji: "🎓",
    category: "advanced",
    level: "C1 → YDS",
    summary: "Zarf ve sıfat kısaltmaları (Having V3), devrik cümleler (Not only..., Hardly... when).",
  },
] as const;

export * from "@/data/grammar-curriculum";
