export interface YdsQuestionType {
  id: string;
  nameTr: string;
  nameEn: string;
  questionRange: string;
  count: number;
  color: string;
  bgGradient: string;
  tacticSummary: string;
  keyStrategy: string;
  icon: string;
}

export const YDS_QUESTION_TYPES: YdsQuestionType[] = [
  {
    id: "vocabulary",
    nameTr: "Kelime Bilgisi (İsim, Sıfat, Zarf, Fiil, Phrasal)",
    nameEn: "Vocabulary",
    questionRange: "1 - 6",
    count: 6,
    color: "from-amber-500 to-orange-600",
    bgGradient: "bg-gradient-to-br from-amber-500/20 to-orange-600/20 border-amber-500/40",
    tacticSummary: "Cümlenin bağlamına, olumlu/olumsuz duygu durumuna ve edat (preposition) eşleşmelerine dikkat et.",
    keyStrategy: "Boşluğun sağındaki edat doğrudan doğru cevabı verebilir: 'cope WITH', 'rely ON', 'result IN'.",
    icon: "📚",
  },
  {
    id: "grammar",
    nameTr: "Dilbilgisi (Tense, Modals, Passive, Conjunction)",
    nameEn: "Grammar & Structure",
    questionRange: "7 - 16",
    count: 10,
    color: "from-purple-500 to-indigo-600",
    bgGradient: "bg-gradient-to-br from-purple-500/20 to-indigo-600/20 border-purple-500/40",
    tacticSummary: "Zaman uyumu kuralını uygula: Present ile Past genelde karışmaz (since hariç).",
    keyStrategy: "Zaman zarflarına (by the time, since, ago, recently) odaklanarak şıkları 2'ye indir.",
    icon: "⚙️",
  },
  {
    id: "cloze",
    nameTr: "Cloze Test (Paragraf İçi Boşluk Doldurma)",
    nameEn: "Cloze Test",
    questionRange: "17 - 26",
    count: 10,
    color: "from-blue-500 to-cyan-600",
    bgGradient: "bg-gradient-to-br from-blue-500/20 to-cyan-600/20 border-blue-500/40",
    tacticSummary: "Boşluğun bulunduğu cümlenin öncesini ve sonrasını mutlaka bir bütün olarak oku.",
    keyStrategy: "Bağlaç sorularında iki cümle arasındaki artı/eksi (sebep, zıtlık, paralel) ilişkisini tespit et.",
    icon: "🧩",
  },
  {
    id: "sentence-completion",
    nameTr: "Cümle Tamamlama",
    nameEn: "Sentence Completion",
    questionRange: "27 - 36",
    count: 10,
    color: "from-teal-500 to-emerald-600",
    bgGradient: "bg-gradient-to-br from-teal-500/20 to-emerald-600/20 border-teal-500/40",
    tacticSummary: "Özne takibi yap! Verilen cümlenin öznesi ile tamamlayan cümlenin zamiri (pronoun) uyuşmalıdır.",
    keyStrategy: "Zıtlık bağlacı (although, whereas, while) varsa karşı tarafta zıt bir sıfat veya durum ara.",
    icon: "🔗",
  },
  {
    id: "translation",
    nameTr: "Çeviri (İngilizce ↔ Türkçe)",
    nameEn: "Translation",
    questionRange: "37 - 42",
    count: 6,
    color: "from-green-500 to-lime-600",
    bgGradient: "bg-gradient-to-br from-green-500/20 to-lime-600/20 border-green-500/40",
    tacticSummary: "YDS'nin en yüksek net getiren bölümüdür. Önce ASIL YÜKLEMİ ve ASIL ÖZNEYİ bul.",
    keyStrategy: "Yüklemi doğru olan şıklar genelde 1 veya 2 tanedir. 10 saniyede elenebilir.",
    icon: "🌐",
  },
  {
    id: "reading",
    nameTr: "Paragraf / Okuma Parçaları (5 Metin x 4 Soru)",
    nameEn: "Reading Comprehension",
    questionRange: "43 - 62",
    count: 20,
    color: "from-yellow-500 to-amber-600",
    bgGradient: "bg-gradient-to-br from-yellow-500/20 to-amber-600/20 border-yellow-500/40",
    tacticSummary: "Önce soru köklerini hızlıca tara, sonra metni oku. Metinde geçmeyen aşırı genellemelerden (all, only, never) kaçın.",
    keyStrategy: "Doğru cevap çoğunlukla metindeki ifadenin eş anlamlı sözcüklerle yeniden yazılmış (paraphrase) halidir.",
    icon: "📖",
  },
  {
    id: "dialogue",
    nameTr: "Diyalog Tamamlama",
    nameEn: "Dialogue Completion",
    questionRange: "63 - 67",
    count: 5,
    color: "from-orange-500 to-rose-600",
    bgGradient: "bg-gradient-to-br from-orange-500/20 to-rose-600/20 border-orange-500/40",
    tacticSummary: "Boşluktan hemen sonraki konuşmacının tepkisine (şaşırma, onaylama, itiraz) dikkat et.",
    keyStrategy: "Sonraki cümle 'I completely agree' diyorsa, boşlukta bir fikir veya öneri olmalıdır.",
    icon: "💬",
  },
  {
    id: "restatement",
    nameTr: "Anlamca En Yakın Cümle (Restatement)",
    nameEn: "Restatement",
    questionRange: "68 - 71",
    count: 4,
    color: "from-rose-500 to-pink-600",
    bgGradient: "bg-gradient-to-br from-rose-500/20 to-pink-600/20 border-rose-500/40",
    tacticSummary: "Ana cümledeki koşul, neden, derece (more, most, as...as) ve modal öğelerini işaretle.",
    keyStrategy: "Orijinal cümlede olmayan ekstra bir kesinlik veya genelleme içeren şıkları doğrudan ele.",
    icon: "🔄",
  },
  {
    id: "paragraph-completion",
    nameTr: "Paragraf Tamamlama",
    nameEn: "Paragraph Completion",
    questionRange: "72 - 75",
    count: 4,
    color: "from-fuchsia-500 to-purple-600",
    bgGradient: "bg-gradient-to-br from-fuchsia-500/20 to-purple-600/20 border-fuchsia-500/40",
    tacticSummary: "Boşluğun önündeki ve arkasındaki cümleyle anlamsal bir köprü kur. İşaret zamirlerine (this, these, such) bak.",
    keyStrategy: "Boşluktan sonra 'For instance' geliyorsa, boşluğa bir kural veya genel yargı yerleştirilmelidir.",
    icon: "🧱",
  },
  {
    id: "irrelevant",
    nameTr: "Anlam Bütünlüğünü Bozan Cümle",
    nameEn: "Irrelevant Sentence",
    questionRange: "76 - 80",
    count: 5,
    color: "from-violet-500 to-indigo-700",
    bgGradient: "bg-gradient-to-br from-violet-500/20 to-indigo-700/20 border-violet-500/40",
    tacticSummary: "Tüm cümlelerin ana konusunu ve öznesini çıkar. Bir cümle konudan sapmışsa veya çok özele/genele inmişse o bozar.",
    keyStrategy: "Şüpheli cümleyi atıp önceki ve sonraki cümleyi art arda oku; anlam pürüzsüz akıyorsa doğru tespit ettin.",
    icon: "❌",
  },
];
