// Badges Data Specification for YDS Master

export type BadgeCategory =
  | "starter"
  | "vocabulary"
  | "grammar"
  | "reading"
  | "exam"
  | "level"
  | "streak"
  | "program"
  | "secret";

export type BadgeRarity = "common" | "rare" | "epic" | "legendary";

export interface BadgeDefinition {
  id: string;
  title: string;
  description: string;
  category: BadgeCategory;
  rarity: BadgeRarity;
  icon: string;
  rewardXp: number;
  hidden?: boolean;
  progressLabel: string;
  targetCount: number;
  wittyPraise: string;
  animationType: "books" | "puzzle" | "glasses" | "pencil" | "fire" | "crown" | "eraser" | "calendar" | "owl" | "alarm";
}

export interface EarnedBadge {
  badgeId: string;
  earnedAt: number;
  awardEventId: string;
  seen: boolean;
}

export interface BadgeState {
  version: number;
  earned: EarnedBadge[];
  progress: Record<string, number>;
}

export function defaultBadgeState(): BadgeState {
  return {
    version: 1,
    earned: [],
    progress: {},
  };
}

export const RARITY_COLORS: Record<BadgeRarity, { border: string; bg: string; text: string; glow: string }> = {
  common: {
    border: "border-sky-500/40",
    bg: "bg-gradient-to-br from-slate-900 via-sky-950/40 to-slate-900",
    text: "text-sky-400",
    glow: "shadow-sky-500/20",
  },
  rare: {
    border: "border-indigo-500/50",
    bg: "bg-gradient-to-br from-slate-900 via-indigo-950/50 to-slate-900",
    text: "text-indigo-400",
    glow: "shadow-indigo-500/30",
  },
  epic: {
    border: "border-fuchsia-500/60",
    bg: "bg-gradient-to-br from-slate-900 via-fuchsia-950/60 to-slate-900",
    text: "text-fuchsia-400",
    glow: "shadow-fuchsia-500/40",
  },
  legendary: {
    border: "border-amber-400/80",
    bg: "bg-gradient-to-br from-slate-900 via-amber-950/60 to-red-950/40",
    text: "text-amber-300",
    glow: "shadow-amber-500/50",
  },
};

export const BADGES: BadgeDefinition[] = [
  // 1. Başlangıç (1-3)
  {
    id: "first-step",
    title: "İlk Adım",
    description: "Profili ve seviye testini tamamla, en az bir çalışma programı seç.",
    category: "starter",
    rarity: "common",
    icon: "🚀",
    rewardXp: 50,
    progressLabel: "Başlangıç adımları",
    targetCount: 3,
    wittyPraise: "Kanka, ilk adımı attın ya, gerisi çorap söküğü gibi gelecek! Hoş geldin aramıza! 🚀",
    animationType: "puzzle",
  },
  {
    id: "warmup-tour",
    title: "Isınma Turu",
    description: "Üç farklı modülü kullan ve aynı gün en az 30 dakika aktif çalış.",
    category: "starter",
    rarity: "common",
    icon: "⚡",
    rewardXp: 40,
    progressLabel: "Çalışma dakikası",
    targetCount: 30,
    wittyPraise: "Motorlar ısındı! 30 dakika boyunca sistemi salladın kral. 🔥",
    animationType: "fire",
  },
  {
    id: "map-unlocked",
    title: "Haritayı Açtım",
    description: "Kelime, gramer, reading, tactics ve exams sayfalarını ziyaret edip etkinlik tamamla.",
    category: "starter",
    rarity: "common",
    icon: "🗺️",
    rewardXp: 60,
    progressLabel: "Keşfedilen modüller",
    targetCount: 5,
    wittyPraise: "Sistemin haritasını tamamen açtın kanka! Artık hiçbir soru senden kaçamaz. 🧭",
    animationType: "puzzle",
  },

  // 2. Kelime (4-9)
  {
    id: "vocab-collector",
    title: "Kelime Toplayıcısı",
    description: "100 farklı kelime üzerinde en az %70 doğrulukla çalış.",
    category: "vocabulary",
    rarity: "common",
    icon: "🧺",
    rewardXp: 60,
    progressLabel: "Öğrenilen kelimeler",
    targetCount: 100,
    wittyPraise: "İlk 100 kelime sepette! Beyin lobların yeni kelimelere yer açmaya bayılıyor. 📚",
    animationType: "books",
  },
  {
    id: "vocab-hunter",
    title: "Kelime Avcısı",
    description: "500 farklı kelimeyi en az 14 farklı çalışma gününde %75 doğrulukla tamamla.",
    category: "vocabulary",
    rarity: "rare",
    icon: "🏹",
    rewardXp: 120,
    progressLabel: "Öğrenilen kelimeler",
    targetCount: 500,
    wittyPraise: "500 kelime avlandı! YDS sözlüğü senin önünde diz çökecek kanka. 🎯",
    animationType: "books",
  },
  {
    id: "vocab-master",
    title: "Kelime Ustası",
    description: "1.000 farklı kelime üzerinde en az 30 farklı çalışma gününde %80 doğruluk sağla.",
    category: "vocabulary",
    rarity: "epic",
    icon: "🧙‍♂️",
    rewardXp: 250,
    progressLabel: "Öğrenilen kelimeler",
    targetCount: 1000,
    wittyPraise: "Kanka, 1.000 kelime ne demek! Oxford sözlüğü seni ortak yazarlığa çağırabilir! 🧠",
    animationType: "crown",
  },
  {
    id: "academic-lexicon",
    title: "Akademik Sözlük",
    description: "500 akademik ve YDS kelimesinde aralıklı tekrarda en az iki başarılı geri çağırma yap.",
    category: "vocabulary",
    rarity: "epic",
    icon: "📖",
    rewardXp: 200,
    progressLabel: "Akademik kelimeler",
    targetCount: 500,
    wittyPraise: "Akademik literatürün şifresi sende artık. Makaleler düşünsün! ✨",
    animationType: "books",
  },
  {
    id: "unforgetting-elephant",
    title: "Unutmayan Fil",
    description: "250 kelimeyi ilk öğrenmeden 30 gün sonra aralıklı tekrarda hatasız hatırla.",
    category: "vocabulary",
    rarity: "rare",
    icon: "🐘",
    rewardXp: 150,
    progressLabel: "Kalıcı kelimeler",
    targetCount: 250,
    wittyPraise: "Fil hafızası falan hikaye, senin nöronlar resmen çelik kasa! 30 gün sonra bile tıkır tıkır! 🐘",
    animationType: "books",
  },
  {
    id: "phrasal-verb-monster",
    title: "Phrasal Verb Canavarı",
    description: "150 farklı phrasal verb üzerinde en az %80 doğruluk sağla.",
    category: "vocabulary",
    rarity: "rare",
    icon: "🧗",
    rewardXp: 140,
    progressLabel: "Phrasal Verbler",
    targetCount: 150,
    wittyPraise: "Turn down, look up, get over... Hepsini tek lokmada yuttun canavar kanka! 💥",
    animationType: "books",
  },

  // 3. Gramer (10-15)
  {
    id: "time-traveler",
    title: "Zaman Yolcusu",
    description: "Bütün temel tense konularını tamamla ve testlerinden en az %75 al.",
    category: "grammar",
    rarity: "common",
    icon: "⏳",
    rewardXp: 80,
    progressLabel: "Tamamlanan zamanlar",
    targetCount: 17,
    wittyPraise: "Geçmiş, şimdi, gelecek... Zaman çizgisi parmaklarının ucunda dans ediyor kanka! ⏳",
    animationType: "puzzle",
  },
  {
    id: "perfect-detective",
    title: "Perfect Dedektifi",
    description: "Present, Past ve Future Perfect testlerinde farklı günlerde iki kez %80+ al.",
    category: "grammar",
    rarity: "rare",
    icon: "🔍",
    rewardXp: 120,
    progressLabel: "Başarılı perfect testleri",
    targetCount: 6,
    wittyPraise: "Have V3 ve had V3 tuzakları dedektif kankamıza sökmez! Şerlok görse ceketini ilikler. 🕵️‍♂️",
    animationType: "puzzle",
  },
  {
    id: "modal-master",
    title: "Modal Ustası",
    description: "Modals ve Perfect Modals testlerinde en az 100 farklı soruda %85 doğruluk elde et.",
    category: "grammar",
    rarity: "rare",
    icon: "🎛️",
    rewardXp: 130,
    progressLabel: "Çözülen modal soruları",
    targetCount: 100,
    wittyPraise: "Must have V3, should have V3 derken modalların efendisi oldun! 🎛️",
    animationType: "puzzle",
  },
  {
    id: "clause-architect",
    title: "Clause Mimarı",
    description: "Relative ve Adverbial Clause testlerinde 150 soruda en az %80 başarı sağla.",
    category: "grammar",
    rarity: "rare",
    icon: "🏛️",
    rewardXp: 150,
    progressLabel: "Clause soruları",
    targetCount: 150,
    wittyPraise: "Hangi cümlenin kimi nitelediğini mimar titizliğiyle çiziyorsun kral! 🏛️",
    animationType: "puzzle",
  },
  {
    id: "inversion-king",
    title: "Devrik Kral",
    description: "Inversion testinde en az 90/100 ve karışık testte %85+ doğruluk sağla.",
    category: "grammar",
    rarity: "epic",
    icon: "🔃",
    rewardXp: 200,
    progressLabel: "Inversion doğruluğu",
    targetCount: 50,
    wittyPraise: "Hardly had you started when you conquered! Cümleyi devirip krallığını kurdun kanka! 👑",
    animationType: "crown",
  },
  {
    id: "grammar-marathoner",
    title: "Gramer Maratoncusu",
    description: "En az 1.000 benzersiz gramer sorusunda genel doğruluk oranını %80 üzerinde tut.",
    category: "grammar",
    rarity: "epic",
    icon: "🏃‍♂️",
    rewardXp: 300,
    progressLabel: "Çözülen gramer soruları",
    targetCount: 1000,
    wittyPraise: "1.000 gramer sorusu! Bu azimle YDS'de gramer soruları sana soru soramaz, sen onları çözersin! 🏅",
    animationType: "pencil",
  },

  // 4. Reading (16-20)
  {
    id: "paragraph-explorer",
    title: "Paragraf Kaşifi",
    description: "25 farklı reading metnini tamamlayıp sorularda en az %70 başarı sağla.",
    category: "reading",
    rarity: "common",
    icon: "🔭",
    rewardXp: 70,
    progressLabel: "Okunan metinler",
    targetCount: 25,
    wittyPraise: "Paragrafların derinliklerine indin ve hazineyi buldun kanka! 🔭",
    animationType: "glasses",
  },
  {
    id: "reading-runner",
    title: "Reading Koşucusu",
    description: "100 farklı metni en az 20 farklı çalışma gününde %75 başarıyla tamamla.",
    category: "reading",
    rarity: "rare",
    icon: "🏃‍♀️",
    rewardXp: 180,
    progressLabel: "Okunan metinler",
    targetCount: 100,
    wittyPraise: "100 akademik metin devrildi! Gözler hızlandı, anlama tavan yaptı! 🏃‍♂️",
    animationType: "glasses",
  },
  {
    id: "academic-reader",
    title: "Akademik Okur",
    description: "B2–C1 seviyesinde 150 metinde en az %80 başarı sağla.",
    category: "reading",
    rarity: "epic",
    icon: "🧐",
    rewardXp: 250,
    progressLabel: "İleri seviye metinler",
    targetCount: 150,
    wittyPraise: "Nature ve Science makaleleri bile senin karşında hafif kalır kanka! 🧐",
    animationType: "glasses",
  },
  {
    id: "inference-detective",
    title: "Satır Arası Dedektifi",
    description: "100 çıkarım ve yazarın tutumu sorusunda en az %85 doğruluk sağla.",
    category: "reading",
    rarity: "epic",
    icon: "🔎",
    rewardXp: 220,
    progressLabel: "Çıkarım soruları",
    targetCount: 100,
    wittyPraise: "Yazarın ne demek istediğini yazar daha yazmadan anlıyorsun! Müthiş sezgi! 🕵️",
    animationType: "glasses",
  },
  {
    id: "reading-500-library",
    title: "500’lük Kütüphane",
    description: "Sistemdeki 500 okuma metni ve etkinliğini en az %75 başarıyla tamamla.",
    category: "reading",
    rarity: "legendary",
    icon: "📚",
    rewardXp: 500,
    progressLabel: "Tamamlanan metinler",
    targetCount: 500,
    wittyPraise: "İskenderiye kütüphanesini yeniden kurdun kanka! Saygıyla eğiliyoruz! 🏛️👑",
    animationType: "crown",
  },

  // 5. Sınav (21-26)
  {
    id: "first-mock",
    title: "İlk Deneme",
    description: "İlk 80 soruluk denemeyi tamamla ve en az 30 net çıkar.",
    category: "exam",
    rarity: "common",
    icon: "🎯",
    rewardXp: 80,
    progressLabel: "Net sayısı",
    targetCount: 30,
    wittyPraise: "180 dakikalık maratonda ter döktün ve ilk tabelanı diktin kanka! Tebrikler! ⏱️",
    animationType: "pencil",
  },
  {
    id: "time-hunter",
    title: "Süre Avcısı",
    description: "80 soruluk denemeyi süre içinde bitirip en az 55 net yap.",
    category: "exam",
    rarity: "rare",
    icon: "⏱️",
    rewardXp: 150,
    progressLabel: "Net sayısı",
    targetCount: 55,
    wittyPraise: "Zamanla yarıştın ve kazandın! 55+ net cebinde, süre kontrolü sende! ⚡",
    animationType: "pencil",
  },
  {
    id: "club-70",
    title: "70 Kulübü",
    description: "Üç farklı tam denemede en az 70 net çıkar.",
    category: "exam",
    rarity: "epic",
    icon: "🥉",
    rewardXp: 300,
    progressLabel: "70+ netli denemeler",
    targetCount: 3,
    wittyPraise: "70 barajı aşıldı! Artık lisansüstü kapıları ardına kadar açık kanka! 🏆",
    animationType: "crown",
  },
  {
    id: "club-80",
    title: "80 Kulübü",
    description: "Beş farklı tam denemede en az 80 net yap.",
    category: "exam",
    rarity: "epic",
    icon: "🥈",
    rewardXp: 450,
    progressLabel: "80+ netli denemeler",
    targetCount: 5,
    wittyPraise: "80 net mi?! Kanka sen sınava hazırlanmıyorsun, sınav senin için hazırlanıyor! 🚀",
    animationType: "crown",
  },
  {
    id: "consistency-machine",
    title: "İstikrar Makinesi",
    description: "Son beş farklı tam denemenin ortalaması en az 75 net olsun, hiçbiri 65 altına inmesin.",
    category: "exam",
    rarity: "epic",
    icon: "⚙️",
    rewardXp: 400,
    progressLabel: "İstikrarlı denemeler",
    targetCount: 5,
    wittyPraise: "İsviçre saati gibi çalışıyorsun! Şans değil, saf disiplin ve bilgi! ⚙️",
    animationType: "pencil",
  },
  {
    id: "error-bender",
    title: "Hata Bükücü",
    description: "Daha önce yanlış yapılan 250 farklı soruyu daha sonra doğru cevapla.",
    category: "exam",
    rarity: "rare",
    icon: "🥋",
    rewardXp: 180,
    progressLabel: "Düzeltilen yanlışlar",
    targetCount: 250,
    wittyPraise: "Hatalarından ders çıkaran yenilmez olur! Hataları büküp güce çevirdin! 🥋",
    animationType: "eraser",
  },

  // 6. Seviye (27-31)
  {
    id: "gate-a2",
    title: "A2 Kapısı",
    description: "Seviye testinde A2 seviyesine ulaş ve doğrulama testinde eşiği geç.",
    category: "level",
    rarity: "common",
    icon: "🌱",
    rewardXp: 100,
    progressLabel: "A2 Doğrulama",
    targetCount: 1,
    wittyPraise: "A1 geride kaldı, A2 kapısından girdin! Adımların sağlam kanka! 🌱",
    animationType: "puzzle",
  },
  {
    id: "traveler-b1",
    title: "B1 Yolcusu",
    description: "Seviye testinde B1 sonucu al, grammar ve reading eşiklerini geç.",
    category: "level",
    rarity: "rare",
    icon: "🚀",
    rewardXp: 180,
    progressLabel: "B1 Doğrulama",
    targetCount: 1,
    wittyPraise: "B1 seviyesi açıldı! Artık bağımsız bir dil kullanıcısısın, YDS rotası netleşti! 🚀",
    animationType: "fire",
  },
  {
    id: "climber-b2",
    title: "B2 Tırmanıcısı",
    description: "Seviye testinde en az orta/yüksek güvenle B2 sonucu elde et.",
    category: "level",
    rarity: "epic",
    icon: "🧗‍♂️",
    rewardXp: 300,
    progressLabel: "B2 Doğrulama",
    targetCount: 1,
    wittyPraise: "B2 zirvesine tırmandın! Akademik İngilizce kapılarını sana açtı kanka! 🧗‍♂️",
    animationType: "crown",
  },
  {
    id: "summit-c1",
    title: "C1 Zirvesi",
    description: "C1 sonucu al, doğrulama testini geç ve en az üç beceri alanında C1 eşiğine ulaş.",
    category: "level",
    rarity: "epic",
    icon: "👑",
    rewardXp: 450,
    progressLabel: "C1 Doğrulama",
    targetCount: 1,
    wittyPraise: "C1 Zirvesi! Kanka resmen ligin en tepesine demir attın! Muazzam başarı! 👑",
    animationType: "crown",
  },
  {
    id: "legend-c2",
    title: "C2 Efsanesi",
    description: "C2 sonucu, yüksek güven, doğrulama testi ve tutarlı performans ile efsaneleş.",
    category: "level",
    rarity: "legendary",
    icon: "🌟",
    rewardXp: 750,
    progressLabel: "C2 Efsane Doğrulama",
    targetCount: 1,
    wittyPraise: "C2 Efsanesi! Ana dili İngilizce olanlar bile senden tüyo alabilir. Zirvenin tek sahibisin! 🌟👑",
    animationType: "crown",
  },

  // 7. Seri ve Disiplin (32-35)
  {
    id: "here-for-a-week",
    title: "Bir Haftadır Buradayım",
    description: "7 farklı gün, günlük en az 20 dakika aktif çalışma tamamla.",
    category: "streak",
    rarity: "common",
    icon: "📅",
    rewardXp: 100,
    progressLabel: "Çalışma günleri",
    targetCount: 7,
    wittyPraise: "7 gün boyunca her gün buradaydın! Disiplin dediğin böyle olur! 📅",
    animationType: "calendar",
  },
  {
    id: "became-habit",
    title: "Alışkanlık Oldu",
    description: "30 günlük seri boyunca her gün en az bir gerçek etkinlik tamamla.",
    category: "streak",
    rarity: "rare",
    icon: "🔥",
    rewardXp: 300,
    progressLabel: "Seri gün sayısı",
    targetCount: 30,
    wittyPraise: "30 günlük seri! Artık ders çalışmıyorsun, İngilizce senin yaşam tarzın oldu kral! 🔥",
    animationType: "fire",
  },
  {
    id: "iron-discipline",
    title: "Demir Disiplin",
    description: "90 günlük dönemin en az 75 gününde çalış, toplam en az 75 saat tamamla.",
    category: "streak",
    rarity: "epic",
    icon: "🛡️",
    rewardXp: 500,
    progressLabel: "Tamamlanan saatler",
    targetCount: 75,
    wittyPraise: "Demir disiplin! Çelik gibi iradenin önünde hiçbir YDS sorusu duramaz! 🛡️",
    animationType: "fire",
  },
  {
    id: "marathoner",
    title: "Maratoncu",
    description: "180 günlük dönemin en az 140 gününde çalış, toplam en az 150 saat tamamla.",
    category: "streak",
    rarity: "legendary",
    icon: "🏃‍♂️",
    rewardXp: 1000,
    progressLabel: "Tamamlanan saatler",
    targetCount: 150,
    wittyPraise: "150 saatlik dev maraton! Bu azim tarihi baştan yazar. Tebrikler şampiyon! 🏅🌟",
    animationType: "crown",
  },

  // 8. Program ve Gizli (36 + Gizli)
  {
    id: "planned-programmed",
    title: "Planlı Programlı",
    description: "30 günlük çalışma programının en az %90'ını eksiksiz tamamla.",
    category: "program",
    rarity: "rare",
    icon: "📋",
    rewardXp: 200,
    progressLabel: "Tamamlanan plan günleri",
    targetCount: 27,
    wittyPraise: "Plana sadık kaldın ve zafere ulaştın! Programlı çalışan öğrenci yenilmezdir. 📋",
    animationType: "calendar",
  },
  {
    id: "comma-police",
    title: "Comma Police",
    description: "Virgül ve bağlaç taktiklerinde 30 soruda sıfır hata yap.",
    category: "secret",
    rarity: "rare",
    icon: "👮‍♂️",
    rewardXp: 100,
    hidden: true,
    progressLabel: "Hatasız virgül soruları",
    targetCount: 30,
    wittyPraise: "Virgülün yerini bir santim bile kaydıramazlar! Comma Police görev başında! 👮",
    animationType: "pencil",
  },
  {
    id: "ago-v2",
    title: "Ago Geldi V2’ye Sarıldım",
    description: "Simple Past ve zaman zarfları sorularında ardışık 20 doğru cevap ver.",
    category: "secret",
    rarity: "rare",
    icon: "🔙",
    rewardXp: 100,
    hidden: true,
    progressLabel: "Ardışık doğru sayısı",
    targetCount: 20,
    wittyPraise: "Cümlede 'ago'yu gördün, V2'yi yapıştırdın! YDS taktikleri damarlarında akıyor! 😂",
    animationType: "puzzle",
  },
  {
    id: "despite-master",
    title: "Despite’tan Sonra Cümle Yazmadım",
    description: "Preposition ve bağlaç ayrımı sorularında 30 doğru yap.",
    category: "secret",
    rarity: "rare",
    icon: "🛡️",
    rewardXp: 100,
    hidden: true,
    progressLabel: "Bağlaç soruları",
    targetCount: 30,
    wittyPraise: "ÖSYM tuzak kurdu ama sen 'Despite + Noun' kuralını asla unutmadın! Helal! 🛡️",
    animationType: "puzzle",
  },
  {
    id: "no-sooner-than",
    title: "No Sooner Than Kankası",
    description: "Inversion ve zaman bağlacı sorularında 25 doğru yap.",
    category: "secret",
    rarity: "epic",
    icon: "⚡",
    rewardXp: 150,
    hidden: true,
    progressLabel: "Inversion doğruları",
    targetCount: 25,
    wittyPraise: "No sooner had you seen the question than you marked the right answer! Müthiş! ⚡",
    animationType: "crown",
  },
  {
    id: "night-owl",
    title: "Gece Kuşu",
    description: "Gece 23:00 ile 04:00 saatleri arasında 5 farklı gün aktif çalış.",
    category: "secret",
    rarity: "common",
    icon: "🦉",
    rewardXp: 75,
    hidden: true,
    progressLabel: "Gece çalışmaları",
    targetCount: 5,
    wittyPraise: "Herkes uyurken sen İngilizceyle fısıldaşıyordun. Sessiz sedasız zirveye! 🦉🌙",
    animationType: "owl",
  },
  {
    id: "early-bird",
    title: "Sabahın Grameri",
    description: "Sabah 05:00 ile 08:00 saatleri arasında 5 farklı gün aktif çalış.",
    category: "secret",
    rarity: "common",
    icon: "🌅",
    rewardXp: 75,
    hidden: true,
    progressLabel: "Sabah çalışmaları",
    targetCount: 5,
    wittyPraise: "Kuşlar bile uyanmadan gramer çözen şampiyon! Sabah bereketi netlerine yansısın! 🌅☕",
    animationType: "alarm",
  },
];
