// ============================================================
// src/lib/certificates/data.ts
// YDS Master — Seviye Sertifika Tanımları & Seviye Atlama Soruları
// ============================================================

import { CertificateDefinition, CertificateLevel, LevelUpQuizQuestion } from "./types";

export const CERTIFICATE_DEFINITIONS: Record<CertificateLevel, CertificateDefinition> = {
  A1: {
    level: "A1",
    title: "A1 Başlangıç Seviyesi Bitirme Sertifikası",
    subtitle: "Elementary English Foundations Certificate",
    cefrRank: "Başlangıç (Beginner / Çaylak)",
    badgeEmoji: "🌱",
    theme: {
      border: "border-emerald-500/50",
      accent: "#10b981",
      badgeBg: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
      textGradient: "from-emerald-400 via-teal-300 to-cyan-400",
      sealColor: "#059669",
    },
    skillsLearned: [
      "Temel İngilizce cümle sırası (SVO)",
      "Simple Present & Past Tense kullanımı",
      "Günlük 100+ temel kelime ve zamirler",
      "Temel zaman zarfları ve sıfatlar",
    ],
    requirements: {
      minXp: 120,
      minWords: 30,
      minGrammar: 2,
      examPassingScore: 70,
    },
    descriptionTr: "Öğrenci temel İngilizce cümle kurma kurallarını, basit zaman kiplerini ve başlangıç seviyesi kelime dağarcığını başarıyla tamamlamıştır.",
  },
  A2: {
    level: "A2",
    title: "A2 Temel Düzey Bitirme Sertifikası",
    subtitle: "Pre-Intermediate English Proficiency Certificate",
    cefrRank: "Temel Seviye (Elementary / Kaşif)",
    badgeEmoji: "🌿",
    theme: {
      border: "border-lime-500/50",
      accent: "#84cc16",
      badgeBg: "bg-lime-500/15 text-lime-400 border-lime-500/30",
      textGradient: "from-lime-400 via-emerald-300 to-teal-400",
      sealColor: "#65a30d",
    },
    skillsLearned: [
      "Zaman uyumu & geçmiş süreç bağlaçları (when/while)",
      "Karşılaştırma kalıpları (Comparatives & Superlatives)",
      "Gerund & Infinitive temelleri",
      "200+ akademik ve günlük kelime ayrımı",
    ],
    requirements: {
      minXp: 350,
      minWords: 75,
      minGrammar: 5,
      examPassingScore: 70,
    },
    descriptionTr: "Öğrenci zamanlar arası geçişleri, karşılaştırma yapılarını ve temel bağlaç mantığını başarıyla kavrayarak A2 düzeyini tamamlamıştır.",
  },
  B1: {
    level: "B1",
    title: "B1 Orta Düzey YDS Hazırlık Sertifikası",
    subtitle: "Intermediate Academic Foundations Certificate",
    cefrRank: "Orta Düzey (Intermediate / Gelişim)",
    badgeEmoji: "⚡",
    theme: {
      border: "border-sky-500/50",
      accent: "#0ea5e9",
      badgeBg: "bg-sky-500/15 text-sky-400 border-sky-500/30",
      textGradient: "from-sky-400 via-cyan-300 to-blue-400",
      sealColor: "#0284c7",
    },
    skillsLearned: [
      "Modal fiiller ve olasılık çıkarımları (must/might have V3)",
      "Relative Clauses (Sıfat cümlecikleri ve kısaltmalar)",
      "Akademik bağlaçlar (Although, Because, Therefore)",
      "Orta düzey metin kavrama ve çıkarım yapma",
    ],
    requirements: {
      minXp: 750,
      minWords: 150,
      minGrammar: 9,
      examPassingScore: 70,
    },
    descriptionTr: "Öğrenci YDS'nin temelini oluşturan modal çıkarımlarını, sıfat cümleciklerini ve akademik bağlaç stratejilerini başarıyla tamamlamıştır.",
  },
  B2: {
    level: "B2",
    title: "B2 İleri-Orta YDS Baraj Başarı Sertifikası",
    subtitle: "Upper-Intermediate Academic Mastery Certificate",
    cefrRank: "İleri-Orta (Upper-Intermediate / YDS Barajı)",
    badgeEmoji: "🔥",
    theme: {
      border: "border-purple-500/50",
      accent: "#a855f7",
      badgeBg: "bg-purple-500/15 text-purple-400 border-purple-500/30",
      textGradient: "from-purple-400 via-pink-300 to-indigo-400",
      sealColor: "#7e22ce",
    },
    skillsLearned: [
      "Zıtlık, sebep-sonuç ve ikili bağlaç kombinasyonları",
      "Noun Clauses & Dolaylı anlatım teknikleri",
      "Phrasal Verbs ve Collocation eşdizimleri",
      "Akademik okuma parçası analizi ve ana fikir tespiti",
    ],
    requirements: {
      minXp: 1400,
      minWords: 250,
      minGrammar: 13,
      examPassingScore: 70,
    },
    descriptionTr: "Öğrenci YDS'de 70+ hedefleyen kritik akademik kelimeleri, karmaşık bağlaç yapılarını ve okuma kavrama tekniklerini başarıyla tamamlamıştır.",
  },
  C1: {
    level: "C1",
    title: "C1 İleri Düzey Akademik Uzmanlık Sertifikası",
    subtitle: "Advanced English Proficiency & YDS Expert Certificate",
    cefrRank: "İleri Seviye (Advanced / YDS Ustası)",
    badgeEmoji: "💎",
    theme: {
      border: "border-fuchsia-500/50",
      accent: "#d946ef",
      badgeBg: "bg-fuchsia-500/15 text-fuchsia-400 border-fuchsia-500/30",
      textGradient: "from-fuchsia-400 via-pink-400 to-rose-400",
      sealColor: "#c026d3",
    },
    skillsLearned: [
      "Devrik cümle yapıları (Inversion & Negative Adverbials)",
      "Participle Clause kısaltmaları (Having been V3)",
      "Reader at Work tarzı ağır akademik metin çözümlemeleri",
      "Çeviri, Paragraf Tamamlama ve Akışı Bozan Cümle taktikleri",
    ],
    requirements: {
      minXp: 2200,
      minWords: 360,
      minGrammar: 17,
      examPassingScore: 70,
    },
    descriptionTr: "Öğrenci ileri düzey dilbilgisi tuzaklarını, karmaşık akademik metin yapılarını ve 80+ puan gerektiren YDS soru tiplerini ustalıkla çözmüştür.",
  },
  C2: {
    level: "C2",
    title: "C2 Üst Düzey YDS Efsanesi ve Ustalık Sertifikası",
    subtitle: "Mastery Level YDS Grandmaster Certificate",
    cefrRank: "Ustalık (Mastery / YDS 90+ Efsanesi)",
    badgeEmoji: "👑",
    theme: {
      border: "border-amber-400/60",
      accent: "#f59e0b",
      badgeBg: "bg-amber-500/20 text-amber-300 border-amber-400/40",
      textGradient: "from-amber-300 via-yellow-200 to-orange-400",
      sealColor: "#b45309",
    },
    skillsLearned: [
      "485 Akademik kelime envanterinin eksiksiz hakimiyeti",
      "Tam YDS deneme sınavlarında yüksek net ve hız optimizasyonu",
      "İleri düzey akademik retorik ve örtük anlam çıkarımı",
      "Hata analiz defterini sıfırlayan kusursuz soru çözme yetisi",
    ],
    requirements: {
      minXp: 3000,
      minWords: 430,
      minGrammar: 20,
      examPassingScore: 75,
    },
    descriptionTr: "Öğrenci YDS Master müfredatının tamamını üstün başarıyla bitirmiş, akademik İngilizce alanında en üst seviye olan C2 Ustalık unvanına hak kazanmıştır.",
  },
};

// Seviye Atlama Sınav Soruları (Her seviye için 8 soru)
export const LEVEL_UP_QUESTIONS: Record<CertificateLevel, LevelUpQuizQuestion[]> = {
  A1: [
    {
      id: "a1-q1",
      stem: "My sister and I ------- students at the new high school.",
      options: ["am", "is", "are", "be"],
      answer: 2,
      explanation: "'My sister and I' çoğul bir öznedir (we), bu yüzden 'to be' fiilinin şimdiki zaman çoğul hali 'are' kullanılır.",
    },
    {
      id: "a1-q2",
      stem: "Ahmet usually ------- coffee before going to work every morning.",
      options: ["drink", "drinks", "drinking", "drank"],
      answer: 1,
      explanation: "Geniş zaman (Simple Present) kuralı: 3. tekil şahıslar (He/She/It - Ahmet) fiile '-s' takısı alır: 'drinks'.",
    },
    {
      id: "a1-q3",
      stem: "We ------- to Ankara last weekend to visit our grandparents.",
      options: ["go", "goes", "went", "gone"],
      answer: 2,
      explanation: "'Last weekend' geçmiş zaman (Simple Past) zaman zarfıdır. 'Go' fiilinin 2. hali düzensiz olarak 'went' şeklindedir.",
    },
    {
      id: "a1-q4",
      stem: "There isn't ------- milk left in the fridge.",
      options: ["many", "some", "any", "a few"],
      answer: 2,
      explanation: "Olumsuz cümlelerde sayılamayan isimlerle 'hiç' anlamında 'any' kullanılır.",
    },
    {
      id: "a1-q5",
      stem: "Look at the sky! It is very cloudy; it ------- rain soon.",
      options: ["is going to", "was", "did", "shall"],
      answer: 0,
      explanation: "Mevcut görsel bir kanıta (kara bulutlar) dayalı gelecek tahminlerinde 'be going to' kalıbı kullanılır.",
    },
    {
      id: "a1-q6",
      stem: "She speaks English very ------- because she lived in London for two years.",
      options: ["good", "well", "better", "best"],
      answer: 1,
      explanation: "'Speaks' bir eylem fiilidir ve fiili nitelemek için sıfat (good) değil, durum zarfı (well) kullanılır.",
    },
    {
      id: "a1-q7",
      stem: "They don't have ------- car, so they travel by bus.",
      options: ["a", "an", "the", "some"],
      answer: 0,
      explanation: "Tekil ve sessiz harfle başlayan sayılabilir isimlerin önünde belirsiz tanım edatı 'a' kullanılır.",
    },
    {
      id: "a1-q8",
      stem: "Where ------- you yesterday afternoon?",
      options: ["was", "were", "are", "did"],
      answer: 1,
      explanation: "'You' öznesi için 'to be' fiilinin geçmiş zaman (Past) hali 'were' olur.",
    },
  ],
  A2: [
    {
      id: "a2-q1",
      stem: "While I ------- down the street, I ran into an old friend from school.",
      options: ["walked", "was walking", "have walked", "had walked"],
      answer: 1,
      explanation: "'While' bağlacı geçmişte devam eden bir eylemi anlatırken 'Past Continuous' (was/were V-ing) gerektirir.",
    },
    {
      id: "a2-q2",
      stem: "This mobile phone is much ------- than the one I bought last year.",
      options: ["expensive", "more expensive", "most expensive", "as expensive"],
      answer: 1,
      explanation: "İki nesne karşılaştırılırken ve 'than' bağlacı varken çok heceli sıfatların önüne 'more' gelir.",
    },
    {
      id: "a2-q3",
      stem: "He stopped ------- junk food because he wanted to live a healthier life.",
      options: ["eating", "to eat", "eat", "eaten"],
      answer: 0,
      explanation: "'Stop' fiilinden sonra bir alışkanlığı tamamen bırakmak 'stop doing something' (V-ing) şeklinde ifade edilir.",
    },
    {
      id: "a2-q4",
      stem: "I have lived in this city ------- almost ten years.",
      options: ["since", "for", "during", "ago"],
      answer: 1,
      explanation: "Present Perfect ile bir sürecin toplam süresi belirtilirken 'for' kullanılır ('since' ise başlangıç noktasını belirtir).",
    },
    {
      id: "a2-q5",
      stem: "If the weather ------- nice tomorrow, we will go for a picnic by the lake.",
      options: ["is", "will be", "was", "would be"],
      answer: 0,
      explanation: "Type 1 koşul cümlesi: 'If' cümlesinde Present Tense (is), ana cümlede 'will + V1' kullanılır.",
    },
    {
      id: "a2-q6",
      stem: "The flight was delayed ------- the dense fog at the airport.",
      options: ["because", "due to", "although", "unless"],
      answer: 1,
      explanation: "'Dense fog' bir isim tamlamasıdır. İsimlerden önce sebep bildirmek için 'due to' (veya because of) kullanılır.",
    },
    {
      id: "a2-q7",
      stem: "Have you ------- finished reading that 500-page historical novel?",
      options: ["already", "yet", "still", "ever"],
      answer: 0,
      explanation: "Bir işin beklenenden önce veya çoktan bittiğini vurgulayan sorularda 'already' kullanılır.",
    },
    {
      id: "a2-q8",
      stem: "You ------- wear a helmet while riding a motorcycle; it is mandatory by law.",
      options: ["might", "must", "can", "may"],
      answer: 1,
      explanation: "Yasal zorunluluklar ve kurallarda güçlü gereklilik bildiren 'must' kullanılır.",
    },
  ],
  B1: [
    {
      id: "b1-q1",
      stem: "The light was still on in his room; he ------- forgot to turn it off before leaving.",
      options: ["must have", "can't have", "shouldn't have", "might not"],
      answer: 0,
      explanation: "Geçmişe yönelik güçlü olumlu çıkarım ('kesinlikle unutmuş olmalı') için 'must have + V3' kalıbı kullanılır.",
    },
    {
      id: "b1-q2",
      stem: "The scientist ------- discovery changed medical history received a Nobel prize.",
      options: ["who", "which", "whose", "whom"],
      answer: 2,
      explanation: "Scientist (bilim insanı) ile discovery (keşif) arasındaki aidiyet ilişkisi 'whose' (onun keşfi) ile kurulur.",
    },
    {
      id: "b1-q3",
      stem: "The government took strict measures ------- prevent further economic decline.",
      options: ["so that", "in order to", "because", "despite"],
      answer: 1,
      explanation: "Kendisinden sonra yalın fiil (V1 - prevent) alarak 'amacıyla' anlamı veren bağlaç 'in order to'dur.",
    },
    {
      id: "b1-q4",
      stem: "She wouldn't have missed her morning train if her alarm ------- on time.",
      options: ["went off", "had gone off", "has gone off", "would go off"],
      answer: 1,
      explanation: "Type 3 geçmiş zaman koşul yapısı: If + Past Perfect (had gone off), would have + V3.",
    },
    {
      id: "b1-q5",
      stem: "By the end of this century, researchers predict that sea levels ------- significantly.",
      options: ["will have risen", "have risen", "rose", "are rising"],
      answer: 0,
      explanation: "'By + gelecekteki zaman' kalıbı daima 'Future Perfect Tense' (will have V3) gerektirir.",
    },
    {
      id: "b1-q6",
      stem: "Although the negotiation was arduous, both parties ------- reach a mutual compromise.",
      options: ["could", "were able to", "may", "used to"],
      answer: 1,
      explanation: "Zorlu bir durumun üstesinden gelip tek seferlik başarı elde etmede 'could' yerine 'was/were able to' kullanılır.",
    },
    {
      id: "b1-q7",
      stem: "The company was forced to ------- the launch due to unexpected software defects.",
      options: ["call off", "put up with", "look forward to", "break into"],
      answer: 0,
      explanation: "'Call off' ertelemek/iptal etmek anlamına gelir; bağlamdaki yazılım hataları nedeniyle lansman iptal edilmiştir.",
    },
    {
      id: "b1-q8",
      stem: "Neither the team manager nor the players ------- satisfied with the referee's verdict.",
      options: ["was", "were", "is", "has been"],
      answer: 1,
      explanation: "'Neither ... nor' yapısında fiil kendisine en yakın olan özneye (the players - çoğul) uyar.",
    },
  ],
  B2: [
    {
      id: "b2-q1",
      stem: "The committee approved the budget, ------- that strict auditing would be enforced quarterly.",
      options: ["provided", "whereas", "unless", "in spite of"],
      answer: 0,
      explanation: "'Provided that' (şartıyla/koşuluyla) koşul bildiren bir bağlaçtır ve cümlenin anlamına tam uyar.",
    },
    {
      id: "b2-q2",
      stem: "The new renewable energy project is expected to ------- significant foreign investment.",
      options: ["attract", "distract", "detract", "contract"],
      answer: 0,
      explanation: "'Attract investment' (yatırım çekmek) akademik dilde sık kullanılan güçlü bir 'collocation'dır.",
    },
    {
      id: "b2-q3",
      stem: "Not only ------- the project ahead of schedule, but they also reduced the overall costs.",
      options: ["they completed", "did they complete", "they had completed", "were they completed"],
      answer: 1,
      explanation: "'Not only' cümle başında devrik yapı (Inversion) oluşturur: yardımcı fiil özneden önce gelir (did they complete).",
    },
    {
      id: "b2-q4",
      stem: "The research suggests that regular aerobic exercise may help ------- cognitive decline in old age.",
      options: ["accelerate", "mitigate", "deteriorate", "aggravate"],
      answer: 1,
      explanation: "'Mitigate' hafifletmek, azaltmak demektir; egzersizin yaşlılıktaki bilişsel gerilemeyi hafifletmesi bağlama uygundur.",
    },
    {
      id: "b2-q5",
      stem: "------- the adverse weather conditions, the expedition crew managed to ascend the summit.",
      options: ["In spite of", "Even though", "Since", "Provided"],
      answer: 0,
      explanation: "'The adverse weather conditions' isim tamlamasıdır; zıtlık belirten ve isim alan edat 'In spite of'dur.",
    },
    {
      id: "b2-q6",
      stem: "The CEO was accused of attempting to ------- the public regarding the firm's true financial losses.",
      options: ["mislead", "reassure", "clarify", "enhance"],
      answer: 0,
      explanation: "'Mislead' yanıltmak/aldatmak demektir; şirketin gerçek zararları konusunda kamuoyunu yanıltma suçlaması uygundur.",
    },
    {
      id: "b2-q7",
      stem: "The historical documents ------- in the royal vault date back to the early Byzantine era.",
      options: ["discovering", "discovered", "having discovered", "to discover"],
      answer: 1,
      explanation: "'Which were discovered' pasif sıfat cümleciğinin kısaltması geçmiş zaman ortacı 'discovered' (V3) ile yapılır.",
    },
    {
      id: "b2-q8",
      stem: "Artificial intelligence models require vast amounts of data ------- to function with high precision.",
      options: ["in order", "so that", "such as", "as well as"],
      answer: 0,
      explanation: "'In order to + V1' (fonksiyon göstermek amacıyla) yapısı cümleyi gramer ve anlam olarak tamamlar.",
    },
  ],
  C1: [
    {
      id: "c1-q1",
      stem: "Hardly ------- into the lecture hall when the professor began the complex demonstration.",
      options: ["had the students stepped", "the students had stepped", "did the students step", "have the students stepped"],
      answer: 0,
      explanation: "'Hardly ... when' yapısı devrik başlar ve 'Past Perfect' gerektirir: 'Hardly had the students stepped'.",
    },
    {
      id: "c1-q2",
      stem: "------- all the required clinical trials, the innovative vaccine was finally granted regulatory approval.",
      options: ["Having undergone", "Undergoing", "Undergone", "To have undergone"],
      answer: 0,
      explanation: "Önce tamamlanmış olan etken süreci kısaltırken 'Perfect Participle' (Having + V3 - Having undergone) kullanılır.",
    },
    {
      id: "c1-q3",
      stem: "The philosopher argued that moral values are not immutable; -------, they evolve alongside societal norms.",
      options: ["furthermore", "on the contrary", "otherwise", "consequently"],
      answer: 1,
      explanation: "İlk cümlede 'değişmez değildir' denilmiş, ikinci cümlede tam tersine evrimleştiği belirtilmiştir: 'on the contrary' (bilakis/aksine).",
    },
    {
      id: "c1-q4",
      stem: "The rapid depletion of groundwater reserves has posed an ------- threat to regional agriculture.",
      options: ["unprecedented", "insignificant", "ambiguous", "obsolete"],
      answer: 0,
      explanation: "'Unprecedented' (eşi benzeri görülmemiş) tehdit sıfatı akademik çevre metinlerinde sıkça karşımıza çıkar.",
    },
    {
      id: "c1-q5",
      stem: "Under no circumstances ------- to reveal confidential patient data without explicit legal authorization.",
      options: ["physicians are permitted", "are physicians permitted", "physicians permit", "have physicians permitted"],
      answer: 1,
      explanation: "'Under no circumstances' (hiçbir koşulda) negatif zarf yapısı devrik dizilim gerektirir: 'are physicians permitted'.",
    },
    {
      id: "c1-q6",
      stem: "The treaty was intended to foster bilateral trade, but its ambiguous phrasing gave rise to numerous -------.",
      options: ["discrepancies", "clarifications", "conciliations", "endorsements"],
      answer: 0,
      explanation: "'Discrepancies' tutarsızlıklar/uyuşmazlıklar anlamına gelir; muğlak dilin uyuşmazlıklara yol açması bağlama uygundur.",
    },
    {
      id: "c1-q7",
      stem: "Had the archeological team not used satellite radar imaging, the subterranean palace ------- undiscovered.",
      options: ["would remain", "would have remained", "had remained", "will have remained"],
      answer: 1,
      explanation: "Geçmişte 'had + V3' ile yapılan devrik koşulun ana cümlesi 'would have + V3' (would have remained) gerektirir.",
    },
    {
      id: "c1-q8",
      stem: "The newly discovered manuscript sheds light on the ------- beliefs of early Mediterranean civilizations.",
      options: ["prevalent", "negligible", "transient", "prohibitive"],
      answer: 0,
      explanation: "'Prevalent' (yaygın/hüküm süren) inançlar anlamına gelir ve tarihi akademik metinlerde sıkça kullanılır.",
    },
  ],
  C2: [
    {
      id: "c2-q1",
      stem: "So profound ------- that the committee unanimously decided to overhaul the entire educational syllabus.",
      options: ["was the impact of the research", "the impact of the research was", "the research had such impact", "did the research impact"],
      answer: 0,
      explanation: "'So + sıfat' cümlenin başında devrik yapı kurar: 'So profound was the impact of the research that...'.",
    },
    {
      id: "c2-q2",
      stem: "The author deftly avoids didacticism, opting instead to let the moral dilemmas ------- through subtle nuances.",
      options: ["manifest", "obfuscate", "repress", "stifle"],
      answer: 0,
      explanation: "'Manifest' (ortaya çıkmak/kendini göstermek) fiili ahlaki ikilemlerin kendiliğinden belirmesini kusursuz ifade eder.",
    },
    {
      id: "c2-q3",
      stem: "Were the central bank ------- interest rates abruptly, market liquidity could suffer severe shockwaves.",
      options: ["to raise", "raised", "raising", "will raise"],
      answer: 0,
      explanation: "Geleceğe veya varsayıma dayalı 'If' devriğinde 'Were + subject + to V1' (Were the central bank to raise) kalıbı kullanılır.",
    },
    {
      id: "c2-q4",
      stem: "The anthropologist's findings effectively ------- the long-cherished dogma regarding hunter-gatherer diet.",
      options: ["substantiated", "debunked", "perpetuated", "revered"],
      answer: 1,
      explanation: "'Debunk' (çürütmek/yanlışlığını kanıtlamak) akademik yayınlarda kökleşmiş dogmaları çürütmek için kullanılır.",
    },
    {
      id: "c2-q5",
      stem: "The diplomatic envoy acted with such ------- that neither faction could reasonably accuse him of partisanship.",
      options: ["equanimity", "recklessness", "indignation", "arrogance"],
      answer: 0,
      explanation: "'Equanimity' (tarafsızlık, itidal, soğukkanlılık) diplomatın tarafgirlikle suçlanmamasını açıklayan doğru terimdir.",
    },
    {
      id: "c2-q6",
      stem: "Much as the policy was criticized by conservative pundits, it ------- to be the most resilient economic safeguard.",
      options: ["turned out", "called for", "backed down", "broke away"],
      answer: 0,
      explanation: "'Much as' (her ne kadar ... olsa da) zıtlığıyla 'turned out to be' (olduğu ortaya çıktı) yapısı kusursuz bir uyum sağlar.",
    },
    {
      id: "c2-q7",
      stem: "Only by rigorously scrutinizing empirical evidence ------- avoid the pitfalls of ideological bias.",
      options: ["can scholars", "scholars can", "scholars should", "they can"],
      answer: 0,
      explanation: "'Only by + V-ing' yapısıyla başlayan cümle devriktir: modal/yardımcı fiil özneden önce gelir (can scholars).",
    },
    {
      id: "c2-q8",
      stem: "The novel's aesthetic brilliance lies in its ability to reconcile the seemingly ------- facets of human nature.",
      options: ["irreconcilable", "superficial", "homogeneous", "redundant"],
      answer: 0,
      explanation: "'Irreconcilable' (uzlaştırılamaz görünen) niteliği ile 'reconcile' (uzlaştırmak) tezatı felsefi/akademik metnin özünü oluşturur.",
    },
  ],
};

export const ALL_LEVELS: CertificateLevel[] = ["A1", "A2", "B1", "B2", "C1", "C2"];
export const LEVEL_UP_QUIZZES = LEVEL_UP_QUESTIONS;

