// 2013-2026 YDS / YDT Yayınları Master Kelime Korpusu
// Konsolide Edilmiş Yüksek Frekanslı Sınav Kelime Havuzu
// Kaynak Temsiliyetleri: Modadil, Akın Dil, YDS Publishing, İrem Yayıncılık,
// Remzi Hoca (Remzi Özden), ODTÜ GV (Reader at Work/More to Read), Benim Hocam,
// Yargı, Yediiklim, Dilko, ELS, Pelikan, Nüans, Pegem, Kritik, Hocawebde,
// Cambridge Academic, Oxford 3000/5000, Pearson Longman Academic Collocations.
// Telif açısından lexicographical saf veri (orijinal akademik tanımlar ve örnekler).

export interface PublicationWord {
  term: string;
  meaningsTr: string[];
  type: "isim" | "fiil" | "sıfat" | "zarf" | "phrasal verb";
  level: "B1" | "B2" | "C1" | "C2" | "YDS";
  definitionEn: string;
  exampleEn: string;
  exampleTr: string;
  synonyms: string[];
  collocations?: string[];
  sourceCategory: string;
}

export const YDS_PUBLICATIONS_MASTER_CORPUS: PublicationWord[] = [
  // 1. MODADİL & AKIN DİL & YDS PUBLISHING ÖNE ÇIKAN AKADEMİK FİİLLER
  {
    term: "abate",
    meaningsTr: ["azalmak", "hafiflemek", "dinmek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To become less intense or widespread",
    exampleEn: "The storm suddenly abated, allowing rescue teams to reach the remote village.",
    exampleTr: "Fırtına aniden dindi ve kurtarma ekiplerinin ücra köye ulaşmasını sağladı.",
    synonyms: ["subside", "lessen", "diminish", "decline"],
    collocations: ["abate pain", "abate pollution"],
    sourceCategory: "Modadil / Akın Dil / YDS Pub",
  },
  {
    term: "accelerate",
    meaningsTr: ["hızlandırmak", "hızlanmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To increase in speed or rate of occurrence",
    exampleEn: "Technological innovation has accelerated economic globalization across the globe.",
    exampleTr: "Teknolojik yenilik, dünya genelinde ekonomik küreselleşmeyi hızlandırdı.",
    synonyms: ["speed up", "hasten", "quicken"],
    sourceCategory: "Akın Dil / Modadil",
  },
  {
    term: "accommodate",
    meaningsTr: ["barındırmak", "uyum sağlamak", "ihtiyacını karşılamak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To provide lodging or sufficient space for; to fit in with the wishes or needs of",
    exampleEn: "The new conference hall can accommodate more than two thousand delegates.",
    exampleTr: "Yeni konferans salonu iki binden fazla delegeyi barındırabilir.",
    synonyms: ["house", "lodge", "adapt", "adjust"],
    sourceCategory: "Cambridge / Oxford / YDS Pub",
  },
  {
    term: "adhere to",
    meaningsTr: ["bağlı kalmak", "uymak (kurala/ilkeye)"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To believe in and follow the practices of; to stick fast to",
    exampleEn: "All medical personnel must strictly adhere to hygienic safety protocols.",
    exampleTr: "Tüm sağlık personeli hijyenik güvenlik protokollerine sıkı bir şekilde uymalıdır.",
    synonyms: ["comply with", "abide by", "conform to", "stick to"],
    sourceCategory: "Remzi Hoca / İrem / Modadil",
  },
  {
    term: "advocate",
    meaningsTr: ["savunmak", "desteklemek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To publicly recommend or support a particular cause or policy",
    exampleEn: "Environmental organizations fiercely advocate the reduction of fossil fuels.",
    exampleTr: "Çevre örgütleri fosil yakıtların azaltılmasını şiddetle savunuyor.",
    synonyms: ["support", "champion", "endorse", "uphold"],
    sourceCategory: "Akın Dil / Benim Hocam",
  },
  {
    term: "allocate",
    meaningsTr: ["tahsis etmek", "ayırmak (bütçe/kaynak)"],
    type: "fiil",
    level: "B2",
    definitionEn: "To distribute resources or duties for a specific purpose",
    exampleEn: "The ministry allocated substantial funds for pediatric vaccine research.",
    exampleTr: "Bakanlık, çocuk aşı araştırmaları için önemli miktarda kaynak tahsis etti.",
    synonyms: ["assign", "allot", "designate", "earmark"],
    sourceCategory: "YDS Pub / Pegem / Dilko",
  },
  {
    term: "alleviate",
    meaningsTr: ["hafifletmek", "dindirmek", "azaltmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To make suffering, deficiency, or a problem less severe",
    exampleEn: "Emergency humanitarian aid helped alleviate hunger in drought-affected provinces.",
    exampleTr: "Acil insani yardım, kuraklıktan etkilenen vilayetlerde açlığı hafifletmeye yardımcı oldu.",
    synonyms: ["mitigate", "relieve", "ease", "soothe"],
    sourceCategory: "Modadil / Pelikan / Akın Dil",
  },
  {
    term: "anticipate",
    meaningsTr: ["ummak", "beklemek", "öngörmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To regard as probable; to expect or predict",
    exampleEn: "Economists anticipate a gradual decline in national inflation rates by late autumn.",
    exampleTr: "Ekonomistler sonbahar sonuna kadar ulusal enflasyon oranlarında kademeli bir düşüş öngörüyor.",
    synonyms: ["expect", "foresee", "predict"],
    sourceCategory: "İrem / Remzi Hoca",
  },
  {
    term: "apprehend",
    meaningsTr: ["yakalamak (suçluyu)", "kavramak", "endişeyle beklemek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To arrest someone for a crime; to understand or perceive",
    exampleEn: "Police officers managed to apprehend the suspect near the international border.",
    exampleTr: "Polis memurları şüpheliyi uluslararası sınırın yakınında yakalamayı başardı.",
    synonyms: ["arrest", "capture", "comprehend"],
    sourceCategory: "Yargı / Yediiklim / Pegem",
  },
  {
    term: "ascertain",
    meaningsTr: ["belirlemek", "kesinleştirmek", "tahkik etmek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To find something out for certain; to make sure of",
    exampleEn: "Investigative reporters are trying to ascertain whether bribery took place.",
    exampleTr: "Araştırmacı gazeteciler rüşvet olayının gerçekleşip gerçekleşmediğini kesinleştirmeye çalışıyor.",
    synonyms: ["determine", "verify", "discover", "confirm"],
    sourceCategory: "ODTÜ GV / Reader at Work",
  },
  {
    term: "assimilate",
    meaningsTr: ["özümsemek", "benimsemek", "sindirmek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To absorb and integrate people, ideas, or culture into a wider society",
    exampleEn: "Immigrants frequently struggle to assimilate into unfamiliar linguistic communities.",
    exampleTr: "Göçmenler sıklıkla alışılmadık dil topluluklarına entegre olmakta zorlanırlar.",
    synonyms: ["absorb", "integrate", "incorporate"],
    sourceCategory: "ODTÜ GV / More to Read",
  },
  {
    term: "attribute to",
    meaningsTr: ["-e bağlamak", "-e atfetmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To regard something as being caused by a specific circumstance or person",
    exampleEn: "Scientists attribute the recent heatwaves directly to human-induced emissions.",
    exampleTr: "Bilim insanları son sıcak hava dalgalarını doğrudan insan kaynaklı emisyonlara bağlıyor.",
    synonyms: ["ascribe to", "credit to", "impute to"],
    sourceCategory: "Modadil / Akın Dil / YDS Pub",
  },
  {
    term: "augment",
    meaningsTr: ["artırmak", "çoğaltmak", "büyütmek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To make something greater by adding to it; to increase",
    exampleEn: "He works weekend freelance shifts to augment his regular academic salary.",
    exampleTr: "Düzenli akademik maaşını artırmak için hafta sonları serbest vardiyalarda çalışıyor.",
    synonyms: ["increase", "expand", "enhance", "enlarge"],
    sourceCategory: "Pelikan / Yargı / ELS",
  },
  {
    term: "coerce",
    meaningsTr: ["baskı yapmak", "zorlamak"],
    type: "fiil",
    level: "C1",
    definitionEn: "To persuade an unwilling person to do something by using force or threats",
    exampleEn: "Confessions obtained when witnesses are coerced are inadmissible in legal courts.",
    exampleTr: "Tanıklar zorlanarak elde edilen itiraflar mahkemelerde delil olarak kabul edilemez.",
    synonyms: ["force", "compel", "intimidate", "pressure"],
    sourceCategory: "Yargı / Pegem / Kritik",
  },
  {
    term: "coincide with",
    meaningsTr: ["çakışmak", "aynı zamana denk gelmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To occur at or during the same time as something else",
    exampleEn: "The solar eclipse will coincide with the vernal equinox this year.",
    exampleTr: "Güneş tutulması bu yıl ilkbahar ekinoksuyla aynı zamana denk gelecek.",
    synonyms: ["overlap", "concur", "clash"],
    sourceCategory: "Remzi Hoca / İrem",
  },
  {
    term: "commence",
    meaningsTr: ["başlamak", "başlatmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To begin; to start an operation or event",
    exampleEn: "The formal peace negotiations will commence promptly at ten in the morning.",
    exampleTr: "Resmi barış müzakereleri sabah tam saat onda başlayacak.",
    synonyms: ["begin", "start", "initiate", "launch"],
    sourceCategory: "Cambridge / Oxford",
  },
  {
    term: "compensate for",
    meaningsTr: ["telafi etmek", "tazmin etmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To make up for something unwelcome or unpleasant",
    exampleEn: "Nothing could fully compensate the families for their devastating human loss.",
    exampleTr: "Hiçbir şey ailelerin yaşadığı yıkıcı insan kaybını tam olarak telafi edemezdi.",
    synonyms: ["make up for", "offset", "reimburse"],
    sourceCategory: "Akın Dil / Modadil",
  },
  {
    term: "compile",
    meaningsTr: ["derlemek", "toparlamak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To produce something by assembling information collected from other sources",
    exampleEn: "Linguists compiled a comprehensive dictionary of endangered Anatolian dialects.",
    exampleTr: "Dilbilimciler, nesli tükenmekte olan Anadolu lehçelerinden oluşan kapsamlı bir sözlük derlediler.",
    synonyms: ["assemble", "collect", "gather", "compose"],
    sourceCategory: "Dilko / ELS / Pearson",
  },
  {
    term: "comprise",
    meaningsTr: ["-den oluşmak", "kapsamak", "içermek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To consist of; to be made up of",
    exampleEn: "The Mediterranean archipelago comprises twelve inhabited volcanic islands.",
    exampleTr: "Akdeniz takımadaları, meskun on iki volkanik adadan oluşur.",
    synonyms: ["consist of", "include", "encompass"],
    sourceCategory: "ODTÜ GV / More to Read",
  },
  {
    term: "concur with",
    meaningsTr: ["aynı fikirde olmak", "hemfikir olmak"],
    type: "fiil",
    level: "C1",
    definitionEn: "To agree with someone or a conclusion",
    exampleEn: "Most geneticists concur with the findings published by the Oxford laboratory.",
    exampleTr: "Genetikçilerin çoğu, Oxford laboratuvarı tarafından yayımlanan bulgularla hemfikirdir.",
    synonyms: ["agree", "accord", "harmonize"],
    sourceCategory: "Remzi Hoca / Modadil",
  },
  {
    term: "condemn",
    meaningsTr: ["kınamak", "mahkum etmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To express complete disapproval of; to sentence someone to punishment",
    exampleEn: "World leaders gathered to condemn the unprovoked civilian airstrikes.",
    exampleTr: "Dünya liderleri sebepsiz sivil hava saldırılarını kınamak üzere toplandı.",
    synonyms: ["denounce", "censure", "criticize"],
    sourceCategory: "Benim Hocam / Pegem",
  },
  {
    term: "conform to",
    meaningsTr: ["uymak", "uyum sağlamak (standarda/kurala)"],
    type: "fiil",
    level: "B2",
    definitionEn: "To comply with rules, standards, or laws",
    exampleEn: "Imported pharmaceutical products must strictly conform to European hygiene norms.",
    exampleTr: "İthal farmasötik ürünler kesinlikle Avrupa hijyen normlarına uymalıdır.",
    synonyms: ["comply", "adhere", "obey"],
    sourceCategory: "YDS Pub / Akın Dil",
  },
  {
    term: "confront",
    meaningsTr: ["yüzleşmek", "karşısına çıkmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To meet someone face to face with hostile intent; to face up to a problem",
    exampleEn: "Societies must confront systemic corruption before economic growth can be sustained.",
    exampleTr: "Toplumlar, ekonomik büyümenin sürdürülebilmesi için sistemik yolsuzlukla yüzleşmelidir.",
    synonyms: ["face", "tackle", "encounter"],
    sourceCategory: "İrem / Hocawebde",
  },
  {
    term: "consolidate",
    meaningsTr: ["pekiştirmek", "güçlendirmek", "birleştirmek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To make something physically stronger or more solid; to combine into a single unit",
    exampleEn: "The newly elected president moved quickly to consolidate political power.",
    exampleTr: "Yeni seçilen cumhurbaşkanı siyasi gücünü pekiştirmek için hızla harekete geçti.",
    synonyms: ["strengthen", "reinforce", "merge", "unify"],
    sourceCategory: "Pelikan / Yargı",
  },
  {
    term: "curtail",
    meaningsTr: ["kısmak", "azaltmak", "sınırlandırmak"],
    type: "fiil",
    level: "C1",
    definitionEn: "To reduce in extent or quantity; to impose a restriction on",
    exampleEn: "Budget shortfalls forced the state university to curtail recreational programs.",
    exampleTr: "Bütçe açıkları, devlet üniversitesini dinlence programlarını kısmaya zorladı.",
    synonyms: ["reduce", "cut back", "diminish", "trim"],
    sourceCategory: "Modadil / Akın Dil",
  },
  {
    term: "deteriorate",
    meaningsTr: ["kötüleşmek", "bozulmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To become progressively worse in quality or condition",
    exampleEn: "Without urgent structural repairs, the medieval castle walls will rapidly deteriorate.",
    exampleTr: "Acil yapısal onarımlar olmadan, orta çağ kale duvarları hızla bozulacaktır.",
    synonyms: ["worsen", "decline", "decay", "degenerate"],
    sourceCategory: "ODTÜ GV / Reader at Work",
  },
  {
    term: "disclose",
    meaningsTr: ["açığa vurmak", "ifşa etmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To make secret or new information known",
    exampleEn: "Public officials are legally obligated to disclose their international business assets.",
    exampleTr: "Kamu görevlileri yasal olarak uluslararası ticari varlıklarını ifşa etmekle yükümlüdür.",
    synonyms: ["reveal", "uncover", "divulge"],
    sourceCategory: "Benim Hocam / Remzi Hoca",
  },
  {
    term: "disperse",
    meaningsTr: ["dağıtmak", "dağılmak", "yayılmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To distribute or spread over a wide area; to go or cause to go in different directions",
    exampleEn: "Police deployed tear gas to disperse the aggressive gathering outside the consulate.",
    exampleTr: "Polis, konsolosluk dışındaki saldırgan kalabalığı dağıtmak için göz yaşartıcı gaz kullandı.",
    synonyms: ["scatter", "disseminate", "dissolve"],
    sourceCategory: "Yargı / Dilko",
  },
  {
    term: "disseminate",
    meaningsTr: ["yaymak (bilgi/fikir)", "saçmak"],
    type: "fiil",
    level: "C1",
    definitionEn: "To spread information, knowledge, or ideas widely",
    exampleEn: "Online scholarly repositories disseminate cutting-edge medical papers without charge.",
    exampleTr: "Çevrim içi akademik depolar, en ileri tıp makalelerini ücretsiz olarak yaymaktadır.",
    synonyms: ["circulate", "distribute", "broadcast", "propagate"],
    sourceCategory: "Oxford / Cambridge / Pelikan",
  },
  {
    term: "elicit",
    meaningsTr: ["ortaya çıkarmak", "öğrenmek", "tepki çekmek"],
    type: "fiil",
    level: "C1",
    definitionEn: "To evoke or draw out a response, answer, or fact from someone",
    exampleEn: "Skillful cross-examination elicited a startling confession from the defendant.",
    exampleTr: "Usta bir çapraz sorgulama, sanıktan şaşırtıcı bir itiraf ortaya çıkardı.",
    synonyms: ["draw out", "extract", "evoke"],
    sourceCategory: "Akın Dil / Modadil / YDS Pub",
  },
  {
    term: "eradicate",
    meaningsTr: ["kökünü kazımak", "tamamen yok etmek"],
    type: "fiil",
    level: "B2",
    definitionEn: "To destroy completely; to put an end to",
    exampleEn: "Global immunization campaigns successfully eradicated smallpox in the late twentieth century.",
    exampleTr: "Küresel bağışıklama kampanyaları, yirminci yüzyılın sonlarında çiçek hastalığını başarıyla yok etti.",
    synonyms: ["eliminate", "wipe out", "exterminate", "uproot"],
    sourceCategory: "İrem / Remzi Hoca / Pelikan",
  },
  {
    term: "facilitate",
    meaningsTr: ["kolaylaştırmak", "olanak sağlamak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To make an action or process easy or easier",
    exampleEn: "Modern satellite communications facilitate rapid disaster relief coordination.",
    exampleTr: "Modern uydu haberleşmesi, hızlı afet yardım koordinasyonunu kolaylaştırır.",
    synonyms: ["ease", "expedite", "promote", "aid"],
    sourceCategory: "ODTÜ GV / More to Read",
  },
  {
    term: "hamper",
    meaningsTr: ["engellemek", "köstek olmak", "aksatmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To hinder or impede the movement or progress of",
    exampleEn: "Freezing blizzard conditions severely hampered mountain rescue attempts.",
    exampleTr: "Dondurucu tipi koşulları, dağ kurtarma girişimlerini ciddi şekilde engelledi.",
    synonyms: ["hinder", "impede", "obstruct", "thwart"],
    sourceCategory: "Modadil / Akın Dil",
  },
  {
    term: "jeopardize",
    meaningsTr: ["tehlikeye atmak", "riske sokmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To put someone or something into a situation in which there is a danger of loss, harm, or failure",
    exampleEn: "A reckless public announcement could jeopardize sensitive diplomatic negotiations.",
    exampleTr: "Pervasızca yapılan bir kamuoyu açıklaması, hassas diplomatik müzakereleri tehlikeye atabilir.",
    synonyms: ["endanger", "threaten", "risk", "imperil"],
    sourceCategory: "Benim Hocam / Pegem",
  },
  {
    term: "mitigate",
    meaningsTr: ["hafifletmek", "azaltmak", "yatıştırmak"],
    type: "fiil",
    level: "B2",
    definitionEn: "To make something less severe, serious, or painful",
    exampleEn: "Planting urban forests helps mitigate the severe heat island effect in metropolitan centres.",
    exampleTr: "Kentsel ormanlar dikmek, metropol merkezlerindeki şiddetli ısı adası etkisini hafifletmeye yardımcı olur.",
    synonyms: ["alleviate", "reduce", "diminish", "lessen"],
    sourceCategory: "YDS Core / Tüm Yayınlar",
  },

  // 2. YÜKSEK FREKANSLI AKADEMİK SIFATLAR (ADJECTIVES)
  {
    term: "ambiguous",
    meaningsTr: ["muğlak", "belirsiz", "çift anlamlı"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Open to more than one interpretation; having a double meaning",
    exampleEn: "The ceasefire agreement contains several ambiguous clauses that could spark new disputes.",
    exampleTr: "Ateşkes anlaşması, yeni anlaşmazlıkları tetikleyebilecek birkaç muğlak madde içeriyor.",
    synonyms: ["vague", "unclear", "equivocal", "obscure"],
    sourceCategory: "ODTÜ GV / Akın Dil",
  },
  {
    term: "arduous",
    meaningsTr: ["çetin", "meşakkatli", "zorlu"],
    type: "sıfat",
    level: "C1",
    definitionEn: "Involving or requiring strenuous effort; difficult and tiring",
    exampleEn: "Climbing Mount Everest requires months of arduous physical training.",
    exampleTr: "Everest Dağı'na tırmanmak aylarca süren meşakkatli fiziksel antrenman gerektirir.",
    synonyms: ["strenuous", "laborious", "exhausting", "demanding"],
    sourceCategory: "Remzi Hoca / İrem",
  },
  {
    term: "coherent",
    meaningsTr: ["tutarlı", "mantıklı", "bağlantılı"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Logical and consistent; argued or thought out well",
    exampleEn: "The committee presented a coherent strategy to combat regional water shortages.",
    exampleTr: "Komite, bölgesel su kıtlığıyla mücadele etmek için tutarlı bir strateji sundu.",
    synonyms: ["logical", "consistent", "lucid", "cogent"],
    sourceCategory: "Cambridge / Oxford",
  },
  {
    term: "conspicuous",
    meaningsTr: ["göze çarpan", "dikkat çekici"],
    type: "sıfat",
    level: "C1",
    definitionEn: "Clearly visible; attracting notice or attention",
    exampleEn: "There was a conspicuous absence of senior officials at the controversial press briefing.",
    exampleTr: "Tartışmalı basın toplantısında üst düzey yetkililerin göze çarpan bir yokluğu vardı.",
    synonyms: ["noticeable", "prominent", "salient", "striking"],
    sourceCategory: "Pelikan / Yargı",
  },
  {
    term: "detrimental",
    meaningsTr: ["zararlı", "hasar veren"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Tending to cause harm or damage",
    exampleEn: "Prolonged exposure to microplastics produces detrimental effects on marine ecosystems.",
    exampleTr: "Mikroplastiklere uzun süreli maruz kalma, deniz ekosistemleri üzerinde zararlı etkiler yaratır.",
    synonyms: ["harmful", "damaging", "injurious", "pernicious"],
    sourceCategory: "Modadil / Akın Dil",
  },
  {
    term: "diligent",
    meaningsTr: ["çalışkan", "özenli", "gayretli"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Having or showing care and conscientiousness in one's work or duties",
    exampleEn: "Diligent archival research allowed historians to uncover forgotten manuscripts.",
    exampleTr: "Özenli arşiv araştırması, tarihçilerin unutulmuş el yazmalarını gün ışığına çıkarmasını sağladı.",
    synonyms: ["hardworking", "meticulous", "conscientious", "assiduous"],
    sourceCategory: "Benim Hocam / Pegem",
  },
  {
    term: "elusive",
    meaningsTr: ["ele avuca sığmaz", "yakalanması/anlaşılması zor"],
    type: "sıfat",
    level: "C1",
    definitionEn: "Difficult to find, catch, or achieve; difficult to remember",
    exampleEn: "A definitive biological cure for Alzheimer's disease remains frustratingly elusive.",
    exampleTr: "Alzheimer hastalığı için kesin bir biyolojik tedavi, ne yazık ki hala yakalanması zor olmaya devam ediyor.",
    synonyms: ["evasive", "intangible", "fleeting"],
    sourceCategory: "ODTÜ GV / More to Read",
  },
  {
    term: "eminent",
    meaningsTr: ["seçkin", "seçkin ve ünlü", "önde gelen"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Famous and respected within a particular sphere; distinguished",
    exampleEn: "The university invited several eminent biochemists to deliver keynote lectures.",
    exampleTr: "Üniversite, açılış konuşmalarını yapmaları için birkaç seçkin biyokimyacıyı davet etti.",
    synonyms: ["distinguished", "renowned", "prominent", "illustrious"],
    sourceCategory: "YDS Pub / Dilko",
  },
  {
    term: "feasible",
    meaningsTr: ["uygulanabilir", "yapılabilir", "olası"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Possible to do easily or conveniently; plausible",
    exampleEn: "Engineers confirmed that generating power entirely through offshore wind is economically feasible.",
    exampleTr: "Mühendisler, enerjinin tamamen açık deniz rüzgarıyla üretilmesinin ekonomik olarak uygulanabilir olduğunu doğruladı.",
    synonyms: ["viable", "practicable", "workable", "achievable"],
    sourceCategory: "Remzi Hoca / Modadil",
  },
  {
    term: "formidable",
    meaningsTr: ["heybetli", "korkutan", "alt edilmesi güç"],
    type: "sıfat",
    level: "C1",
    definitionEn: "Inspiring fear or respect through being impressively large, powerful, or capable",
    exampleEn: "The defending world champions represent a formidable opponent for any young team.",
    exampleTr: "Savunmadaki dünya şampiyonları, her genç takım için alt edilmesi güç bir rakibi temsil ediyor.",
    synonyms: ["daunting", "intimidating", "fearsome", "mighty"],
    sourceCategory: "Pelikan / Yargı",
  },
  {
    term: "futile",
    meaningsTr: ["nafile", "boşuna", "sonuçsuz"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Incapable of producing any useful result; pointless",
    exampleEn: "All rescue efforts proved futile as the burning wooden structure collapsed.",
    exampleTr: "Yanan ahşap yapının çökmesiyle tüm kurtarma çabaları nafile çıktı.",
    synonyms: ["pointless", "useless", "vain", "fruitless"],
    sourceCategory: "Akın Dil / İrem",
  },
  {
    term: "indispensable",
    meaningsTr: ["vazgeçilmez", "olmazsa olmaz"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Absolutely necessary; essential",
    exampleEn: "Clean drinking water and proper sanitation are indispensable to human survival.",
    exampleTr: "Temiz içme suyu ve uygun sanitasyon, insanın hayatta kalması için vazgeçilmezdir.",
    synonyms: ["essential", "crucial", "vital", "imperative"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },
  {
    term: "inevitable",
    meaningsTr: ["kaçınılmaz", "çaresiz"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Certain to happen; unavoidable",
    exampleEn: "With automated algorithms expanding, some job displacement appears inevitable.",
    exampleTr: "Otomatik algoritmaların genişlemesiyle birlikte bazı iş kayıpları kaçınılmaz görünüyor.",
    synonyms: ["unavoidable", "inescapable", "inexorable"],
    sourceCategory: "ODTÜ GV / Reader at Work",
  },
  {
    term: "lucrative",
    meaningsTr: ["kazançlı", "karlı"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Producing a great deal of profit",
    exampleEn: "Renewable energy technology has grown into an exceptionally lucrative global industry.",
    exampleTr: "Yenilenebilir enerji teknolojisi, olağanüstü kazançlı bir küresel sektöre dönüştü.",
    synonyms: ["profitable", "rewarding", "remunerative"],
    sourceCategory: "Benim Hocam / Pegem",
  },
  {
    term: "meticulous",
    meaningsTr: ["titiz", "kılı kırk yaran", "aşırı özenli"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Showing great attention to detail; very careful and precise",
    exampleEn: "The forensic analyst followed meticulous procedures to avoid contaminating the DNA sample.",
    exampleTr: "Adli analist, DNA örneğini kirletmekten kaçınmak için son derece titiz prosedürler izledi.",
    synonyms: ["thorough", "painstaking", "scrupulous", "exacting"],
    sourceCategory: "Akın Dil / Modadil",
  },
  {
    term: "prevalent",
    meaningsTr: ["yaygın", "hüküm süren"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Widespread in a particular area or at a particular time",
    exampleEn: "Vitamin D deficiency is particularly prevalent among urban desk workers.",
    exampleTr: "D vitamini eksikliği, özellikle şehirli masa başı çalışanları arasında yaygındır.",
    synonyms: ["widespread", "common", "pervasive", "rampant"],
    sourceCategory: "Tüm Yayınlar / Pelikan",
  },
  {
    term: "ubiquitous",
    meaningsTr: ["her yerde bulunan", "yaygın"],
    type: "sıfat",
    level: "C1",
    definitionEn: "Present, appearing, or found everywhere",
    exampleEn: "Smartphones have become so ubiquitous that life without them seems unimaginable.",
    exampleTr: "Akıllı telefonlar o kadar her yerde bulunur hale geldi ki, onlarsız bir hayat hayal bile edilemez görünüyor.",
    synonyms: ["omnipresent", "pervasive", "universal"],
    sourceCategory: "Cambridge / Oxford / YDS Pub",
  },
  {
    term: "vulnerable to",
    meaningsTr: ["-e karşı savunmasız", "kırılgan"],
    type: "sıfat",
    level: "B2",
    definitionEn: "Susceptible to physical or emotional attack or harm",
    exampleEn: "Elderly individuals with chronic illnesses are exceptionally vulnerable to respiratory infections.",
    exampleTr: "Kronik hastalığı olan yaşlı bireyler, solunum yolu enfeksiyonlarına karşı son derece savunmasızdır.",
    synonyms: ["susceptible", "defenseless", "exposed", "fragile"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },

  // 3. EN SIK ÇIKAN PHRASAL VERB'LER & PREPOSITIONAL KALIPLAR
  {
    term: "account for",
    meaningsTr: ["oluşturmak (oran)", "açıklamak (nedenini)"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To form a particular proportion of; to explain the cause of",
    exampleEn: "Renewable energy installations currently account for nearly thirty percent of total national electricity.",
    exampleTr: "Yenilenebilir enerji tesisleri şu anda toplam ulusal elektriğin yaklaşık yüzde otuzunu oluşturuyor.",
    synonyms: ["constitute", "make up", "explain"],
    sourceCategory: "Tüm Yayınlar / YDS 2013-2026",
  },
  {
    term: "break through",
    meaningsTr: ["çığır açmak", "engeli yarıp geçmek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To make a sudden, major advance or discovery; to force a way through",
    exampleEn: "Biologists finally broke through when they isolated the gene responsible for cellular repair.",
    exampleTr: "Biyologlar, hücresel onarımdan sorumlu geni izole ettiklerinde nihayet çığır açtılar.",
    synonyms: ["advance", "penetrate", "discover"],
    sourceCategory: "Remzi Hoca / İrem",
  },
  {
    term: "bring about",
    meaningsTr: ["yol açmak", "sebep olmak", "meydana getirmek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To cause something to happen",
    exampleEn: "The scientific renaissance brought about massive changes in medical diagnostics.",
    exampleTr: "Bilimsel rönesans, tıbbi teşhiste muazzam değişikliklere yol açtı.",
    synonyms: ["cause", "lead to", "trigger", "give rise to"],
    sourceCategory: "Akın Dil / Modadil / YDS Pub",
  },
  {
    term: "call off",
    meaningsTr: ["iptal etmek"],
    type: "phrasal verb",
    level: "B1",
    definitionEn: "To cancel an event or agreement",
    exampleEn: "The ministry decided to call off the international symposium due to air traffic strikes.",
    exampleTr: "Bakanlık, hava trafiği grevleri nedeniyle uluslararası sempozyumu iptal etme kararı aldı.",
    synonyms: ["cancel", "abandon", "abort"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },
  {
    term: "carry out",
    meaningsTr: ["yürütmek", "uygulamak", "gerçekleştirmek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To perform or complete a planned task or experiment",
    exampleEn: "Researchers will carry out extensive laboratory trials before testing the vaccine on humans.",
    exampleTr: "Araştırmacılar aşıyı insanlar üzerinde denemeden önce kapsamlı laboratuvar deneyleri yürütecekler.",
    synonyms: ["conduct", "execute", "implement", "perform"],
    sourceCategory: "Tüm Yayınlar / YDS 2013-2026",
  },
  {
    term: "cope with",
    meaningsTr: ["başa çıkmak", "üstesinden gelmek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To deal effectively with something difficult",
    exampleEn: "Public hospitals had to develop emergency strategies to cope with the surge of patients.",
    exampleTr: "Devlet hastaneleri, hasta akınıyla başa çıkabilmek için acil durum stratejileri geliştirmek zorunda kaldı.",
    synonyms: ["handle", "manage", "deal with", "tackle"],
    sourceCategory: "Modadil / Remzi Hoca",
  },
  {
    term: "cut down on",
    meaningsTr: ["kısmak", "azaltmak (tüketim)"],
    type: "phrasal verb",
    level: "B1",
    definitionEn: "To reduce the size, amount, or quantity of something consumed",
    exampleEn: "Doctors advised the cardiac patient to cut down on saturated fats and refined sugars.",
    exampleTr: "Doktorlar kalp hastasına doymuş yağları ve rafine şekerleri kısmasını tavsiye etti.",
    synonyms: ["reduce", "curtail", "lessen"],
    sourceCategory: "Benim Hocam / Pegem",
  },
  {
    term: "dispose of",
    meaningsTr: ["elden çıkarmak", "atmak (çöp/atık)"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To get rid of by throwing away or giving or selling to someone else",
    exampleEn: "Hospitals must carefully dispose of hazardous bio-waste according to national laws.",
    exampleTr: "Hastaneler tehlikeli biyolojik atıkları ulusal yasalara uygun olarak dikkatle elden çıkarmalıdır.",
    synonyms: ["discard", "throw away", "eliminate"],
    sourceCategory: "ODTÜ GV / More to Read",
  },
  {
    term: "give rise to",
    meaningsTr: ["yol açmak", "doğurmak", "tetiklemek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To cause or induce something to exist or happen",
    exampleEn: "Unregulated industrial zoning gave rise to serious urban groundwater contamination.",
    exampleTr: "Denetimsiz sanayi imarı, ciddi kentsel yer altı suyu kirliliğine yol açtı.",
    synonyms: ["cause", "bring about", "provoke", "spark"],
    sourceCategory: "Cambridge / Oxford / Akın Dil",
  },
  {
    term: "make up for",
    meaningsTr: ["telafi etmek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To compensate for something lost, missed, or lacking",
    exampleEn: "Her exceptional diligence and enthusiasm made up for her relative lack of field experience.",
    exampleTr: "Olağanüstü gayreti ve şevki, sahadaki görece tecrübe eksikliğini telafi etti.",
    synonyms: ["compensate for", "offset"],
    sourceCategory: "İrem / Yargı / Pelikan",
  },
  {
    term: "put off",
    meaningsTr: ["ertelemek"],
    type: "phrasal verb",
    level: "B1",
    definitionEn: "To postpone something to a later date",
    exampleEn: "The executive board agreed to put off the product release until market conditions improve.",
    exampleTr: "Yönetim kurulu, piyasa koşulları düzelene kadar ürün lansmanını ertelemeyi kabul etti.",
    synonyms: ["postpone", "delay", "defer"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },
  {
    term: "rely on",
    meaningsTr: ["güvenmek", "bel bağlamak", "dayanmak"],
    type: "phrasal verb",
    level: "B1",
    definitionEn: "To depend on with full trust or confidence",
    exampleEn: "Developing nations heavily rely on international aid during natural humanitarian emergencies.",
    exampleTr: "Gelişmekte olan ülkeler doğal insani acil durumlarda büyük ölçüde uluslararası yardıma bel bağlarlar.",
    synonyms: ["depend on", "count on", "bank on"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },
  {
    term: "rule out",
    meaningsTr: ["elemek", "göz ardı etmek", "ihtimal dışı bırakmak"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To exclude or eliminate something from consideration",
    exampleEn: "Detectives cannot rule out arson until the structural engineering report is finalized.",
    exampleTr: "Dedektifler, yapı mühendisliği raporu sonuçlanana kadar kundaklama ihtimalini eleyemezler.",
    synonyms: ["exclude", "eliminate", "dismiss"],
    sourceCategory: "Remzi Hoca / Modadil",
  },
  {
    term: "stem from",
    meaningsTr: ["-den kaynaklanmak", "-den ileri gelmek"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To originate or derive from a specific source",
    exampleEn: "Much of the current social unrest stems from decades of deepening income inequality.",
    exampleTr: "Mevcut toplumsal huzursuzluğun büyük bir kısmı, onlarca yıldır derinleşen gelir eşitsizliğinden kaynaklanmaktadır.",
    synonyms: ["arise from", "originate from", "derive from"],
    sourceCategory: "Akın Dil / ODTÜ GV",
  },
  {
    term: "wipe out",
    meaningsTr: ["yok etmek", "kökünü kazımak"],
    type: "phrasal verb",
    level: "B2",
    definitionEn: "To destroy completely or eradicate",
    exampleEn: "The catastrophic volcanic explosion wiped out several ancient coastal settlements.",
    exampleTr: "Felaket boyutundaki volkanik patlama, birkaç antik kıyı yerleşimini tamamen yok etti.",
    synonyms: ["eradicate", "destroy", "annihilate"],
    sourceCategory: "Benim Hocam / YDS Pub",
  },

  // 4. AKADEMİK İSİMLER & ZARFLAR (NOUNS & ADVERBS)
  {
    term: "adversity",
    meaningsTr: ["sıkıntı", "güçlük", "talihsizlik"],
    type: "isim",
    level: "C1",
    definitionEn: "Difficulties or misfortune",
    exampleEn: "Resilience is the psychological ability to bounce back and thrive in the face of adversity.",
    exampleTr: "Direnç, sıkıntılar karşısında toparlanıp gelişebilme yönündeki psikolojik kabiliyettir.",
    synonyms: ["hardship", "misfortune", "tribulation"],
    sourceCategory: "ODTÜ GV / Pelikan",
  },
  {
    term: "breakthrough",
    meaningsTr: ["büyük buluş", "çığır açıcı gelişme"],
    type: "isim",
    level: "B2",
    definitionEn: "A sudden, dramatic, and important discovery or development",
    exampleEn: "The invention of mRNA vaccines represents an unprecedented scientific breakthrough.",
    exampleTr: "mRNA aşılarının icadı, eşi görülmemiş bilimsel bir çığır açıcı gelişmeyi temsil eder.",
    synonyms: ["advance", "innovation", "discovery"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },
  {
    term: "consensus",
    meaningsTr: ["fikir birliği", "uzlaşma"],
    type: "isim",
    level: "B2",
    definitionEn: "A general agreement among a group of people",
    exampleEn: "Scientists have reached an overwhelming consensus on human influence upon climate change.",
    exampleTr: "Bilim insanları, insanın iklim değişikliği üzerindeki etkisi konusunda ezici bir fikir birliğine vardılar.",
    synonyms: ["agreement", "accord", "harmony", "unanimity"],
    sourceCategory: "Cambridge / Oxford / Akın Dil",
  },
  {
    term: "discrepancy",
    meaningsTr: ["çelişki", "uyumsuzluk", "farklılık"],
    type: "isim",
    level: "C1",
    definitionEn: "A lack of compatibility or similarity between two or more facts",
    exampleEn: "Auditors noted a puzzling discrepancy between the recorded inventory and actual stock.",
    exampleTr: "Denetçiler, kayıtlara geçen envanter ile fiili stok arasında kafa karıştırıcı bir çelişki fark ettiler.",
    synonyms: ["inconsistency", "difference", "divergence"],
    sourceCategory: "Remzi Hoca / Yargı / Modadil",
  },
  {
    term: "infrastructure",
    meaningsTr: ["altyapı"],
    type: "isim",
    level: "B2",
    definitionEn: "The basic physical and organizational structures and facilities needed for the operation of a society",
    exampleEn: "Massive public investment is required to modernize aging railway infrastructure.",
    exampleTr: "Eski demiryolu altyapısını modernize etmek için muazzam kamu yatırımı gerekmektedir.",
    synonyms: ["facilities", "framework", "substructure"],
    sourceCategory: "Benim Hocam / Pegem / Dilko",
  },
  {
    term: "drastically",
    meaningsTr: ["ciddi ve köklü biçimde", "şiddetle"],
    type: "zarf",
    level: "B2",
    definitionEn: "In an extreme way that has a sudden, serious or noticeable effect",
    exampleEn: "Technological automation has drastically altered employment trends in manufacturing.",
    exampleTr: "Teknolojik otomasyon, imalat sektöründeki istihdam eğilimlerini ciddi ve köklü biçimde değiştirdi.",
    synonyms: ["radically", "substantially", "dramatically"],
    sourceCategory: "ODTÜ GV / Reader at Work",
  },
  {
    term: "inevitably",
    meaningsTr: ["kaçınılmaz olarak", "ister istemez"],
    type: "zarf",
    level: "B2",
    definitionEn: "As is certain to happen; unavoidably",
    exampleEn: "Unchecked urbanization will inevitably increase pressure upon municipal water supplies.",
    exampleTr: "Kontrolsüz şehirleşme, kaçınılmaz olarak belediye su kaynakları üzerindeki baskıyı artıracaktır.",
    synonyms: ["unavoidably", "inescapably"],
    sourceCategory: "Tüm Yayınlar / YDS Core",
  },
  {
    term: "substantially",
    meaningsTr: ["büyük ölçüde", "önemli derecede"],
    type: "zarf",
    level: "B2",
    definitionEn: "To a great or significant extent; considerably",
    exampleEn: "The new solar panels have substantially reduced operating electricity expenses.",
    exampleTr: "Yeni güneş panelleri, işletmenin elektrik giderlerini büyük ölçüde azalttı.",
    synonyms: ["considerably", "significantly", "vastly"],
    sourceCategory: "Akın Dil / Modadil / YDS Pub",
  },
];
